### ISSUE TITLE
Simplify package structure

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#105]
The new setup code highlights that we have quite a few packages. I think we can flatten this a bit withous decreasing readability / manageability:

navigator.views
navigator
~~navigator.utils~~ --> navigator
navigator.templatetags   # required
amcat.tests
~~amcat.management~~
~~amcat.management.commands~~
~~amcat.scripts.output~~
~~amcat.scripts.tools~~
amcat.scripts
~~amcat.scripts.forms~~
~~amcat.scripts.actions~~ --> amcat.scripts (?)
~~amcat.scripts.processors~~
~~amcat.scripts.searchscripts~~
amcat.scripts.article_upload # keep separate?
amcat.tools
~~amcat.tools.table~~
amcat.manage
amcat
~~amcat.forms~~
~~amcat.contrib.plugins~~
~~amcat.contrib~~
amcat.models
~~amcat.models.coding~~
~~accounts~~ -> navigator (?)
settings -> amcat.settings
api.rest.viewsets
~~api.rest.viewsets.coding~~
api.rest
~~api.rest.resources~~
~~api.webscripts~~
api
~~annotator.views~~ -> navigator (?)
~~annotator~~ -> navigator (?)

@martijnbastiaan  Comments?

**Comment by martijnbastiaan** [comment]
Issue replaced by https://github.com/amcat/amcat/issues/473.
