### ISSUE TITLE
empty screen on uploading codebooks

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#134]
When uploading a codebook, I get a blank screen instead of a success/error message. The codebook is not uploaded.

**Comment by CJStuart** [comment]
Currently exceptions aren't caught when an incorrect encoding or CSV dialect is selected:

![image](https://cloud.githubusercontent.com/assets/2796609/12235342/85855014-b873-11e5-92cc-72d336ba7a4d.png)
![image](https://cloud.githubusercontent.com/assets/2796609/12235353/98bdb5c2-b873-11e5-9013-f301f2834af6.png)
