### ISSUE TITLE
plea for more informative amcat_query error: include the meaning object

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#172]
In case an error is included in search queries for meaning objects that are entered in the form
mo1<tab>query1
<tab>mo1a<tab>query1a
<tab>mo1b<tab>query1b
mo2<tab>query2

You will always end up with the uninformative error:

Cannot parse query: QueryParseError: ParseException: Expected end of text (at char 20), (line:1, col:21)
Task: f2c1cdfa-5abc-4e14-9a90-63bd1fd2f664, status FAILURE.

it would be nice to see in the error whether the search query for mo1, mo1a, mo1b or mo2 produced the error

**Comment by martijnbastiaan** [comment]
Fixed in master (not sure when). For example:

    Error in query 'a': Expected quoted string, starting with " ending with " (at char 9), (line:1, col:10)
    headline:(jumbo OR lidl)
             ^
