### ISSUE TITLE
SPSS  date columns

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#173]
@nruigrok reports: when extracting e.g. coding jobs to SPSS, the date columns are not rendered properly.

**Comment by martijnbastiaan** [comment]
This has probably been fixed in https://github.com/amcat/amcat/commit/37cd29eae1146e88984fc53bb25fa0334fbd2c77, I'll test it as soon as I get my hands on a SPSS copy.

**Comment by martijnbastiaan** [comment]
Is fixed in spss code, but exporter doesn't hint the spss code properly.
