### ISSUE TITLE
White text in dropdown menus codingschema editor, impossible to read

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#196]
The dropdown menus in the codingschema editor have white text, making them impossible to read until you hover over them with the cursor

![text color](https://cloud.githubusercontent.com/assets/6417728/3721150/64db1bbe-165d-11e4-902f-4bfe0c638731.png)

Can the text color here be changed to black?

**Comment by vanatteveldt** [comment]
(closing for now, feel free to comment or open a new issue if this is still relevant)
