### ISSUE TITLE
Association-interval graphs have strange datapoint popups

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#200]
This is a minor issue, and sorry for the unclear description, but hopefully this makes more clear what I mean:

Query-> two searchstrings -> associations -> include an interval (in my case, per week) and display this as a graph. Click on one of the datapoints in the graph and this shows up:

![ass interval table](https://cloud.githubusercontent.com/assets/6417728/3736660/e210688c-172f-11e4-9c40-19985b1d492d.png)

It seems as if amcat wants to make a table with articles here, but for some reason (because the graph shows associations and not frequencies?) no articles show up, and you can see the graph's legend through the background. 

Maybe it would be better to just have a small popup in these graphs, that only shows the conditional probability and its direction?

**Comment by CJStuart** [comment]
No longer relevant in 3.4
