### ISSUE TITLE
Small problem with search results as relative values

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#204]
The query section, output option graph/table, has the option to make values relative to and exclude the first column, however which column is the first seems to be somewhat randomly defined:
![relative2](https://cloud.githubusercontent.com/assets/6417728/3765956/35fe2d80-18c0-11e4-8514-535e891f0a35.png)

![relative1](https://cloud.githubusercontent.com/assets/6417728/3765954/3001f4ca-18c0-11e4-8849-110dc9678a13.png)
Here it is not Zeit im Bild 1 (which looks like the first column) but ZIB24 which is excluded and which is used to calculate relative values. 

As the make relative to & exclude function is quite useful, isn't there a way to set the column that is used as the benchmark? When the columns consist of results per search term, this is easy (the first search term entered) but for results per medium, I don't think this is possible. 

Also, is there an easy way to make the results for a particular search term relative to all articles in the selected articleset(s)? Leaving a line empty in the keyword search window doesn't work.

**Comment by vanatteveldt** [comment]
No longer relevant for 3.4 (?)
