### ISSUE TITLE
Feature request: add button to copy articleset (not link)

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#216]
When I link an articleset to a different project, it seems to be copied there instead, as the articleset is then part of both projects. If I delete the articleset in the original project, it still stays part of the second project. However, if I then try to unlink the set in the second project, it disappears. Is this how linking/unlinking is intended to work? 

Also, I think it would be a good idea to have a button that copies linked sets to the project they are linked to, so to turn them from linked sets into owned sets, of course only accessible to those users that have admin status (in both projects?). Right now linked sets have a kind of strange in between projects status, I would prefer to be able to fully move an articleset from one project to another.

**Comment by vanatteveldt** [comment]
(closing due to inaction)
