### ISSUE TITLE
update media select list (query) when a medium no longer occurs within the project

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#217]
When I delete all articlesets that contain articles from medium X from a project and then do a query and select specific media, medium X is still on the list. In project 50, we have many 'false' medium names due to uploader problems so here the medium list is huge even though none of the articles uses the false medium names any longer. Also, query acts strangely when I select one of these deleted media:
It either 
![update deleted media 2](https://cloud.githubusercontent.com/assets/6417728/3779468/4ef1980a-1982-11e4-8eaa-670a44441887.png)

shows an error message
or
![update deleted media](https://cloud.githubusercontent.com/assets/6417728/3779469/5222efc4-1982-11e4-9fbb-f506bb678364.png)

says articles are found, but does not list them (could this be because the articlesets in which they were found were linked to another project and deleted from this project?).

So would it be possible to automatically update the media select list when all articles from that medium are removed from a project?

Alternatively, can I send a list of medium names that should be removed from project 50 so they no longer show up in the query section?

Thanks!

**Comment by martijnbastiaan** [comment]
I'm going to assume this is fixed!
