### ISSUE TITLE
Invert graph if only Y axis given (was: error message for total per medium graph)

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#219]
Query, output option graph/table, output type graph.
When I select total as the x axis and medium as the y axis, I get the following error message:
![total medium graph](https://cloud.githubusercontent.com/assets/6417728/3795515/8bfce52e-1bbc-11e4-912e-5d31b63860e3.png)

Output type = table works fine.
The graph for medium as the x axis and total as the y axis also works fine.

So maybe AmCAT gets confused here because it tries to make a bar chart on the x axis while there's no variation on the x axis variable? Maybe the error message could be changed to something that informs the user that the x and y axis should be switched for the graph to work?

**Comment by martijnbastiaan** [comment]
This has been fixed in master.
