### ISSUE TITLE
Codingschema editor annoyance (preview)

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#220]
Codingschemas -> select a codingschema -> edit fields

The field 'default' starts out as 'null'.
When using tab to move from field to field, this 'null' is removed as soon as you use tab to jump from the field 'default' to the next one. The 'default' field is then empty and amcat shows an error when you try to save the codingschema. Can this be changed so 'null' stays in place when you use tab to go to the next field?

![default](https://cloud.githubusercontent.com/assets/6417728/3795935/192132a8-1bc1-11e4-9071-60b4cbaf3238.png)

**Comment by vanatteveldt** [comment]
(closing due to inaction)
