### ISSUE TITLE
Unlinking doesn't work properly

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#221]
In project 50, I tried to unlink articleset 3463 http://amcat.nl/navigator/projects/50/articlesets/3463/
a couple of times, but in the query results it keeps showing up anyway (both amcat.nl and preview.amcat.nl). It is also still listed as an archived set for project 50.

I want to link this articleset from the current project (50) to another project, and delete it from project 50. Instead, after linking it there it shows the unlink button rather than the delete button in the original project (50). However, as I mentioned, this unlink button does not actually unlink it from any project.

**Comment by vanatteveldt** [comment]
(closing due to inaction)
