### ISSUE TITLE
Annotator layout for article codings - slightly smaller codingfields?

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#226]
I know an earlier request of mine was to make the codingfields for article codings in the annotator bigger, so sorry that I'm now asking for the opposite again, but I think the codingfields now take up a bit too much space in comparison to the variable names (labels):
![codingfields article level](https://cloud.githubusercontent.com/assets/6417728/3824947/6a802d5a-1d4e-11e4-90b8-9b92e33ff956.png)

Variable names tend to be quite long so they take up two lines, while there is a lot of white space in the codingfields on the right side of the screen. If the left border of the codingfields could be moved a little bit to the right, this would look better. Thanks!

**Comment by vanatteveldt** [comment]
(closing due to inaction)
