### ISSUE TITLE
search strings identifier doesn't show up in article list table

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#232]
I did a query using a long search string with an identifier (in red circle below), however in the results table for article list, the entire search string without the identifier showed up, instead of only the identifier. 
![searchstring no name](https://cloud.githubusercontent.com/assets/6417728/3888987/3813fbe0-2207-11e4-92e5-592ad33e5a25.png)

(playing around with extra spaces before or after the identifier did not change the results)

This happens only when I choose article list as output type (with number of hits selected under columns). When I select graph/table as output, amcat does use the identifier instead of the searchstring itself
![searchstring identifier](https://cloud.githubusercontent.com/assets/6417728/3888978/123cd270-2207-11e4-98bb-9331416e9560.png)

**Comment by martijnbastiaan** [comment]
This has been fixed in master.
