### ISSUE TITLE
ß not parsed correctly

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#234]
When I enter a word containing a ß in the search window, amcat shows this letter as Y in the table description
![sharp s](https://cloud.githubusercontent.com/assets/6417728/3889162/03d5860c-220a-11e4-8dbd-309e111b417c.png)

Also, when I searched for 'ß', I got an article containing this sentence 'Es ist immer der ORF-Redakteur X oder Y' as a result with the Y highlighted, so it seems like amcat parses it as a Y. Can this be corrected so 'ß' finds either ß or ss?

**Comment by vanatteveldt** [comment]
(closing due to inaction)
