### ISSUE TITLE
remove python scripting

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#236]
We use python scripts within elastic to extract the lead paragraphs of text. It would be better to just add the lead as one of the fields and reindex. This would remove the dependency on dynamic scripting, and remove some code from amcates.py

 Note by @martijnbastiaan  Lead should *not* be part of the has*h*

**Comment by nruigrok** [comment]
Fixed in https://github.com/amcat/amcat/commit/f48dcaf0c341384260f4f53af49846c5538c3fc7 by making a groovy script to do the same

(https://www.youtube.com/watch?v=TBQxG0Z72qM)

**Comment by vanatteveldt** [comment]
Die nel toch ;-)

**Comment by martijnbastiaan** [comment]
Ja Nel gaat lekker!
