### ISSUE TITLE
check article set elastic scripts

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#237]
We use some simple elastic scripts to manipulate set membership: (https://github.com/amcat/amcat/blob/master/amcat/tools/amcates.py#L102)

We should check if these still run with dynamic scripting disbled, if we can/should 'externalize' them, and maybe replace them with some of the new scripting options in 1.3.1 (http://www.elasticsearch.org/blog/elasticsearch-1-3-0-released/)

**Comment by vanatteveldt** [comment]
They now execute without dynamic scripting (https://github.com/amcat/amcat/commit/3c2a97b267da67efc86ee1eae25cf851fda99aad and https://github.com/amcat/amcat/commit/1c646e4fcc0a562d70f0743db233d5b846109031). I'm leaving the issue open because it would probably be quicker to preload them into elastic instead of sending them on the wire, especially as this is called for *each article* that is added to a set. See: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-scripting.html#modules-scripting

**Comment by martijnbastiaan** [comment]
Fixed in master.
