### ISSUE TITLE
export in spss-formaat geeft foutmelding

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#243]
Query > Article List > Export > SPSS
{
  "status": 500, 
  "message": "500 : An Error has occurred", 
  "description": "The server encountered an internal error or misconfiguration and\n                     was unable to complete your request.", 
  "details": "AttributeError: 'int' object has no attribute 'write'", 
  "error": true
}

**Comment by martijnbastiaan** [comment]
Fixed.
