### ISSUE TITLE
codingfields for specific article do not load

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#246]
(minor problem)
This is really strange, for one particular article in one particular codingjob, the codingfields in the annotator do not load. If I make a new codingjob for only the problematic article, the codingfields load normally. Finding a workaround was easy, but I thought I'd report it anyway.

Codingjob http://amcat.vu.nl/annotator/project/50/codingjob/5557/ 
ArticleID 47537336

![codingfields do not load](https://cloud.githubusercontent.com/assets/6417728/4091383/cf47660e-2f87-11e4-9aa0-49bbbc18a031.png)

Here it works normally: http://amcat.nl/navigator/projects/50/codingjobs/5597

**Comment by vanatteveldt** [comment]
(closing due to inaction)
