### ISSUE TITLE
uploading articles: existing articleset cannot be deselected?

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#253]
I wanted to upload articles into a new articleset (BZK HTML uploader), but accidentally clicked on an existing one
![uploader1](https://cloud.githubusercontent.com/assets/6417728/4401219/8dbc5a4c-448a-11e4-93b3-ad32c97a54fd.png)

I tried to deselect this existing articleset, but found no way to do so, so I just entered a name for the new articleset
![uploader2](https://cloud.githubusercontent.com/assets/6417728/4401226/a7a5b11a-448a-11e4-9c82-8fc25725ec3b.png)

And when submitting the upload, amcat showed this screen - no error, but not a 'valid' screen either - the only option was to go back
![uploader3](https://cloud.githubusercontent.com/assets/6417728/4401234/d997dbb2-448a-11e4-89bf-3ba9f9dae2b9.png)

Is it true that existing articlesets cannot be deselected (or is this my mistake)? If so, please change this. 
Also, an error message (instead of the current strange screen) when both entering a name for a new articleset and choosing an existing articleset would be useful.

**Comment by vanatteveldt** [comment]
(I'm tying this to #439, i.e. add some useful help messages in the new (or existing) uploader implementation)
