### ISSUE TITLE
allow codebook to be joined to date, section etc columns

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#265]
The 'metadata' columns in the coding job extraction sometimes give information on the 'wrong' level of granularity for a substantive analysis, for example some media are differentiated while that is not necessary. It would be nice to be able to add extra columns where these are categorized, e.g.

medium / mediumcat
volkskrant / newspaper
nos / TV

And the same could hold for other fields such as section. 

I think the best way to do this would be to allow a codebook to be added to the extraction options for that field, and joined on label, e.g. a codebook could be

newspaper
- volkskrant
  - vk
  - vk.nl
- ad

etc, and than the extra columns could be generated on different levels like they are now for proper codebook fields.

**Comment by martijnbastiaan** [comment]
I think this was implemented in https://github.com/amcat/amcat/commit/acf570d85f85ce4abb697fb9d0fda268a7d5cb78 and https://github.com/amcat/amcat/commit/f662834fc0915e976c8bc18609bc5a68e0a470a7.
