### ISSUE TITLE
highlighting multiple terms

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#270]
Question or feature request from Anita: is it possible to highlight more than one term per code?

We currently tried things like "term1 OR term2", "term1 term2", "term1, term2", but in each case it refuses to highlight anything, only single terms per code seem to work?

**Comment by martijnbastiaan** [comment]
This has been implemented in feature-elastic-filters. Relevant files: [amcates_queryset.py](https://github.com/amcat/amcat/blob/feature-elastic-filters/amcat/tools/amcates_queryset.py), [test_amcates_queryset.py](https://github.com/amcat/amcat/blob/feature-elastic-filters/amcat/tools/tests/test_amcates_queryset.py). See the tests for some usage examples.
