### ISSUE TITLE
adding large amounts of articles to a set takes long, gives time out

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#271]
It would be nice to be able to easily save a query result as a set, but currently it takes long and often gives a time out:

```
ConnectionError: ConnectionError(HTTPConnectionPool(host='192.168.144.110', port=9200): Read timed out. (read timeout=60)) caused by: ReadTimeoutError(HTTPConnectionPool(host='192.168.144.110', port=9200): Read timed out. (read timeout=60))
Task: f07c4f7a-f894-4690-bf5e-4c7217b9ebe6, status FAILURE.
```

![image](https://cloud.githubusercontent.com/assets/1736240/5075221/77310940-6e91-11e4-8d52-e456e08abbd2.png)

(in this case, caused by querying http://amcat.vu.nl/navigator/projects/333/query/?articlesets=11977 with the query below (133530 results) and selecting save as set)

```
“KVP” “Anti-Revolutionaire Partij” “CHU” “CDA” “SGP” “GPV” “RPF” “ChristenUnie” “KNP” “RKPN” “LPF” “Leefbaar Nederland” “PVV” “PvdV” “Boerenpartij”  “DS’70”  “Nederlandse Middenstands Partij” “Centrumpartij” “Centrumdemocraten” “D66” “PvdD” “PvdA” “CPN” “Pacifistisch Socialistische Partij” “PPR” “EVP” “GroenLinks” “Socialistische Partij” “Algemeen Ouderen Verbond” “Unie 55+” “50 Plus”
```

Edit: interestingly, the result was saved correctly: http://amcat.vu.nl/navigator/projects/333/articlesets/16755/

**Comment by martijnbastiaan** [comment]
> Edit: interestingly, the result was saved correctly: http://amcat.vu.nl/navigator/projects/333/articlesets/16755/

Elasticsearch only yields a timeout, but this does not guarantee the query is stopped entirely. Indeed, it is very likely that the query finishes if it doesn't annoy the circuit breaker.

**Comment by vanatteveldt** [comment]
It is quite possible that this is fixed by https://github.com/amcat/amcat/commit/37d39054a89c95169d8adc6a7de9797970e2d904
