### ISSUE TITLE
Option to cancel queries when the process takes too long

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#274]
Sometimes queries take very long and are likely to result in an error message, so it will be helpful in this case to just cancel the query and go back to the previous step (the query screen, date and media/articleset selected and searchstring entered into the search window like it was right before clicking the submit button).

 If I am not mistaken, the only option for canceling a query now is to close the tab, and then all selections/searchstring entering have to be done over again. There is a little 'close the window'  X in the upper right corner of the progress bar window when amcat is processing a query, but this does not seem to interrupt or cancel the query, amcat simply continues processing (or starts over?).

**Comment by martijnbastiaan** [comment]
Cancelling a query in elasticsearch is a surprisingly hard thing to do unfortunately. From a user standpoint it's fine we only pretend a query has been cancelled though..

**Comment by martijnbastiaan** [comment]
Covered in: https://github.com/elastic/elasticsearch/issues/15117. Will likely arrive this year.
