### ISSUE TITLE
black-white(dashed)-graphs on http://amcat.nl/api/action/Network

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#281]
The network visualization tool is nice for all types of purpuses,
also as a first rough attempt to create a visualization with gvedit.exe.
It would be nice if the black-white(dashed) feature could be restored
(in my remembrance this feature was restored already, but now it just gives green-red-graphs.

**Comment by martijnbastiaan** [comment]
This feature has been removed in master. We might re-add this later, if there is any demand for it.
