### ISSUE TITLE
fix travis.yml and upgrade 

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#282]
- travis.yml complains about saf, I think we can just push the import in (there are no test cases using it, I think, and I would prefer to not have a static dependency here)
- we should update to elastic 1.4 and remove python, dynamic scripting config

(and if it is easy maybe move to django 1.7 as well?)

**Comment by martijnbastiaan** [comment]
- dynamic scripting: https://github.com/amcat/amcat/commit/f48dcaf0c341384260f4f53af49846c5538c3fc7

**Comment by martijnbastiaan** [comment]
* Elastic 1.4 / Django 1.7: see latest commits
* Travis seems to get stuck on errors I cannot reproduce: https://travis-ci.org/amcat/amcat/builds/50917482, even in a fresh environment.

@vanatteveldt: can you reproduce them?
