### ISSUE TITLE
Exporting large numbers of articles

### ISSUE THREAD

**Issue by mahavi** [amcat/amcat#283]
What steps will reproduce the problem?
1. Query articleids
2. Export results (ids and full text) - tried csv and excel, tried varying numbers of articles (100, 1000, 9000 - same results)

What project did the issue occur in?
50

What query were you using? On which articlesets?
articleids

What is the expected output? What do you see instead?
Expected: Output file of results (xlsx or csv)

Result: 414 Request-URI Too Large
nginx/1.4.6 (Ubuntu)

What version of the product are you using? On what operating system?
AmCAT 3.3.2, Windows 7, Chrome  40.0.2214.111 m

Please provide any additional information below.
I want to export articleids and texts from a large number of articles (ca. 9000).  AmCAT returns an error message. I tried exporting to excel files and csv and also reduced the number of articles to export to 1000 and even 100 -  without any difference.

**Comment by vanatteveldt** [comment]
@CJStuart  can you check if you can reproduce / solve?
