### ISSUE TITLE
Tables don't show in Lynx

### ISSUE THREAD

**Issue by martijnbastiaan** [amcat/amcat#287]
*What causes the issue?* Browsing to a page with a table on it in Lynx
*What do you expect to see?* A table with my projects
*What do you see instead?* No such table.

This is probably due to datatables only working in javascript. I'm inclined to assign a 'high priority' to this bug.

Screenshot of the issue:

![screenshot from 2015-03-04 17 57 49](https://cloud.githubusercontent.com/assets/5658854/6488472/114ab990-c298-11e4-8946-1be10a9da71a.png)

**Comment by vanatteveldt** [comment]
No fix needed. Headless clients can just use telnet and local js parsing.
