### ISSUE TITLE
png of time series graph is empty

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#289]
The png-file that is produced by 

Query > output option "graph/table" > options: date-day-search term-graph > right click on graph > copy 

is empty.

Example of empty png:
![time sries isam ukraine fincris](https://cloud.githubusercontent.com/assets/6690321/6546694/7f8671d8-c5bd-11e4-868f-ba378211c948.png)

**Comment by vanatteveldt** [comment]
Thanks for the empty picture, I was actually waiting for the picture the appear for a minute :)

**Comment by vanatteveldt** [comment]
Confirmed the problem in both chrome and firefox, either they don't like the base64-images or the library we use starts with a white canvas and then adds stuff. Best workaround is to take a screenshot, there are some pretty easy programs around. @martijnbastiaan does the new graph engine for 3.4 support saving the graph?

**Comment by martijnbastiaan** [comment]
Yes!

(And I like the second picture better :P)
