### ISSUE TITLE
view items in article sets that were imported from another project

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#292]
Project 704, Justifications of (counter)terrorism, scriptiewerkgroepproject
De studenten zijn als "reader" ingeschreven maar krijgen een foutmelding te zien zodra ze willen lezen, omdat de artikelen uit een ander project geimporteerd zijn (zie foutmelding). Hoe dit te verhelpen? Moeten ze misschien een andere rol toebedeeld krijgen?

![capture](https://cloud.githubusercontent.com/assets/6690321/6689348/d9824e20-ccb9-11e4-9fa7-62f2dcaf5427.PNG)

**Comment by vanatteveldt** [comment]
As noted, you need to give that person access to project 3.
