### ISSUE TITLE
Submit button

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#294]
It would be handy to have a Submit button right underneath the query field with Summary as default option? This is default at AmCAT now and I think that is very handy to get a quick overview.

**Comment by martijnbastiaan** [comment]
As per https://github.com/amcat/amcat/commit/84f3aa0b4753d7ca7b28a3720ff333e269636d0e, summary is now the defualt script. I've added a hotkey (CTRL + Q) for executing a query. Does this solve your issue?

**Comment by martijnbastiaan** [comment]
I assume it does. Closing issue.
