### ISSUE TITLE
Changing articleset in query section

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#297]
In the new query, it is no longer possible to switch articlesets from the query section itself (you have to go back to articlesets, and then select a different articleset from there, which is annoying when e.g. you want to add or remove a single articleset from your selection). Is it possible to add a button 'change articlesets' that allows you to change articlesets from the query section, or alternatively, to keep the current articlesets selected when you go back to 'articles'  to change the articlesets there?

**Comment by martijnbastiaan** [comment]
Fixed in https://github.com/amcat/amcat/commit/7f2bde94f0baf06cf8b36ee6e7e7a76239d903cc, but with a warning.

![screenshot from 2015-04-23 21 10 37](https://cloud.githubusercontent.com/assets/5658854/7306502/e7959314-ea05-11e4-9a8a-783eb0fecc11.png)
