### ISSUE TITLE
LabelSearchString# does'nt work

### ISSUE THREAD

**Issue by doegema** [amcat/amcat#300]
Beste mensen, 

Op dit moment werkt de hashtag niet, waardoor Amcat de labels niet als zodanig herkent. Het is een kleinigheid, maar leidt er oa toe dat je in spss veel werk hebt om je variabelenamen op orde te krijgen als je een langere lijst zoektermen hebt. En het is ook lastig voor studenten doordat hun uitvoer al snel onoverzichtelijk wordt.

Vr groet, Dirk

Supermarkt#AH "Albert Heijn" C1000

**Comment by nruigrok** [comment]
Waar werk je dan in, want ik ben net bezig met allerlei hashtags en dat werkt prima

Nel

**Comment by doegema** [comment]
Hi,

Ik werk in bijv
https://amcat.nl/navigator/projects/701/query/?articlesets=17763https://amcat.nl/navigator/projects/701/query/?articlesets=17763

Ik zie net dat het wel werkt bij tabellen en grafieken, je hebt daar gelijk. Maar het werkt niet als je de hits per article wilt wegschrijven (menu onder: Article list).
Het is gewoon een beetje lastig als je met 20 of meer zoektermen werkt en die in wilt lezen in spss.

Bedacht net dat ik er wel omheen kan werken door in de uitvoer spreadsheet (csv of xls) de regel met variabele namen te vervangen door de lijst met hashtags die ik in mijn wordlist netjes had opgegeven. Studenten doen meestal niet zo ingewikkeld en ik kan er wel omheen werken. Heel dringend is het dan niet meer.

Groetjes, D
________________________________
Van: nruigrok [notifications@github.com]
Verzonden: donderdag 19 maart 2015 16:37
Aan: amcat/amcat
CC: Oegema, D.
Onderwerp: Re: [amcat] LabelSearchString# does'nt work (#300)


Waar werk je dan in, want ik ben net bezig met allerlei hashtags en dat werkt prima

Nel

**Comment by vanatteveldt** [comment]
We won't fix this in 3.3, so I've added it to the rewrite feature.

**Comment by martijnbastiaan** [comment]
Fixed in https://github.com/amcat/amcat/commit/4bf63e4a16c460c4e62e4769e2d171b7cd920c20.
