### ISSUE TITLE
Article list output option, export options gone?

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#301]
Are the article list output option and the export (article list or table from amcat to Excel/SPSS) gone in the new query section? If so, please bring them back! Especially article list -> export to Excel is what my colleagues and me use very frequently:)

**Comment by carinajacobi** [comment]
Another thing that is missing is the 'Save as Set' and 'Assign as Codingjob' options from a summary. Not sure if this is done on purpose? 

I don't think 'Assign as Codingjob' even worked in the current amcat (it said 'polling task undefined failed) - so do others want to keep this option? However, I think 'Save as Set' (with the option to add articles to an existing articleset) is essential, so please include this in the new query section.

**Comment by martijnbastiaan** [comment]
> Another thing that is missing is the 'Save as Set' and 'Assign as Codingjob' options from a summary. Not sure if this is done on purpose?

Added in https://github.com/amcat/amcat/commit/854f4507a806040ff342743aa1a21135d2dcca26 and https://github.com/amcat/amcat/commit/645814166911d33b33f38f863814d043b5ae5f88.

**Comment by martijnbastiaan** [comment]
Article list added in https://github.com/amcat/amcat/commit/4bf63e4a16c460c4e62e4769e2d171b7cd920c20.
