### ISSUE TITLE
Save query doesn't work

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#302]
When I try to save a query, amcat leads me back here:
![save query](https://cloud.githubusercontent.com/assets/6417728/6748528/fbbfee32-cee6-11e4-9cda-e63c1eaf4806.png)

**Comment by martijnbastiaan** [comment]
Fixed in https://github.com/amcat/amcat/commit/c71737f81d907784a4223e5bd70bc97ebb5b4d89 and https://github.com/amcat/amcat/commit/fae5d7d087e311b1d0081799462de9fa60261af3.
