### ISSUE TITLE
Some minor issues in new query

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#303]
1. When I select 'on' as datetype, then specify a day, and then change the datetype, e.g. to 'after', the date for 'on' is still visible, which looks a bit confusing:

![time interval](https://cloud.githubusercontent.com/assets/6417728/6748707/e6d98bc0-cee8-11e4-9484-324464227b64.png)
 
Is it possible to make amcat automatically clear the date field when you change the datetype?

2. I think the 'use in query' button should be bigger/have a bright color so it stands out more. It is quite an important button and gets a bit lost in the other information on the screen right now

![use in query](https://cloud.githubusercontent.com/assets/6417728/6748726/45d21c00-cee9-11e4-82b6-4aae22e30485.png)

3. Some language suggestions for the query screen:
- datetype: I would suggest using time interval, time period or simply date here
- mediums -> media
- ID's -> IDs

![language thingies](https://cloud.githubusercontent.com/assets/6417728/6748749/88306e76-cee9-11e4-900e-d9fe9138119f.png)

**Comment by carinajacobi** [comment]
This is a very minor thing, but for this set: https://opdakken.hmbastiaan.nl:9090/navigator/projects/1/query/?sets=46

Some results from April 2015 (?) show up in the graphs for summary even when I set the datetype to before January 2014:

![articles from the future](https://cloud.githubusercontent.com/assets/6417728/6765696/a785dfa6-cfeb-11e4-91b2-d45e5bf4d287.png)

Here the detail for only articleset 46:

![future2](https://cloud.githubusercontent.com/assets/6417728/6765713/515c7986-cfec-11e4-9687-f0472378e5d8.png)

Not really a problem in itself but I thought maybe it points to a larger problem?
These articles only show up in the date and medium graphs, not in the list of articles to the left of the graphs.

**Comment by martijnbastiaan** [comment]
> Some results from April 2015 (?) show up in the graphs for summary even when I set the datetype to before January 2014:

Woops! Fixed in https://github.com/amcat/amcat/commit/087403c45c939824f3b1ecebbeb3f9ccfaa6b954.

**Comment by martijnbastiaan** [comment]
> When I select 'on' as datetype, then specify a day, and then change the datetype, e.g. to 'after', the date for 'on' is still visible, which looks a bit confusing:

Fixed in https://github.com/amcat/amcat/commit/fb2747f52b8d2fc6a1c7dad22c3d9eef2d424f2e.

![Date selecting](https://fat.gfycat.com/PlumpInstructiveHarpyeagle.gif)

**Comment by martijnbastiaan** [comment]
The rest of your issues have been resolved in https://github.com/amcat/amcat/commit/8fde1feaa380015eaa93184cd6077cb255f4cc84 and https://github.com/amcat/amcat/commit/6d713c2525facba044f5cbf459feaf12043360cb. Thanks for reporting :)
