### ISSUE TITLE
Associations, export clustermaps?

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#304]
There are two more things from the old query section that are missing in the new one:
1. associations (conditional probability for two search terms, both displayed in amcat as a network graph and as a table for export in Excel/SPSS/etc.)
2. clustermaps as a table for export in Excel/SPSS/etc.

Are these missing from the new query section on purpose?

In the old query they were here:
![clustermap excel associations](https://cloud.githubusercontent.com/assets/6417728/6765653/5c182c50-cfea-11e4-887f-dd5a6ae99f21.png)

**Comment by martijnbastiaan** [comment]
Added associations in https://github.com/amcat/amcat/commit/adeadf1b8d62f4eb44ef337a0c56ecef07de860d: 

https://www.hmbastiaan.nl/martijn/amcat/img/associations.mp4

**Comment by martijnbastiaan** [comment]
Added SPSS to clustermap export options in https://github.com/amcat/amcat/commit/1301a87a33918f78670dd8f676fc72cc10733a3a. Issue fixed! :)
