### ISSUE TITLE
'Size' for summary

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#306]
In the new query section, we have to specify the size/number of articles displayed a priori. Would it be possible to:

a) Simply say 'all' instead of having to enter a number that we guess would be the total of number of results, if we decide before doing the query that we want to see all results?

b) Have a 'show more results' button, like in the old query section?

**Comment by martijnbastiaan** [comment]
a) I'm not sure that's a safe operation. We want to prevent DOS attacks (even if they're made unconsciously :-)).

b) Implemented in the following manner:

![Dynamic loading](https://i.imgur.com/N5BSU9y.gif)

**Comment by martijnbastiaan** [comment]
Fixed by https://github.com/amcat/amcat/commit/5d953ddb6ca92c935c98e10f0fbdfb334805bcfb.
