### ISSUE TITLE
amcat queries vastgelopen?

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#307]
Zodra je een project binnen wilt om eerst de article sets te zien verschijnt de weinig informatieve melding "Processing ..."
Gisteren lukt het nog om een zoekopdracht aan te bieden, maar toen bleek niet uit het schuifbalkje dat er nog geschoven werd (zie inhoud zoekstrings hieronder, ook geupload als codebook 647 "euposneg")

eu	(eu ecb europe* europa eurocommissaris* europarlement* barroso rompuy draghi ashton)
posnel	(aangena* aantrekkelijk* aanzien* aardig* actief* adequa* allerbest* applaus* barmhartig* befaamd* begrijpelijk* begripvol* behulpzaam* bekwa* belastingvoordeel* beschaafd* bescheidenheid* best* beter* betrokken* betrouwba* betrouwbaarheid* bevlogen* bijzonder* blij* blijde* boeiend* briljant* charmant* collegia* comfortabel* competent* conscientieu* consensus* constructie* cool* correct* coulance* creatie* daadkrachtig* dankba* dapper* deskundig* deugdelijk* dierba* diplomatiek* doelmatig* doeltreffend* dolblij* eensgezind* eensgezindheid* eenvoudig* eerlijk* effectie* efficiency* efficiencywinst* efficient* eminent* enthousiasme* enthousiast* ervaren* esthetisch* evenwichtig* excellent* excelleren* fair* fantastisch* fatsoenlijk* favoriet* feestelijk* felbegeerd* fenomenaal* fijn* filantropisch* florissant* foutlo* fraai* fris* geacht* gedreven* geduldig* geliefd* gelijkheidsdenken* gelijkwaardig* geloofwaardig* gelukkig* gemakkelijk* gemoedelijk* gemotiveerd* genia* gerechtvaardigd* gerenommeerd* gerust* geschikt* getalenteerd* geweldig* gezaghebbend* gezellig* gezond* glansrijk* goed* goedwillend* goeie* goodwill* gul* gunstig* haalba* handig* hardwerkend* hartelijk* hemels* herkenba* hoffelijk* hoogbegaafd* hooggekwalificeerd* hooggewaardeerd* hoogwaardig* hoop* hoopvol* huma* idea* ijverig* indrukwekkend* ingenieu* innovatie* inspireren* intelligent* interessant* juist* kansrijk* keurig* knap* kunde* kwalitatief* kwaliteit* kwaliteitsverbetering* leergierig* leergierigheid* leerontwikkeling* lef* lekker* leuk* lief lieve liefste liefde* liefdevol* lof* lofzang* lol* loya* lucratief* majestueu* makkelijk* meerwaarde* meevaller* moedig* moeiteloos* mooi* moreel morele nauwkeurig* netjes* nobel* nuttig* objectie* onpartijdig* ontplooiing* ontspannen* ontwikkeld* onverschrokken* opgelucht* opgewekt* optima* optimisme* optimistisch* overtuigend* overzichtelijk* perfect* plezier* plezierig* populair* populariteit* positief positieve prachtig* praktisch* prestigieu* prettig* prima proactie* proba* probleemlo* professionaliteit* professione* profijt* profilering* prominent* proominent* rechtvaardigheid* rekenprestatie* relevant* representatie* respect* respectabel* respectvol* rijk* ruimhartig* rust* schitterend* schoon schone sfeervol* slagvaardig* slim* smakelijk* socia* soepel* solidair* solide* sportief* standvastig* stijlvol* stimulans* strijdbaar* succesvol* sympathiek* talentontwikkeling* talentvol* tevreden* tevredenheid* toegankelijk* toegewijd* toereikend* tof* tolerant* toonbeeld* topfunctie* topinstituut* topleraar* topmens* topmusicus* topniveau* toponderzoek* topopleiding* topper* toppositie* topsector* toptalent* topuniversiteit* topvrouw* trots* trouw* uitblinker* uitstekend* vaardig* veelbelovend* veelzijdig* veilig* verantwoord* verantwoordelijk* verbeter* verbetering* verheugd* verstandig* vertrouw* vindingrijk* vlot* voldoende* vooraanstaand* voordeel* voordelig* voortreffelijk* voortvarend* vooruitgang* vooruitstrevend* vorstelijk* vrede* vreedzaam* vriendelijk* vrolijk* waar ware waarachtig* waardering* waardig* waarheid* weldenkend* welgesteld* welkom* weloverwogen* welwillend* welwillendheid* welzijn* wereldfaam* wereldklasse* werkbaar* wijs wijze winstgevend* zalig* zelfstandig* zinvol* zorgvuldigheid* zorgza*)
negnel	(aanklager* aanvaring* absurd* achtelo* achterlijk* achteruitgang* aderlating* afkeer* afkerig* afkeuring* afschuwelijk* afwijzing* agressie* akelig* alarm* allerslechtst* angst* arbitrair* arm* armoeiig* armzalig* arrogantie* asociaal* bandeloos* bang* bars* bedenkelijk* bedreiging* bekaaid* bekrompen* belachelijk* bemoeizuchtig* benepen* beroerd* berucht* beschuldiging* besmet* bespottelijk* bestraffing* betreurenswaardig* beu* bevreesd* bezorgd* bits* bitter* boegeroep* boete* boos* boosdoener* boosheid* buikpijn* bureaucratisch* censuur* chaos* conflict* contraproductief* corrupt* corruptie* crimineel* crisis* cynisch* debacle* demagogie* demagogisch* depressie* depressie* desastreus* desinteresse* destructie* diefstal* diplomafraude* discriminatie* diskrediet* dodelijk* doello* dof* dom* dood* doodzonde* draconisch* dramatisch* dreigement* dreiging* drogreden* dubieus* dupe* duur dure dwaas* eenheidsworst* eenzaam* egoistisch* eng* exorbitant* extremistisch* failliet* faillissement* fataal* fiasco* fout* fraudeur* frustratie* funest* gebrek* gebrekkig* gecompliceerd* gedragsprobleem* gedupeerden* gek* geldgebrek* geldverslindend* gemeen gemene genant* gepolariseerd* gesjoemel* gestoord* gevaar* gevaarlijk* gevangenisstraf* gevarenzone* gevecht* gevreesd* geweld* geweldsincident* geweldsmisdrij* gitzwart* gotspe* grauw* grimmig* haat* hachelijk* hekel* hinderlijk* hoofdpijndossier* hoofdschuddend* hoongelach hopeloos* huiverig* hulpbehoevend* hypocriet* hysterisch* idioot* ijzingwekkend* illegaal* imbeciel* impopulair* improductief* inbreuk* incapabel* inconsequent* inconsistent* ineffectie* inflatie* ingewikkeld* inhoudsloos* irritant* irritatie* jaloezie* jammer* kaalslag* kansarm* kanslo* klacht* knettergek* knieschot* kortaf* kortzichtig* krachteloos* kredietcrisis* krimpgebied* krimpregio* kritiekpunt* kwaad* kwalijk* kwetsba* kwijt* laaggeletterdheid* laf* laks* lamlendig* langstudeerderboete* last* lastig* lawaai* leed* leegloop* leerachterstand* leerprobleem* lerarentekort* liefdeloos* lomp* lui* machtelo* machtsmisbruik* malafide* maniakaal* marginaal* miljoenenfraude* minachting* minzaam* mis* misbruik* misdadig* mishandeling* misstand* moedeloos* moeilijk* moeite* moeizaam* mokerslag* moord* naar* nachtmerrie* nadeel* nadelig* nalatig* nederlaag* negatie* nekschot* nepotisme* niet-integer* nood* noodgedwongen* nutteloos* obstakel* omslachtig* omstreden* onaangenaam* onaantrekkelijk* onaanvaardbaar* onacceptabel* onbegrijpelijk* onbegrip* onbehagen* onbehoorlijk* onbeschaafd* onbeschoft* onbespreekbaar* onbetaalbaar* onbetrouwbaar* ondergang* ondermaats* ondeugdelijk* ondoelmatig* onduidelijk* oneerlijk* onenigheid* onervaren* onevenredig* onfatsoenlijk* onfris* ongecontroleerd* ongegrond* ongelijk* ongelijkheid* ongeloofwaardig* ongelukkig* ongemakkelijk* ongemotiveerd* ongenoegen* ongenuanceerd* ongeoorloofd* ongeregeldhe* ongewenst* ongunstig* onheilspellend* onherstelbaar* onhoudbaar* onjuist* onmogelijk* onnodig* onrecht* onrechte* onrechtmatig* onrechtvaardig* onredelijk* onrust* onterecht* ontevreden* ontsteltenis* ontslag* ontzet* onveilig* onverantwoord* onverbiddelijk* onvergeeflijk* onverstandig* onvoldoende* onvrede* onvriendelijk* onwaarhe* onwelgevallig* onwelwillend* onwenselijk* onwerkbaar* onwetendheid* onwettig* onwil* onzalig* onzeker* onzekerheid* onzin* onzinnig* onzorgvuldig* oorlog* ophokuur* opportunistisch* ordinair* overbodig* overdreven* overhaast* overmatig* overreding* overtreding* paniek* passief passieve pech* perikel* perspectieflo* pervers* pessimistisch* pijn* pijnlijk* populistisch* probleem* probleemgeval* probleemgroep* probleemleerling* problematiek* problematisch* profiteurscultuur* puinhoop* raar* raddraaier* ramp* rampzalig* rancune* rancuneu* recalcitrant* reputatieschade* respectloos* ridicuul* riskant* rot* ruzie* saai* scepsis* sceptisch* schaamtelo* schade* schadelijk* schandaal* schandalig* schande* schandelijk* schietpartij* schimmig* schoffering* schokkend* schra* schrijnend* schrikbarend* schril* schuld* schuldgevoel* schuldig* seksisme* slachtoffer* slecht* slonzig* slordig* sluw* smaakloos* sneu* soft* somber* spijt* spijtig* spuugzat* staatsgevaarlijk* staatsschuld* stagnatie* star* stiekem* stom* stomvervelend* stout* straf* strafba* streng* strijd* studiedieven* studieschuld* studie-uitval* stug* subversief* taalachterstand* tegenstand* tegenvaller* tekort* teleurstellen* teleurstellend* teloorgang* tenenkrommen* terreur* terroristisch* tevergeefs* tragisch* treurig* triest* tweederangs* uitholling* uitval* uitzichtloos* vals* verbolgen* verdacht* verdeeldheid* verdrietig* verfoeilijk* vergeefs* verkeerd* verlies* vernietiging* verongelijkt* verontrustend* verontwaardigd* verontwaardiging* verschraling* verschrikkelijk* verslaafd* versobering* verstoord* verval* vervelend* verwerpelijk* verwijt* verzet* vies* vijand* vijandig* vijandigheid* visieloos* vleugellam* vogelvrij* vooroordeel* vreemd* vrees*  vreesd* gevreesd* vreselijk* vriendjespolitiek* vruchteloos* vuil* waardeloos* walgelijk* wangedrag* wantrouwen* wantrouwend* wantrouwig* wars* weerstand* weerzin* weerzinwekkend* weifelachtig* weigerachtig* weigering* werklo* willekeur* woede* wrang* ziek* zielig* zieltogend* zinlo* zonde zondig zondige zorgelijk* zorgwekkend* zot* zwak* zwakte*)
eupos	"(<eu>)(<posnel>)"~10
euneg	"(<eu>)(<negnel>)"~10
hoop	(hoop* hope gehoopt uitzien uitgezien vooruitzien* vooruitzicht* vooruitblik blikte vertrouw* geestdrift* belofte beloof* inspiratie inspireer* ontplooi* passie gepassioneerd geinspireerd opgelucht toekomstvisie toekomstgericht* toekomstbestendig* houvast toevlucht toeverlaat perspectief redd* gered) 
vrees	(vrees* vreze* gevreesd* schrik* schrok* geschrokken paniek angst* doodsangst* bang* doodsbang* nood noodlot* radeloos* beducht* bezorgd* benard* benauwd* beklem* ingeklem* verwar* overbelast* beroering beroerd* commotie ongerust* onrust* verontrust* stress* nerveus* nervositeit spanning* gespannen* kommer kwel)
euhoop	"(<eu>)(<hoop>)"~10
euvrees	"(<eu>)(<vrees>)"~10

**Comment by nruigrok** [comment]
Tja Jan, kun je niet wat completere zoekstring maken? Dit vindt Amcat veel
te weinig hoor...kan ie vast niet aan....





Dr. N. Ruigrok
Singel 445-V
1012 WP Amsterdam
+31-627588586
//nieuwsmonitor.org
nelruigrok@nieuwsmonitor.org

2015-03-24 0:32 GMT+01:00 Kleinnijenhuis <notifications@github.com>:

**Comment by vanatteveldt** [comment]
Elastic has great difficulty with this kind of complex phrase queries, e.g. "(lots* of* options*) (and* more* options*"~10, since it needs to check an explosive amount of possible span queries.

So, this is simply too much for amcat to do in the query screen, but we can fix this in R using the semantic network code
