### ISSUE TITLE
Query using codebooks, not everything works yet

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#308]
I tried testing a query using codebooks. Uploading a codebook with extra labels in language 'query' went without problems, editing the codebook (hiding/unhiding codes, moving codes, adding new children or labels) went fine too. Downloading the codebook however did not work, after clicking on 'download codebook' I got this:

![download codebook](https://cloud.githubusercontent.com/assets/6417728/6801814/777797ea-d22b-11e4-97eb-acfe61068ba7.png)

And in the query section, it is not possible yet to select codebooks or languages for keywords/replacements. The three dropdown menus here are empty:

![query codebook](https://cloud.githubusercontent.com/assets/6417728/6801898/dc0a8a00-d22b-11e4-8898-4fb7147ba1b8.png)

Let me know when these work, then I can test the query using codebooks further.

**Comment by martijnbastiaan** [comment]
> The three dropdown menus here are empty:

This is fixed in https://github.com/amcat/amcat/commit/eaa78a3e106d833784d071feda117391e3694c16.

https://fat.gfycat.com/ThirdThisAdeliepenguin.gif

**Comment by martijnbastiaan** [comment]
Could you e-mail the codebook you're trying to upload?

**Comment by martijnbastiaan** [comment]
I'm closing this issue, as querying codebooks now work. I've taken note of the other issues.
