### ISSUE TITLE
Amcat queries heel traag; r-server loopt met queries vast op error code 502 save file

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#310]
AMCAT zoekt heel erg traag, ook met simpele woordlijsten.
Voer je de queries op de r-server uit, dan blijft amcat soms steken in error code 502, save file (zie png)

![status code 502 save file](https://cloud.githubusercontent.com/assets/6690321/6826216/1e8cc71a-d300-11e4-9285-d5ddd4306c05.PNG)

**Comment by vanatteveldt** [comment]
Can you post the r code somewhere so I can try? e.g. on http://gist.github.com

**Comment by Kleinnijenhuis** [comment]
Beste Wouter,
r-script hieronder, wat in codebook 649 bevat als het goed is pnstrings.txt (bijgevoegd).
Succes ermee, dank dat je probeert te vinden wat het probeem is.
H groet, Jan

**Comment by vanatteveldt** [comment]
Ik ben het nu aan het draaien, alvast een paar kleine hinweise om de code net te houden:

1. gebruik projecten in plaats van setwd
2. gebruik amcat.savepassword in plaats van een ww in je script (met dank voor de redactie in dit geval)
3. al die source(.) en de meeste library(.) calls zijn onnodig, dat maakt het voor mij lastiger om te volgen
4. het maakt het voor mij een stuk makkelijker als je een stuk script post dat alleen maar datgene doet wat fout gaat, nu kost het mij meer tijd dan nodig om te kijken wat er eigenlijk gebeurt. (en vaak helpt het schrijven van een 'minimal example' al een eind om het probleem zelf op te lossen)

**Comment by vanatteveldt** [comment]
Duplicate of #307
