### ISSUE TITLE
queries leveren ineractief time-out fout, via r-server columns do not match fout

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#311]
De queries staan in codebook 16539 pnstrings. 
Ze moeten worden toegepast op articleset 8719.
interactief krijg ik een time-out fout, via de rserver een columns don't match fout.
![timeout](https://cloud.githubusercontent.com/assets/6690321/6860624/b639cc04-d42a-11e4-8208-340fb4785ac4.PNG)
![rserver columns do not match](https://cloud.githubusercontent.com/assets/6690321/6860628/c089d096-d42a-11e4-9a79-22642ca3bbe0.PNG)

**Comment by vanatteveldt** [comment]
From the R code it seems that the last query has some sort of problem. Can you post the R code somewhere so I can try running it? e.g. on http://gist.github.com ?

**Comment by vanatteveldt** [comment]
Duplicate of #307
