### ISSUE TITLE
Sample doesn't work

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#312]
I tried to make a sample from an articleset using the 'sample' button from the articleset overview. I used the following settings (though changing them didn't seem to change anything):
![sample1](https://cloud.githubusercontent.com/assets/6417728/6914063/1b83ec5c-d787-11e4-93b1-1c5d8d2768e6.png)

And then I got the following error:
![sample2](https://cloud.githubusercontent.com/assets/6417728/6914066/241df6dc-d787-11e4-8ad5-0ca8d4071578.png)

Yesterday (March 30th) afternoon, I made samples following the same procedure, and then it didn't cause any errors yet.

**Comment by vanatteveldt** [comment]
I would guess that the umlaut in the set name is the problem, can you confirm that?

**Comment by carinajacobi** [comment]
Confirmed. It only happens when I try to draw a sample from an articleset
with an umlaut in the name. For the other articlesets, sample works fine.
