### ISSUE TITLE
Issues with query tab with no articlesets selected

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#313]
If I understood it correctly, in the new query interface, you always have to select one or more articlesets first before you proceed to the query screen. Currently, you select these from the 'Articles' screen. There is still a 'Query' tab on the top left of the screen, but this leads only to this 'empty' content:

![query tab](https://cloud.githubusercontent.com/assets/6417728/6918860/3a7da6ea-d7b2-11e4-819f-af5b38000e9a.png)

and is therefore not very useful.

Maybe, instead of asking users to select their articlesets from the 'Articles' tab and then the 'use in query' button, wouldn't it be easier to have a simplified articlesets overview from the 'Query' tab, where you can only select articlesets for queries? So we leave the articleset editing/sampling/deleting under the 'Articles' tab, and move the selecting for queries to the 'Query' tab, which is then no longer 'empty' as it is now.

**Comment by martijnbastiaan** [comment]
This screen is now no longer empty.

![screenshot from 2015-04-24 15 51 42](https://cloud.githubusercontent.com/assets/5658854/7319981/e129f346-ea99-11e4-86cc-82daf0b5cb5d.png)
