### ISSUE TITLE
aanmaken set is een succes, maar toch is de set leeg

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#314]
Successfully saved set populatiesearchstring eujedenfalls n=16365 with id 18099 in project ArchiveJK, containing 16365 articles

Echter, 18099 (en op vergelijkbare wijze aangemaakte sets) zijn leeg.

Selectiecriteria voor het aanmaken van 18099:
articlesets: 18539 eu elections dec13 - 22mai14
query:
eu	(eu ecb europe* europa eurocommissaris* europarlement* barroso rompuy draghi ashton)

**Comment by vanatteveldt** [comment]
duplicate of #286
