### ISSUE TITLE
queries based on codebooks: highlight indicators not only in snippet but also in text

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#315]
Example below comes from: 
project 582 (archive JK), 
codebook  649 (pnstrings), 
search query <eu> AND <hope>

Suppose a codebook is uploaded with among others the concepts 
<eu> and <hope>. The query
<eu> AND <hope> 
nicely retrieves the articles that satisfy the query.
In the short snippets from the retrieved items that are shown on the screen the indicators of <eu> and <hope> are highlighted in red.
However, clicking on a retrieved article shows the article as plain text, without highlighting the indicators of <eu> and <hope>.
In the case of long items of which only a few sentences are relevant (e.g. NOS-journaal) this is frustrating.
Question: is it possible to highlight the indicators not only in the snippets but also the full text of the retrieved items.

**Comment by Kleinnijenhuis** [comment]
sorry, the editor does not allow for  SMALLERTHAN, GREATERTHAN bracketing
The intended query is
SMALLERTHANeuGREATERTHAN   AND  SMALLERTHANhopeGREATERTHAN

**Comment by vanatteveldt** [comment]
(closing due to inaction)
