### ISSUE TITLE
amcat config use both elastic nodes

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#316]

**Comment by martijnbastiaan** [comment]
Err, I don't think we know what this means anymore, so I assume it's fixed?

**Comment by vanatteveldt** [comment]
We do actually, we should allow celeryconfig to use multiple nodes. Currently, it connects only to one of them , which takes away the redundancy.

**Comment by vanatteveldt** [comment]
(closing due to inaction)
