### ISSUE TITLE
save set to different project

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#317]
In the query -> actions -> save as set command, allow saving to a (new set in a) different project as well.

Note that It used to be possible to append to an existing set, I'm not sure that is still possible?

**Comment by martijnbastiaan** [comment]
Added AppendArticlesetAction in https://github.com/amcat/amcat/commit/be191d699ff7a4d6396bc7b56768172e21c270b7:

![appendtoset](http://fat.gfycat.com/DecisiveHealthyDog.gif)

It pulls its articleset choices depending on the selected project, as you can see above.

**Comment by martijnbastiaan** [comment]
Fixed in https://github.com/amcat/amcat/commit/bf3d7da02004eb679d1d0d5cb245fe54f06baff2.
