### ISSUE TITLE
reorder and rename query output options

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#318]
'more' should become actions, and clustermap should be removed

if needed, clustermap and association can form a group 'network' together.

**Comment by martijnbastiaan** [comment]
Fixed in https://github.com/amcat/amcat/commit/dd8edb9547da35ab777878749597d4fcd06758b8.

![screenshot from 2015-04-20 17 23 05](https://cloud.githubusercontent.com/assets/5658854/7233569/0c7f5c40-e782-11e4-83e0-30ea531e549c.png)
