### ISSUE TITLE
articleset provenance

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#322]
In the save as set screen, hide provenance and auto-generate (now as json string, later as link to saved query?)

Instead, add description text area

**Comment by martijnbastiaan** [comment]
What I take from this is the following:

1. We should rename `ArticleSet.provenance` to `ArticleSet.description`
2. Add a field `task` which is, obviously, a FK to a Task.

This way we can easily rerun queries (even when they're not explicitly saved?) and gradually extend support to other scripts as well.

Thoughts?

**Comment by vanatteveldt** [comment]
apparently not :)
