### ISSUE TITLE
Create screen for switching article sets 

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#323]
Create the screen for switching/selecting article sets

- add option to use from different project (special prominence for featured sets?)
- should there be a button on the query screen as well? should that open this screen as a modal and try to preserve query, selection etc?

**Comment by martijnbastiaan** [comment]
Fixed in https://github.com/amcat/amcat/commit/7f2bde94f0baf06cf8b36ee6e7e7a76239d903cc, but with a warning.

![screenshot from 2015-04-23 21 10 37](https://cloud.githubusercontent.com/assets/5658854/7306502/e7959314-ea05-11e4-9a8a-783eb0fecc11.png)
