### ISSUE TITLE
cannot upload pdf ord word documents

### ISSUE THREAD

**Issue by anneloredeprez** [amcat/amcat#325]

**Comment by martijnbastiaan** [comment]
Could you provide screenshots of what you're trying to do? You can use either https://getsharex.com/ or http://getgreenshot.org/ if it doesn't work out with the builtin Windows tools. Additionally, could you e-mail the files you're trying to upload to me (martijn {-at-} hmbastiaan {-dot-} nl)?

**Comment by vanatteveldt** [comment]
Ik had haar gevraagd dit issue aan te maken. Als je een word of pdf Doc upload bij plain text zegt hij "failure" op amcat.nl.

**Comment by martijnbastiaan** [comment]
Clearly an issue for 'chef uploader' :-)

**Comment by CJStuart** [comment]
This is fixed in 3.3.2 and 3.4
