### ISSUE TITLE
query preview: internal error 500

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#328]
preview komt met popupscherm om opnieuw te vragen naar inlognaam en password; vliegt bij een opdracht daarna er uit met internal server error 500; zie png
![unknown error](https://cloud.githubusercontent.com/assets/6690321/7264723/403d46ce-e88f-11e4-9e72-a1c6c9adbcba.PNG)

**Comment by martijnbastiaan** [comment]
> preview komt met popupscherm om opnieuw te vragen naar inlognaam en password;

Fixed in https://github.com/amcat/amcat/commit/be0bf3400a8af5fea78f24507f9a23cc624f871a.

> vliegt bij een opdracht daarna er uit met internal server error 500; zie png

Je zoekt op het jaar 201 :-). Maar, amcat zou inderdaad een betere foutmelding moeten geven. Fixed in https://github.com/amcat/amcat/commit/bb9fe71b19c91dd3e39090aa0455a4dd5a08fefe.
