### ISSUE TITLE
Saved query not clickable

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#333]
Een nieuwe query wordt opgeslagen, maar als je erop klikt krijg je foutmelding:
Eerst de nieuwe query:
![image](https://cloud.githubusercontent.com/assets/6438205/7326993/f58ed0d8-eac9-11e4-9f90-613ba00e6c40.png)

hieronder foutmelding
![image](https://cloud.githubusercontent.com/assets/6438205/7326980/d9c4e5c2-eac9-11e4-83ac-1286fec2a525.png)

**Comment by martijnbastiaan** [comment]
Yikes, fixed in previous commit. Newly saved queries shouldn't cause problems.
