### ISSUE TITLE
update codebook: oude versie kan weg, bij dezelfde concepten alleen de query vervangen

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#335]
Bij coding>codebook>import codebook>codebook:update existing codebook blijkt dat de nieuwe versie van het codebook dubbele of (na herhaalde updates) tal van entries voor hetzelfde concept kan krijgen. 

As een concept in de "nieuwe" versie gelijk is aan een concept uit het bestaande codebook dan zou alleen de query overschreven moeten worden.

**Comment by vanatteveldt** [comment]
(closing due to inaction)
