### ISSUE TITLE
dates in preview

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#336]
The dates on the figures right next to the summary do not correspond with the actual dates of the artiles. They seem to differ with a few months for RTL for example in http://preview.amcat.nl/navigator/projects/736/query/?sets=18213,18547,18548,18549#summary

The show stops in july and august but starts in september. according to the figures though it only starts in october:

![image](https://cloud.githubusercontent.com/assets/6438205/7422837/58b49b8c-ef90-11e4-8f9c-4484215fb72d.png)

**Comment by martijnbastiaan** [comment]
Fixed!
