### ISSUE TITLE
Ask for confirmation before overwriting saved query

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#338]
If you open a saved query, change the articlesets and/or keywords and click on 'Save query', amcat overwrites the saved query without asking for a confirmation. Wouldn't it be better to have it ask for a confirmation first?

**Comment by martijnbastiaan** [comment]
I'm not sure. I don't think Word (for example) asks for a confirmation. Admittedly, Word has undo capabilities, but still..

**Comment by martijnbastiaan** [comment]
@vanatteveldt what do you think?
