### ISSUE TITLE
Highlighter for keywords, keyword in context (summary) back?

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#339]
There are two features missing from the new query that I found quite useful in the old query:

1) Highlighting the query keywords in texts (perform a query, click on the article from the summary or table, and the article opens in another tab with the query words highlighted)

old:
![highlight old](https://cloud.githubusercontent.com/assets/6417728/7429027/8b1ffd2c-effa-11e4-95ed-bc0c328a7884.png)

new:
![highlight new](https://cloud.githubusercontent.com/assets/6417728/7429028/8f1ee10e-effa-11e4-9268-5a9c5a40b05d.png)

Would it be possible to bring these back?

**Comment by vanatteveldt** [comment]
I've split this into 2 issues, see also #381
