### ISSUE TITLE
error on getting article list with text

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#340]
cc @nruigrok 

On a local install (amcat-dev:~nel/amcat) if I try to get an atricle list with the text column from http://localhost:8080/navigator/projects/1/query/?sets=19#articlelist, I get an error:

```
RequestError at /api/v4/search

TransportError(400, u'{"count":0,"_shards":{"total":5,"successful":0,"failed":5,"failures":[{"index":"nel","shard":0,"reason":"BroadcastShardOperationFailedException[[nel][0] ]; nested: QueryParsingException[[nel] [constant_score] requires either \'filter\' or \'query\' element]; "},{"index":"nel","shard":1,"reason":"BroadcastShardOperationFailedException[[nel][1] ]; nested: QueryParsingException[[nel] [constant_score] requires either \'filter\' or \'query\' element]; "},{"index":"nel","shard":2,"reason":"BroadcastShardOperationFailedException[[nel][2] ]; nested: QueryParsingException[[nel] [constant_score] requires either \'filter\' or \'query\' element]; "},{"index":"nel","shard":3,"reason":"BroadcastShardOperationFailedException[[nel][3] ]; nested: QueryParsingException[[nel] [constant_score] requires either \'filter\' or \'query\' element]; "},{"index":"nel","shard":4,"reason":"BroadcastShardOperationFailedException[[nel][4] ]; nested: QueryParsingException[[nel] [constant_score] requires either \'filter\' or \'query\' element]; "}]}}')
````

Full error: https://gist.github.com/vanatteveldt/277eff0ec36b5a8adc67

Looking at the stack, it seems that it is indeed trying to run an empty query:

````
/home/nel/amcat/amcat/tools/amcates.py in count
            result = self.es.count(index=self.index, doc_type=settings.ES_ARTICLE_DOCTYPE, body=body)

[...]
body 	{u'query': {u'constant_score': {}}}
query 	None
filters 	{}
```

Screenshot showing the request that fails:

![err](https://cloud.githubusercontent.com/assets/1736240/7429140/8d855376-effc-11e4-9b8c-691c94de889f.png)

**Comment by martijnbastiaan** [comment]
I'm not sure how to solve this problems. The error occurs as it checks for a project id on the elastic results, to prevent users with readmeta to extract text from articles. (And this seems to be missing on [newer] articles?) I thinks this results in various undesirable properties: 

1. Users uploading a duplicate (for example by uuid) might not be able to extract their own article's text (as the original has another projectid).
2. It's a relatively complex check (see below)

I don't think elastic should be concerned with project logic at all. I therefore propose an additional GET parameter 'project', with which we can refuse/allow text searches with a single check. Without the project parameter, search should always refuse to serve the text property.

**Comment by martijnbastiaan** [comment]
This is now more or less fixed in https://github.com/amcat/amcat/commit/7095958c92d4bbba2d0d4e3a31fc7d701e687598. When requesting `col=text` SearchResource expects a project parameter. It's still a bit awkward, as it now behaves differently when searching with `col=text` or without.

Anyway, I think this fixes it for now.
