### ISSUE TITLE
Aggregation table layout

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#342]
Compared to the aggregation tables (date x medium, search term x date etc.) in amcat.nl, those in preview.amcat.nl have very high rows when the amount of columns is high. With large tables, you quickly run into the problem that you can no longer see the column headings for the lower rows. Also, the background color is white for all cells, which makes large tables a bit confusing. 
Example: 
old
![table old](https://cloud.githubusercontent.com/assets/6417728/7429291/752d83ea-efff-11e4-805a-5e3048b3c295.png)

new
![table new](https://cloud.githubusercontent.com/assets/6417728/7429299/7db1951a-efff-11e4-990b-e4b025a3a7a0.png)

Can the lower rows and white-colored-white background patterns of the tables in amcat.nl also be used for the new query?

**Comment by martijnbastiaan** [comment]
Both issues are fixed in https://github.com/amcat/amcat/commit/0031708640d3176ecddb17959a8e6eb4f3f17b62 and https://github.com/amcat/amcat/commit/9a116d2b3df2d2cf162e74eb781b6255c4c0216e.
