### ISSUE TITLE
'Relative to' for aggregations doesn't work?

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#344]
I can't get 'relative to' to work in aggregation tables. Either it shows an error like this
![relative to](https://cloud.githubusercontent.com/assets/6417728/7441587/47e93b0a-f0ee-11e4-8296-2e8ca32ff7ec.png)

or an empty table
![relative to2](https://cloud.githubusercontent.com/assets/6417728/7441588/4d4e7cd6-f0ee-11e4-8d3b-4df530e71bcd.png)

What is going wrong here? I think it would be useful to make the explanation of this feature within  AmCAT more clear, or I can explain it in the Wiki, but then I need to understand it first.

**Comment by martijnbastiaan** [comment]
It now dynamically fetches columns:

![relative to](http://giant.gfycat.com/ImpureImmaculateHedgehog.gif)
