### ISSUE TITLE
searching on url doesn't work

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#346]
in the preview it won't work to search on an url from one of the blogs. see: 

![image](https://cloud.githubusercontent.com/assets/6438205/7454396/8a0303b4-f273-11e4-998d-845aa1fbf448.png)

**Comment by vanatteveldt** [comment]
Let's check this when we implement the flexible meta fields? (i.e. 3.5)

**Comment by martijnbastiaan** [comment]
This should now work (in master) as url is not an analyzed field and therefore matches exactly. (I have not tested it.) For all other text fields the following syntax applies for an exact match:

```
field.raw:to_match
```

The syntax may be a little strange for (new) users. Maybe we should introduce some "match exactly" operator in the syntax. @vanatteveldt @nruigrok What would do you think / what would you like to see?

**Comment by martijnbastiaan** [comment]
Works in master, using the following syntax:

```
url:"http://digitaleeditie.nrc.nl/digitaleeditie/NH/2016/11/20161201___/NH-5601074/article.html"
```
