### ISSUE TITLE
Read timeout=300 error: wat is het probleem?

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#364]
ConnectionError: ConnectionError(HTTPConnectionPool(host='192.168.144.100', port=9200): Read timed out. (read timeout=300)) caused by: ReadTimeoutError(HTTPConnectionPool(host='192.168.144.100', port=9200): Read timed out. (read timeout=300))
Task: db575d58-4d20-406d-afd1-79b549420aa9, status FAILURE.

Wat is hier het probleem? Wederom dat de zoektermenlijst (van student Sammy Mostard die issuenieuws bij de Provinciale Statenverkiezingen met 199 concepten en 5096 zoektermen wil onderzoeken) te lang dan wel te complex is?

**Comment by vanatteveldt** [comment]
Ik denk een tijdelijk probleem
