### ISSUE TITLE
save as set: nog steeds administratief puin, lijkt bovendien nodeloos tijdrovend

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#365]
1, Ik meende begrepen te hebben dat de mogelijkheid gemaakt zou worden om bij "save as set" de (itemnummers uit de) set direct uit te schrijven naar een project naar keuze, om zo te voorkomen dat in de basissets 2, 3 en 10 de chaos steeds groter wordt. Ik kijk er misschien aan voorbij, maar ik slaag er niet in ze ergens anders weg te schrijven..

2. "save as set" lijkt nodeloos veel tijd te vragen. Eerst duurt het heel lang voordat je de "summary" uitgeschreven hebt; dan komt er een traag proces op gang bij save as set waarbij je verteld wordt dat bijvoorbeeld intussen 38/90 van het werk gedaan is. Maar dat werk zou toch alleen het kopieren van een lijst van itemnummers mogen behelzen? Bovedien lijkt het proces soms wel een uur te stoppen, in mijn geval nu bij 70/90

**Comment by martijnbastiaan** [comment]
Ha Jan,

Deze bugs zijn opgelost in AmCAT 3.4. Die is nog niet beschikbaar helaas, dus je zult nog even moeten wachten!
