### ISSUE TITLE
AMCAT does not distinguish AD and VK articles as different media outlets

### ISSUE THREAD

**Issue by markboukes** [amcat/amcat#368]
Hey there,

When i upload LexisNexis articles into AMCAT from the newspapers Volkskrant and Algemeen Dagblad, it does not save them in the "medium" variable as these newspapers but as "De Persgroep Nederland BV". 

In the attachment i show you the files that we retrieved from LexisNexis for these two newspapers.

**Comment by markboukes** [comment]
![ad vk lexisnexis files](https://cloud.githubusercontent.com/assets/12925601/8192926/b92e6f96-1471-11e5-8be1-03b07a38d9ef.jpg)

**Comment by vanatteveldt** [comment]
@carinajacobi sorry, misklik :)

I'll have a look, it's generally not very difficult to fix (but LN is quite annoying...)

**Comment by markboukes** [comment]
By the way, i just noticed the same goes wrong for newspaper Trouw. Thanks for looking into it!!

**Comment by vanatteveldt** [comment]
This should be fixed now, please reopen if it doesn't work for you!

**Comment by markboukes** [comment]
Great, it works! 
Thanks, @vanatteveldt!
