### ISSUE TITLE
Uploading LexisNexis articles, same datafile leads to different number of articles

### ISSUE THREAD

**Issue by markboukes** [amcat/amcat#369]
Hi another issue, when i uploaded a ZIP.file with articles from Noordhollands Dagblad (but also Volkskrant) it create an article set with 628 articles (this is also the number of articles I downloaded from LexisNexis). When i uploaded the same file half an hour later in another project, it only created an article set of 513 articles. 

Does anybody know why?

I manually looked in the data for which articles where missing in the file that was uploaded the second time. It seem to be articles that were presented twice in the LexisNexis file. Question remains why this happens the first time not, but occurs the second time (and all times after it). Also, I'm not sure whether all the missing articles are actually duplicates.

Thanks once again!

Mark.

**Comment by vanatteveldt** [comment]
My guess is that articles are only deduplicated compared to existing articles on upload. So, the first time there is no deduplication (because the articles don't exist yet), but the second time the set is deduplicated because the articles already exist.

**Comment by vanatteveldt** [comment]
If you don't think this is the case (And this is still relevant to you), can you send me the files and reopen this issue?
