### ISSUE TITLE
Selecting a random sample of articles in Amcat

### ISSUE THREAD

**Issue by markboukes** [amcat/amcat#371]
The random sampling function in Amcat seems not to work. 

When I follow the approach described on the bottom of this page: http://wiki.amcat.nl/Article_list 
I don't get a random sample, but just a list of the first XXX articles depending on the number of articles that i typed at "Limit to XXX results".

Hope this is easy to fix.

Thank you very much, once again,
Mark.

**Comment by vanatteveldt** [comment]
@CJStuart , can you have a look? If you can, please fix in the release version as it should be a small fix (I hope :))

**Comment by CJStuart** [comment]
The wiki page on this subject was incorrect or outdated. Random samples can be made using the `sample` button in the toolbar of the article list. This function allows you to create a new article set containing the randomly sampled items. I updated the wiki accordingly.
