### ISSUE TITLE
(Properly) implement progress bars for QueryActions

### ISSUE THREAD

**Issue by martijnbastiaan** [amcat/amcat#372]
We've had progress bars for a while now, with an implementation of a progress monitor (inspired by Java). I thought we implemented submonitors too, but I might be mistaken. However it may be, QueryActions need to be checked for proper usage of monitors, while making sure their 'subactions' also support progress monitoring.

(Marking this as a bug, as some actions implement progress monitoring completely wrong [thanks @martijnbastiaan..], often yielding progress >100%..)

**Comment by vanatteveldt** [comment]
(sorry :))

**Comment by martijnbastiaan** [comment]
Fixed with the introduction of https://github.com/amcat/progressmonitor
