### ISSUE TITLE
Results table: include (optional) rows with no articles

### ISSUE THREAD

**Issue by joepschaper** [amcat/amcat#374]
When you extract a table amcat skips the rows with 0 articles. That can be annoying if you want to later make a graph, or even a publishable table. It is possible to make an option where the periods with 0 articles are not skipped, but just get the number 0?

Many thanks!

Joep

**Comment by vanatteveldt** [comment]
@CJStuart Is this fixed / fixable with your update to add zeroes in graphs?

**Comment by CJStuart** [comment]
I think i implemented that by filling in the missing zeroes when loading highcharts in javascript, (in amcat-query-js/query/utils/tools.js) so i don't think so. This could of course be moved to the server side.

**Comment by CJStuart** [comment]
I'm going to reimplement this server side as I'm running into more issues with the current solution.

**Comment by CJStuart** [comment]
Closed in fbe571b
