### ISSUE TITLE
queries in arabic don't find results

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#375]
As reported by Christian Baden: Searching for إرهابي yields "0" results in the summary, but then does list a number of results. They are running a separate server, I think with amcat 3.3.2.

To test: query on the above string in https://amcat.nl/navigator/projects/1/query/?articlesets=23060. It finds zero results, but does list the article in that set.

On the current devevelopment version, it finds no results at all even if a text containing that word is present.

I would guess that this has something to do with language analysis (ie like the umlaut removal), but it's hard to be sure. 

![terror](https://cloud.githubusercontent.com/assets/1736240/9661095/6e4feb78-5259-11e5-9ea4-27876d6e28da.png)

**Comment by vanatteveldt** [comment]
cc @Stolpovskaya , Does Christian have a github account as well?

**Comment by Stolpovskaya** [comment]
Quote Christian : "Yes... I believe under jamcat. Forgot. :)"

**Comment by christianbaden** [comment]
hi folks,
the anomaly is bigger than that. also in the query box, the distance operators ("text1 text2"~5) returns an error for arabic characters. any idea what it might be?

**Comment by martijnbastiaan** [comment]
`ES.count()` generates the wrong query for elasticsearch. It generates:

```json
{
  "query": {
    "constant_score": {
      "filter": {
        "bool": {
          "must": [
            {
              "terms": {
                "sets": [
                  28
                ]
              }
            },
            {
              "term": {
                "_all": "إرهابي"
              }
            }
          ]
        }
      }
    }
  }
}
```

instead of:

```json
{
  "query": {
    "constant_score": {
      "filter": {
        "bool": {
          "must": [
            {
              "terms": {
                "sets": [
                  28
                ]
              }
            },
            {
              "match": {
                "_all": "إرهابي"
              }
            }
          ]
        }
      }
    }
  }
}
```

(See `match` vs `term`.) I believe `match` is the correct option here, as it treats the input intelligently depending on the field's properties. The following patch therefore solves the problem:

```diff
diff --git a/amcat/tools/amcates.py b/amcat/tools/amcates.py
index ae3e17f..4cac3aa 100644
--- a/amcat/tools/amcates.py
+++ b/amcat/tools/amcates.py
@@ -652,7 +652,7 @@ class _ES(object):
         """
         Compute the number of items matching the given query / filter
         """
-        filters = dict(build_body(query, filters, query_as_filter=True))
+        filters = dict(build_body(query, filters, query_as_filter=False))
         body = {"query": {"constant_score": filters}}
         result = self.es.count(index=self.index, doc_type=settings.ES_ARTICLE_DOCTYPE, body=body)
         return result["count"]
```

@vanatteveldt agreed?

**Comment by vanatteveldt** [comment]
(closing due to inaction)
