### ISSUE TITLE
export aggregation

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#387]
Geweldig dat je vanuit het interactieve queryscherm met "export aggregation" nu ook een spss-bestand kunt wegschrijven; dat scheelt werk. 
Zou het zo kunnen zijn dat echter een oud probleem niet verholpen is? Amcat neemt de tijd om een tabel te maken, maar bij export aggregation lijkt dat dunnetjes overgedaan te worden. Het bij elkaar sprokkelen van de gegevens lijkt dan zelfs langer te duren, af en toe loopt het pas bij export aggregation fout (je ziet dan bij herhaling staan dat amcat nog (weer) bezig is een en dezelfde zoekstring af te handelen.

**Comment by vanatteveldt** [comment]
Op preview.amcat.nl kan je de nieuwe versie (3.4) vinden. Het queryscherm is behoorlijk overhoop gehaald, dus kijk even of het daar uberhaubt nog kan, en of het probleem zich daar ook nog voordoet. Reopen dit issue gerust als er dingen zijn die daar niet goed werken.

We willen met een paar weken amcat.nl overzetten op de nieuwe versie (tenzij er nog grote problemen gevonden worden met 3.4), dus in principe werken we niet meer aan de "oude" amcat.nl versie.
