### ISSUE TITLE
AJAX error, using Annotator not possible

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#389]
Opening the annotator brings up this error:
![ajax error 2809](https://cloud.githubusercontent.com/assets/6417728/10130419/d393df3a-65c8-11e5-824d-42b36144e97d.png)

When I ignore it codings do not load (even if I wait several minutes):
![codings loading](https://cloud.githubusercontent.com/assets/6417728/10130423/dfb8ab9c-65c8-11e5-878b-6ee3288083db.png)

In the Navigator, the codebook editor also doesn't load codebooks:
![codebooks loading](https://cloud.githubusercontent.com/assets/6417728/10130435/fbf47a8e-65c8-11e5-81ac-9c877d317a9b.png)

**Comment by vanatteveldt** [comment]
shit, dat is mijn fout. In de update van preview heb ik een kolom weggegooid waarvan ik dacht dat ze niet meer werd gebruikt. Ik moet nu naar een meeting, maar ik zal het om 13:00 fiksen

**Comment by vanatteveldt** [comment]
Mogelijk is het nu opgelost, kan jij testen en desnoods heropenen?
