### ISSUE TITLE
uploader and query do not work

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#390]
I tried to upload a html document, but amcat says 'pending' and does not finish uploading
![uploader pending](https://cloud.githubusercontent.com/assets/6417728/10158922/4337488c-6695-11e5-8a70-fcea6cc30e0e.png)

Same problem for query, the query never finishes loading:
![query pending](https://cloud.githubusercontent.com/assets/6417728/10158954/7181a2d2-6695-11e5-9741-b0e4eb05308d.png)

But there's no error message either

**Comment by vanatteveldt** [comment]
Celery/elastic search were not responding, it seems to be working again now
