### ISSUE TITLE
Query screen: uninformative error

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#391]
Zou het mogelijk zijn het juiste regelnummer te vermelden in het query scherm.
("line 1" in foutmelding hieronder klopt gewoon niet)

Cannot parse query: ParseException: Expected end of text (at char 158), (line:1, col:159)
Task: c11c0b4a-f4ab-4652-84e7-ca1010f565d4, status FAILURE.

**Comment by vanatteveldt** [comment]
This actually got worse, now it just says "failed"

E.g:
Go to http://preview.amcat.nl/navigator/projects/2/query/?sets=24448#summary, type in an illegal query such as  (bla, and press query:

What happens:
![image](https://cloud.githubusercontent.com/assets/1736240/12732379/8cebbd66-c935-11e5-99ca-5cb4d2ddfecb.png)

What should happen:
The query error should be displayed in red in the result pane, e.g. in this case 
QueryParseError: [u'ParseException: Expected ")" (at char 6), (line:1, col:7)'

**Comment by vanatteveldt** [comment]
![image](https://cloud.githubusercontent.com/assets/1736240/12874963/be75d610-cddf-11e5-8ed0-69823d11920e.png)
