### ISSUE TITLE
BZK PDF Scraper failure

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#392]
When I try to upload my Knipselkrant with the BZK PDF scraper it says failure:
![bzk scraper failure](https://cloud.githubusercontent.com/assets/6417728/10275634/40ca78fe-6b49-11e5-8dad-a083dcd576d6.png)

The BZK scraper on amcat.nl however does work (I tried with the same document)
![bzk scraper success](https://cloud.githubusercontent.com/assets/6417728/10275648/5085e396-6b49-11e5-896c-1a6c78ae8527.png)

**Comment by carinajacobi** [comment]
Sorry this was my mistake. I should have used the HTML scraper. Still doesn't work though;) but this one seems to at least make some progress before it fails:


![html scrapter](https://cloud.githubusercontent.com/assets/6417728/10302781/445881e8-6c0f-11e5-8615-d8f1a2c501da.png)

**Comment by carinajacobi** [comment]
I'm still having issues with the html uploader in preview.. It didn't want to upload this document
![html uploader](https://cloud.githubusercontent.com/assets/6417728/10536514/fb52b6be-73eb-11e5-8aaa-e73c02a8603c.png)

Even though amcat.nl uploaded it just fine
![html uploader amcat nl](https://cloud.githubusercontent.com/assets/6417728/10536517/04bbe3a6-73ec-11e5-8aac-93a9051b7210.png)

**Comment by CJStuart** [comment]
I believe i actually did fix it this time around, but i'm not 100% sure, as I couldn't reproduce the error.

**Comment by vanatteveldt** [comment]
(please reopen if it is not fixed)
