### ISSUE TITLE
Download CSV file for Aggregations or Associations doesn't produce a CSV

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#400]
When I try to download Associations tables (Query output options: Network, and then Association in the dropdown menu), I get a different file type instead that my computer cannot open:
![mysterious csv](https://cloud.githubusercontent.com/assets/6417728/10366352/1a504d92-6dca-11e5-9348-24fa0e1e624e.png)

Trying to download Aggregation tables produces the same mysterious file type, however Article List produces a csv just fine.

**Comment by vanatteveldt** [comment]
The csv / xlsx serializer doesn't seem to work with the new (json) table structure (and I'm not even sure that that serializer gets called, as aggregation -> csv redirects to http://preview.amcat.nl/api/v4/taskresult/3150c996-37ca-4756-a617-b4ae313387f8?format=json)

**Comment by carinajacobi** [comment]
Confirmed that AmCAT now produces csvs for Aggregations. 

However, Associations (in the Network dropdown menu)
![csvnetwork](https://cloud.githubusercontent.com/assets/6417728/10846675/bcdbbad0-7f11-11e5-99f7-708f4611a418.png)

still produces the problematic file type instead of a csv
![csvnetwork2](https://cloud.githubusercontent.com/assets/6417728/10846683/cad43a68-7f11-11e5-9e3c-46f5f8e6df68.png)
