### ISSUE TITLE
Build instructions in README deprecated/build.py

### ISSUE THREAD

**Issue by dorvak** [amcat/amcat#406]
I tried to build AmCat on CentOS, however the line in the README

    python static/components/highlight/tools/build.py

Does not work, there is only a build.js file. Im not really into that node.js stuff, any hint how to solve this?

Best,

Till (the guy from Munich developing the Facepager)

**Comment by vanatteveldt** [comment]
Hey Till,

Thanks for noticing this!

@martijnbastiaan do you know whether building the highlighter is still needed?

-- Wouter

**Comment by martijnbastiaan** [comment]
Ah, the highlighter team changed the build procedure :(. I'll update the README. In the meantime, after running `bower install`:

```bash
cd static/components/highlightjs
sudo npm install
node tools/build.js :common
cd -
```

You might want to replace `node` with `nodejs`, depending on your distribution.
