### ISSUE TITLE
Article splitting issues

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#411]
1) I tried to split an article, remove the original from the articleset, and add the splitted article to that same set
![splitting1](https://cloud.githubusercontent.com/assets/6417728/10572284/381c698e-7647-11e5-85b4-4dc76866b9b2.png)

However, nothing seemed to happen
![splitting2](https://cloud.githubusercontent.com/assets/6417728/10572294/547503ca-7647-11e5-9e47-736c71e14f0e.png)

When I went back to the articleset overview, it also still showed the original article, not the splitted one. Refreshing the index did not help
![splitting3](https://cloud.githubusercontent.com/assets/6417728/10572304/78bc4af4-7647-11e5-84fb-143f1ce07661.png)

Assigning the splitted article to a new set instead of the old one gives the same result: no splitting (and no new set is created).

2) What does the 'add to set' on top of the page mean? (It doesn't seem to do anything when I select an articleset here or name a new set)

**Comment by vanatteveldt** [comment]
@CJStuart  can you take a look?
