### ISSUE TITLE
Use docker for distributing amcat?

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#412]
From #407: 
@dorvak: "BTW: Might docker be an option for you to ship the app?"
@vanatteveldt: "Docker might be a good idea. We considered shipping VM's earlier but thought it was overkill, maybe docker is the right tool. Do you have experience with it?"
@dorvak: "Haven't worked with docker yet, but i think it's quite lightweight for a VM (and should run fairly efficient). Plus: users might run Amcat on Heroku (etc.)"

@CJStuart @martijnbastiaan  what do you think? Would it make internal version management and problems with less technical contributors easier?

**Comment by martijnbastiaan** [comment]
We could definitely support Docker as a way of distribution AmCAT. Especially if this makes it easier to use AmCAT on a VPS, which seems like a good way to promote usage. I'm not too keen on using Docker as our main way to distribute AmCAT, as it strikes me as a lazy way out of properly doing version management.

On this topic: maybe we could revive the idea of Debian packages? It seems to me that amcat is stable enough to be build against the packages in 16.04. From thereon we could ''officially'' support Ubuntu LTS + Ubuntu latest? This should make it easier to manage amcat on our own servers as well..

**Comment by martijnbastiaan** [comment]
Related: https://github.com/amcat/amcat/issues/568

**Comment by vanatteveldt** [comment]
There is a docker image now. Not sure if it works 100%, but let's close this issue :)
