### ISSUE TITLE
Error in uploading texts to AmCat

### ISSUE THREAD

**Issue by WRoose** [amcat/amcat#413]
This piece of code worked perfectly some months ago, now it gives an error message.

    #connecting to amcat and uploading everything
    conn = amcat.connect("http://preview.amcat.vu.nl")
    amcat.save.password("http://preview.amcat.vu.nl", "wroose", "PASWOORD")

    #upload articles
    amcat.upload.articles(conn = conn, project = 889, articleset = 23278 , text=iconv(dataset$text, to =  "utf-8"), headline=iconv(dataset$title, to = "utf-8"), date=dataset$date, medium="Frieze")

Error message received:

    Uploading 100 articles to set 23278
    Error: Input to str_c should be atomic vectors

**Comment by vanatteveldt** [comment]
Was this resolved? Please reopen if not.
