### ISSUE TITLE
Filtering on medium does not work in query -> graph

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#415]
I tried making a graph per medium over time for a limited set of media, but I get errors on trying to select media:

http://preview.amcat.nl/navigator/projects/521/query/?sets=17112&jobs=#aggregation
![image](https://cloud.githubusercontent.com/assets/1736240/10819772/15b613a8-7e4a-11e5-8b89-085cbc38257d.png)

It gives a 400 BAD REQUEST on the POST to 
http://preview.amcat.nl/api/v4/query/statistics?format=json&project=521&sets=17112&jobs=

response: {"mediums":["Select a valid choice. 5 is not one of the available choices."]}

**Comment by CJStuart** [comment]
Wrong issue

**Comment by vanatteveldt** [comment]
cannot reproduce
