### ISSUE TITLE
HTML uploader doesn't work after editing HTML document in Word

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#423]
I tried to upload a problematic document that contained one article without headline
![uploadfailure1](https://cloud.githubusercontent.com/assets/6417728/10933883/22ba5780-82dc-11e5-9aba-82e0b8538c44.png)

In such cases, I open the HTML in Word and remove the problematic article. After that, I can upload the document without problems in AmCAT
![uploadfailure3](https://cloud.githubusercontent.com/assets/6417728/10933905/4f01ffc8-82dc-11e5-9b35-f2b7d9bf25ad.png)

However, preview.amcat.nl doesn't let me do this (same document)
![uploadfailure2](https://cloud.githubusercontent.com/assets/6417728/10933914/5d23465c-82dc-11e5-8d1b-24c33f92e406.png)

**Comment by CJStuart** [comment]
Do you have an example of the edited and unedited files? I believe i fixed it now, but i don't have anything to test it with.
