### ISSUE TITLE
HTML scraper in preview mixes up document order

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#424]
The HTML scraper in amcat.nl creates an articleset in which individual newspaper articles appear in the inverse order compared to the HTML document which they came from. This was good. However, the HTML scraper in preview.amcat.nl puts the individual articles in a seemingly random order compared to the original HTML. This is annoying, since I have to code them in order. Could this be changed back? (please email me if it is not clear what I mean, I can send one of the HTML documents + screenshots)

**Comment by vanatteveldt** [comment]
Is this a 'feature' of the uploader, or of the annotator or assign to codingjob task? I.e., does this only occur with html uploaded articles?

**Comment by vanatteveldt** [comment]
It should be fixed now, can you test and reopen if necessary?
