### ISSUE TITLE
average of sentence coding does not work when aggregating by article coding

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#429]
For example analysis 2 we need to show count+average per onderwerp, but the average mening does not work when using onderwerp as aggregation

![screenshot from 2015-11-15 20 17 01](https://cloud.githubusercontent.com/assets/6438205/11170470/d8df06bc-8bd5-11e5-841d-dcea05cc2c01.png)
![screenshot from 2015-11-15 20 16 25](https://cloud.githubusercontent.com/assets/6438205/11170471/d8fe260a-8bd5-11e5-8f5e-3aba5d0ba82d.png)

**Comment by martijnbastiaan** [comment]
The query showed above now, hopefully, work as expected on http://dev.amcat.nl. Could you test it?

![screenshot from 2016-01-14 08-57-15](https://cloud.githubusercontent.com/assets/5658854/12318736/e44e4f4e-ba9c-11e5-8a1e-65f887cf4e63.png)

**Comment by nruigrok** [comment]
Just dit but it doesn't work yet at my computer:
![image](https://cloud.githubusercontent.com/assets/6438205/12319185/b8262aa0-baa0-11e5-804a-58a6031a377f.png)

**Comment by martijnbastiaan** [comment]
Did you use the same query? I used  your saved one which you used in the images above:

http://dev.amcat.nl/navigator/projects/29/query/?query=22&jobs=10344,10348,10349,10351,10352,10353,10354,10355,10356,10357,10358#codingaggregation

If that fails too, please try to press F5 / CTRL + F5 to clear your caches!
