### ISSUE TITLE
Uploaded articles no longer in articleset

### ISSUE THREAD

**Issue by decenergy** [amcat/amcat#437]
Uploaded around 3 weeks ago 818 articles and 767 articles in two different articlesets in Amcat. All articles were uploaded successfully and were available. However, when I login now only 288 and 166 articles seem to be still there. 

![print screen amcat](https://cloud.githubusercontent.com/assets/15636964/12113169/52365f68-b3a1-11e5-826a-effa20266f09.png)

**Comment by nruigrok** [comment]
I had the same problem, something went wrong with indexing. However if you click on the articleset and click on Refresh Index, all articles will be back again :-).

**Comment by decenergy** [comment]
Thanks!
