### ISSUE TITLE
Articleset uploader

### ISSUE THREAD

**Issue by CJStuart** [amcat/amcat#439]
Currently the upload view has some problems:
- cryptic errors (e.g. `AttributeError: 'NoneType' object has no attribute 'split'`, `IndexError: list index out of range`, etc.)
- The entire upload is refused when 1 article has issues, for example when an article has no headline.

**Comment by vanatteveldt** [comment]
I think this should be a "wizard", ie first load the file, then add options for what to do with it (e.g. allowing you to assign csv columns to fields, possibly recognizing metadata in text files, smarter handling of zip files, etc)

**Comment by vanatteveldt** [comment]
@CJStuart  any progress?
