### ISSUE TITLE
internal server error on querying a lot of sets

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#441]
If I try to query all 757 sets in project 29, I get an internal server error

Reproduce:
1)  go to http://preview.amcat.nl/navigator/projects/29/articlesets/
2) Set 1000 records per page
3) Select all, use in query
4) run query

(shorter: go [here](http://preview.amcat.nl/navigator/projects/29/query/?sets=24272,24270,24263,24259,24251,24247,24241,24224,24216,24213,24166,24164,24161,24153,24122,24082,24073,24070,24015,23973,23970,23963,23914,23913,23901,23891,23884,23883,23882,23875,23866,23834,23783,23762,23697,23686,23625,23616,23614,23605,23602,23591,23561,23555,23547,23544,23538,23535,23534,23532,23525,23521,23520,23511,23509,23492,23484,23475,23452,23438,23426,23418,23416,23405,23344,23340,23298,23291,23284,23273,23271,23267,23261,23253,23249,23248,23237,23232,23229,23227,23224,23217,23207,23198,23184,23172,23168,23162,23157,23147,23140,23135,23120,23118,23114,23112,23099,23097,23094,23092,23090,23088,23084,23081,23077,23066,23062,23058,23048,23039,23030,23026,23023,23013,23011,23004,22992,22988,22982,22976,22967,22964,22962,22954,22950,22945,22943,22941,22937,22929,22919,22915,22908,22906,22901,22892,22871,22869,22801,22799,22796,22794,22792,22790,22783,22779,22777,22771,22761,22749,22746,22743,22733,22730,22728,22047,22005,22001,21976,21962,21947,21926,21923,21919,21887,21865,21850,21830,21828,21815,21806,21794,21768,21735,21734,21699,21643,21626,21588,21524,21519,21496,21475,21454,21446,21414,21409,21360,19479,19465,19461,18792,18776,18760,18702,18670,18659,18603,18575,18571,18545,18460,18448,18445,18394,18368,18321,18236,18225,18178,18158,18120,18113,18107,18094,18075,18073,18056,18048,18001,17974,17967,17959,17896,17886,17884,17877,17875,17873,17868,17861,17837,17825,17818,17807,17805,17774,17761,17759,17722,17703,17692,17676,17670,17652,17649,17643,17641,17638,17636,17628,17623,17614,17613,17611,17607,17604,17597,17588,17568,17528,17523,17509,17488,17486,17473,17467,17463,17458,17456,17454,17451,17446,17412,17408,17404,17401,17398,17385,17384,17375,17314,17287,17280,17277,17263,17261,17259,17257,17228,17225,17222,17208,17203,17028,17007,16985,16984,16982,16937,16936,16928,16880,16869,16853,16849,16846,16845,16840,16819,16818,16761,16737,16664,16661,16658,16638,16629,16603,16600,16588,16586,16540,16537,16535,16533,16524,16104,16024,15944,15939,15881,15865,15863,15839,15831,15818,15787,15776,15766,15747,15721,15702,15687,15666,15665,15664,15657,15643,15641,15623,15614,15463,15456,15422,15383,15381,14993,14924,14922,14774,14730,14569,14305,14302,14290,14287,14052,14006,13744,13630,13592,13443,13427,13358,13322,13279,13163,13159,13155,13124,13122,13067,13003,12896,12851,12842,12820,12793,12764,12734,12726,12620,12615,12613,12584,12582,12581,12577,12576,12574,12559,12539,12532,12521,12519,12488,12485,12455,12451,12404,12389,12319,12318,12279,12262,12234,12226,12222,12220,12181,12155,12135,12121,12103,12092,12034,12017,12014,11988,11978,11965,11964,11959,11958,11932,11905,11869,11862,11861,11859,11858,11837,11735,11710,11698,11696,11693,11670,11645,11644,11546,11488,11413,11388,11387,11310,11196,11051,11011,10938,10879,10828,10781,10752,10746,10499,10461,10401,10389,10381,10360,10322,10303,10301,10300,10299,10285,10269,10267,10258,10256,10245,10234,10189,10184,10170,10151,10069,10055,10053,10032,10019,9993,9958,9934,9932,9914,9911,9898,9847,9845,9818,9810,9782,9769,9753,9734,9726,9645,9641,9634,9621,9579,9555,9535,9516,9495,9481,9472,9458,8927,8920,8847,8833,8831,8808,8806,8721,8697,8652,8614,8605,8596,8594,8576,8573,8553,8547,8546,8496,8455,8427,8402,8394,8393,8317,8316,8310,8309,8220,8219,8195,8194,8184,8183,8151,8150,8143,8142,8141,8137,8136,8135,8134,8127,8126,8117,8116,7967,7966,7965,7964,7907,7906,7905,7904,7903,7902,6892,6891,6849,6844,6833,6832,6831,6830,6807,6806,6796,6795,6794,6793,6792,6791,6790,6584,6583,6582,6510,6509,6508,6505,6504,6503,6453,6442,6441,6440,6379,6378,6377,6376,6375,6374,6271,6270,6269,6268,6267,6264,6217,6216,6211,6206,6205,6204,6203,6202,6201,6200,6199,6198,6197,6196,6195,6194,6193,6192,6177,6137,6136,6033,6031,6030,6010,6009,6008,5961,5960,5957,5947,5946,5945,5917,5916,5915,5908,5907,5906,5900,5899,5898,5897,5888,5887,5886,5885,5884,5883,5882,5870,5869,5868,5866,5865,5864,5863,5860,5859,5858,5853,5852,5851,5849,5848,5847,5846,5817,5816,5815,5808,5807,5806,5797,5796,5795,5759,5758,5757,5746,5745,5744,5724,5723,5722,5721,5696,5695,5694,5693,5691,5690,5689,5688,5641,5640,5639,5638,5637,5636,5626,5625,5624,5595,5594,5589,5588,5587,5586,5585,5584,5583,5571,5570,5569,5568,5567,5566,5565,5556,5555,5554,5547,5546,5545,5544,5540,5539,5538,5537,5536,5534,5531,5530,5529,5519,5518,5517,5516,5515,5514,5513,5506,5505,5504,5498,5497,5496,5449,5448,5447,5446,5445,5444,5434,5432,5431,5430,5415,5414,5413,5412,5411,5410,5356,5355,5354,5353,5352,5351,5324,5323,5322,5321,5320,5319,5318,5317,5316,5314,5313,5312,5311,5310,5307,5306,5305,5304,5224,5222,5221,5220,5219,5208,5207,5206,5196,5195,5194,5193,5190,5189,5188,5179,5178,5177,5176,5119,5118,5117,5113,5110,5108,5091,5090,5089,5088,5087,5085,5072,5071,5070,5042,5041,5040,5039,5038,5037,5036,5035,4958,4957,4950,4949,4948,4947,4946,4945,4900,4899,4898,4897,4884,4883,4882,4881,4880,4879,4845,4844,4835,4834,4833,4825,4824,4823,4822,4821,4820,4819,4815,4814,4790,4789,4788,4783,4782,4781,4780,4779,4746,4745,4744,4743,4742,4709,4708,4707,4634,4633,4632,4627,4609,4600,4599,4598,4597,4596,4595,4591,4590,4589,4583,4582,4581,4527,4526,4495,4494,4493,4492,4481,4480,4479,4478,4476,4475,4474,4473,4463,4206,4173,4154,4151,4144,4090,4074,4068,4062,4008,3987,3958,3951,3904,3895,3888,3882,3857,3841,3813,3805,3800,3785,3773,3764,3760,3739,3480,3475,3469,3464,3460,3444,3438,3425,3375,3336,3330,3328,3327,3324,3297,3209,3128,3114,3078,3053,3039,3033,3014,2955,2927,2910,2904,2862,2856,2855,2852,2851,2846,2842,2835,2716,2586,2569,2568,2540,2525,2520#summary) and press control-q)

This is quite possibly a GET query length problem in an ajax call?

**Comment by CJStuart** [comment]
Related to #283, adding large numbers of article ID's to GET queries does not seem to be a good idea, as these are usually limited to a couple of thousands of characters
