### ISSUE TITLE
scatter plot hover "x" value is integer timestamp  rather than date

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#446]
If you make a scatter plot with date as an axis, hovering over a point gives the timestap / ms since epoch rather than a human readable date.

**Comment by vanatteveldt** [comment]
![image](https://cloud.githubusercontent.com/assets/1736240/12373331/321b84a0-bc76-11e5-939b-1bd61936071d.png)

(also, if the x: and y:  can be replaced by the axis labels that would be great, e.g. date: ... # articles: ...)

**Comment by CJStuart** [comment]
closed in amcat/amcat-query-js@f1fdf99
