### ISSUE TITLE
graphs/tables missing zeroes

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#455]
Currently, graphs (including the pretty new summary graph) assume that missing time points (i.e. weeks with no hits) are "missing" and are skipped, leading from a line going from e.g. week 1 to week 3. Instead, week 2 should be zero in that case, as there were no articles.

(ideally, a table per week should also have a zero there)

![image](https://cloud.githubusercontent.com/assets/1736240/12717069/917d0de4-c8e5-11e5-9eb4-336072181865.png)

**Comment by vanatteveldt** [comment]
(also, maybe the "line graph" should be replaced with a time series graph as per the new summary, or at least if there is only one line?)

**Comment by CJStuart** [comment]
Reopening this for now, it is implemented in 3.4, but couldn't be merged completely into master.
