### ISSUE TITLE
error on line graph in preview: Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#458]
Preview throws a js error when displaying aggregate results. The taskresult is retrieved correctly, but then it throws a js error 'cannot read property length of undefined'.

To reproduce: go to http://preview.amcat.nl/navigator/projects/2/query/?sets=18676#aggregation, click [query]

My first guess is that this is because amcat-query-js is not the right version, should we add a tag or branch there? (but maybe my guess is wrong :))

renderers.js?cache=default_token:448 Uncaught TypeError: Cannot read property 'length' of undefined
$.extend.text/json+aggregation+table @ renderers.js?cache=default_token:448(anonymous function) @ query.js?cache=default_token:915_result_done @ poll.js?cache=default_token:161fire @ jquery.js?cache=default_token:3099self.fireWith @ jquery.js?cache=default_token:3211done @ jquery.js?cache=default_token:8264(anonymous function) @ jquery.js?cache=default_token:8605

**Comment by vanatteveldt** [comment]
(cc @martijnbastiaan )

**Comment by CJStuart** [comment]
Related to amcat/amcat-query-js#2

**Comment by vanatteveldt** [comment]
Yeah, I was afraid that might be the case. Is there a "quick fix", e.g. specifying a specific commit hash in bower.json?

**Comment by CJStuart** [comment]
I made a release-3.4 branch in amcat/amcat-query-js, and added a bower semver version to it, also bower.json was changed accordingly
