### ISSUE TITLE
setup.py doesn't work

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#461]
We currently have a setup.py, but it references old amcat folders, might not have all new folders and the github requirement in it doesn't seem to work. 

A wise man once told me:
```
We should either support a feature, or not support it
```

So, we should either fix setup.py (also allowing for pip install from github and using pip install -e) or get rid of it.

**Comment by vanatteveldt** [comment]
(If we revamp setup.py, we should probably drop/combine/flatten a lot of our packages to make it managable?)

**Comment by martijnbastiaan** [comment]
Fixed in https://github.com/amcat/amcat/commit/7a4f4d4c118213078ba414668d86b547d1469a8e and https://github.com/amcat/amcat/commit/383faff95aa2c74e268c2857e1ac782b8e3adf05.
