### ISSUE TITLE
Deleting articlesets without proper user rights

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#464]
I am able to delete articlesets in projects where I only have read/write rights or less
![users](https://cloud.githubusercontent.com/assets/6417728/12982377/c6d0452c-d0e4-11e5-859f-ab2f0af5e564.png)

(the guest role of this project is Reader)

![delete articleset](https://cloud.githubusercontent.com/assets/6417728/12982384/cd0dffd8-d0e4-11e5-83cb-0d48622f2a9e.png)

![articleset deleted](https://cloud.githubusercontent.com/assets/6417728/12982393/d64a5786-d0e4-11e5-9a1f-a3fb7a6cb195.png)

Only admins should be able to do so, right?

**Comment by CJStuart** [comment]
Currently you need write rights to create or delete an articleset. Changing delete rights to admin only would have the implication that each time someone makes a mistake and wants to remove or reupload an articleset, an admin will have to remove the set. I'm not sure if this is a good idea.

@vanatteveldt what do you think?

**Comment by vanatteveldt** [comment]
I agree, read/write access should grant complete control over a project except for changing user roles. 

ASAIK, coders don't need write access, as you automatically have write access to a coding job assigned to you (?)
