### ISSUE TITLE
Text bubble in graphs only shows day even when interval is larger

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#466]
Minor issue. In line graphs (Query section, graph/table output option), the text bubble that pops up when you hover over data points shows one specific day and time, for example Friday Dec 31st, 23:00 below, even though the graph shows results by year
![linegraphtextbox](https://cloud.githubusercontent.com/assets/6417728/13007882/53455eee-d193-11e5-899a-246853cbb028.png)

It would be more informative to have the text bubble change based on the interval selected for the graph, e.g. the year instead of the day (in the above example, every data point is December 31st 23:00, only the day of the week changes) - or when month is the interval selected, the month, etc.

**Comment by CJStuart** [comment]
Fixed in 7ab62b5
