### ISSUE TITLE
clicking in graph gives first set/medium regardless of which point is clicked

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#468]
e.g. go to: http://preview.amcat.nl/navigator/projects/915/query/?sets=23513,23450#aggregation and make a graph per set per month. Hovering over a point lists the y value of both sets (which is not a problem per se), and clicking gives the article list for the first set rather than the point clicked.

![image](https://cloud.githubusercontent.com/assets/1736240/13036159/35bbbec6-d360-11e5-92b0-4bf9c0e9f116.png)

Clicking should yield 38k articles, but instead gives the 305 articles of the other set. 

![image](https://cloud.githubusercontent.com/assets/1736240/13036167/5a5d3da4-d360-11e5-907e-56c12a940ff1.png)

**Comment by CJStuart** [comment]
This is a known bug in the highcharts version (4.1.10) we're running. highcharts/highcharts#3919. I suppose it's best to downgrade to 4.1.9 in 3.4, and upgrade to ~4.2.3 in the master branch, as there might have been some breaking changes in 4.2.

**Comment by vanatteveldt** [comment]
Sounds like a good plan!
