### ISSUE TITLE
Presentation in Amcat 3.4 articles is not logic

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#469]
When clicking on results, for example all data from FD and want to see all articles there is a non logic order. for example byline first where i would expect headline. also medium etc earlier would be nice.
![screenshot from 2016-02-15 10-40-37](https://cloud.githubusercontent.com/assets/6438205/13044817/949be5fe-d3d0-11e5-8fe8-cda2d40482fe.png)

**Comment by nruigrok** [comment]
We willen graag eerst mediumid dan headline, page, datum etc

**Comment by vanatteveldt** [comment]
also, it would be nicer if the list were a bit shorter, probably default 10 or 20 should be enough since there is an option to see more anyway?
