### ISSUE TITLE
Clustermap and association is not working

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#470]
Clustermap in 3.4 and association is not functioning
![screenshot from 2016-02-15 11-16-04](https://cloud.githubusercontent.com/assets/6438205/13045774/937807e8-d3d5-11e5-8018-a64ee9a9b202.png)

**Comment by nruigrok** [comment]
Het is vooral een probleem bij de associatie en dan het netwerk. De clustermap werkt wel, maar niet altijd en bij meer dan 6 termen lijkt hij op tilt te slaan.

**Comment by nruigrok** [comment]
Associations werken wel in een tabel.

**Comment by CJStuart** [comment]
Als het goed is zijn deze problemen al eerder verholpen (zie #465). Voor de problemen met grote queries heb ik een nieuwe issue (#471) aangemaakt.

**Comment by CJStuart** [comment]
Overigens moeten bij oudere installaties om dit te verhelpen Java en Graphviz geïnstalleerd worden. Deze stonden eerder niet vermeld in de requirements.
