### ISSUE TITLE
simplify amcat package/folder structure

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#473]
We (me and @martijnbastiaan) decided to simplify the package/folder structure by merging and/or removing a number of pakcages.

To be merged/moved:
- amcat.models.coding -> amcat.models
- amcat.scripts.forms -> amcat.forms
- amcat.scripts.query.templates.\* -> amcat.templates
- amcat.tools.aggregate_es -> amcat.tools.aggregate
- amcat.tools.aggregate_orm -> amcat.tools.aggregate

To be removed:
- amcat.contrib.plugins
- ~~amcat.scripts.output~~
- ~~amcat.tools.sql~~

See also: https://docs.google.com/spreadsheets/d/1u8NqausBLUrY7eYF6KYrr-aUxlZ5sH77sRIF9OnflfM/edit?usp=sharing

**Comment by martijnbastiaan** [comment]
Removed amcat.tools.sql: https://github.com/amcat/amcat/commit/868bb0bd8a402e3d56ddc303e201eaf00b9647fa
Removed amcat.scripts.output: https://github.com/amcat/amcat/commit/1006314e572bcb95eecc1a10dd4a568d63846ede

**Comment by vanatteveldt** [comment]
(closing due to inaction)
