### ISSUE TITLE
Clustermap table and exports don't work

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#474]
The table output option for clustermaps keeps waiting for results, and doesn't finish
![table](https://cloud.githubusercontent.com/assets/6417728/13245701/3ec7cc20-da0f-11e5-81a6-73a4fc743c39.png)

Exporting the table as an SPSS file also doesn't work
![spss](https://cloud.githubusercontent.com/assets/6417728/13245723/5b13488c-da0f-11e5-82e3-39891ee821b9.png)

And exporting it as either of the three CSV options produces something, but not a CSV
![csv](https://cloud.githubusercontent.com/assets/6417728/13245733/6d0540d6-da0f-11e5-9531-e3cbad31a0d2.png)

I used a large articleset, but the clustermap diagram works perfectly, so I thought something might be wrong with the table option.

**Comment by CJStuart** [comment]
The table problem probably has been fixed in 50ecad0

**Comment by martijnbastiaan** [comment]
These issues have been fixed in https://github.com/amcat/amcat/commit/0c6837df36c5c77e764f1ff7107f1b366dcc5891 and https://github.com/amcat/amcat/commit/37cd29eae1146e88984fc53bb25fa0334fbd2c77. It's unlikely that they will be backported to 3.4 unfortunately, so we'll have to wait on the release of amcat 3.5..

**Comment by vanatteveldt** [comment]
Well, it shouldn't give an error / hang in 3.4. So if it is difficult to get it working, we should disable the button? 

Is this feature essential to anyone?

**Comment by vanatteveldt** [comment]
@CJStuart  dat ie csv's niet de csv extentie geeft is makkelijk te fixen
me: nou, laten we dat dan doen, en desnoods de spss/excel gewoon disablen hier?

**Comment by CJStuart** [comment]
Fixed csv download issues in af51942

**Comment by vanatteveldt** [comment]
(so is this fixed now? if not, please reopen)
