### ISSUE TITLE
Association-Interval cross tables aren't ordered chronologically

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#477]
For Associations with a time interval, From-to tables and network graphs are ordered chronologically, but cross tables are not
![tableorder](https://cloud.githubusercontent.com/assets/6417728/13364905/14b738ce-dcd2-11e5-9383-93b4ade0ac30.png)

Is this intentional?

**Comment by vanatteveldt** [comment]
No, at least I can't imagine why anybody would want to have it like this :)

**Comment by martijnbastiaan** [comment]
This fix has been backported to release-3.4 as well.
