### ISSUE TITLE
uploading articles to amcat

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#478]
the following message occured when uploading zip files see attached example
[nrc2000b.zip](https://github.com/amcat/amcat/files/149823/nrc2000b.zip)

------ Issue details -----
500 error on accessing:
https://amcat.nl/navigator/projects/2/articlesets/upload/2/

**Comment by martijnbastiaan** [comment]
Issue confirmed! Working on it.

**Comment by vanatteveldt** [comment]
I think it does work already on preview, but maybe it's a capacity / elastic problem?

**Comment by martijnbastiaan** [comment]
ah, I tried it in dev where it's utterly broken :[

Wouter van Atteveldt <notifications@github.com> schreef op 1 maart 2016 17:00:59 CET:
>I think it does work already on preview, but maybe it's a capacity /
>elastic problem? 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/amcat/amcat/issues/478#issuecomment-190784463

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
