### ISSUE TITLE
Query: polling task undefined failed (AmCAT 3.3), uploading articles doesn't work

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#479]
Query (any searchstring) in 3.3 causes the following error:
![polling task undefined](https://cloud.githubusercontent.com/assets/6417728/13389627/b746ed34-dec9-11e5-853d-bce919a3ca80.png)

And not sure if this is caused by the same thing, but the uploaders also don't work, for example this
![upl1](https://cloud.githubusercontent.com/assets/6417728/13389678/11123f80-deca-11e5-93a2-60ce37e427e9.png)

Leads to this error
![upl2](https://cloud.githubusercontent.com/assets/6417728/13389682/1f51b3c8-deca-11e5-84b5-daf4b6b49553.png)

**Comment by vanatteveldt** [comment]
Can you try again and re-open if it still doesn't work?

**Comment by markboukes** [comment]
Had the same problem in #480 , but solved now. Thanks!
