### ISSUE TITLE
No access to uploaded lexisnexis articles

### ISSUE THREAD

**Issue by joepschaper** [amcat/amcat#481]
Hi developers,

One of my students who's using AmCAT encounters a problem with opening some of the articles he uploaded. It concerns (for instance) article id 155402210 in project 521. It looks like AmCAT tries to retrieve the article from a project my student doesn't have access to. His username is a bit weird: first name: 'Porject', las name: '2', email address: sean5874@gmail.com.

Thanks for your help.

Joep

**Comment by vanatteveldt** [comment]
This should be fixed on preview.amcat.nl, can you try?

(there's even a loophole that gives anyone access to articles, but I'm trying to close that now :))

**Comment by joepschaper** [comment]
Yes, zo werkt het! Zet je het zo over naar de echte site of moeten mijn studenten op de preview site werken?
