### ISSUE TITLE
API: Adding articles to set using upload API no longer possible

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#482]
In 3.3, you could add articles to a set by POSTING the ids to .../articlesets/x/articles. This is no longer possible as .../articles only accepts single values, and article-upload requires complete articles.

This is pretty important for using the AmCAT API, so I'm going to mark it for 3.4

Simplest solution is probably to hack the /articles endpoint, but I really think the article-upload endpoint was a mistake, if only because it introduced backwards incompatibility  (as the articles end point no longer accepts lists) for no real good reason, so I'm tempted to try to merge the two end points again (and allow id/uuid lists), and roll back the client changes.

@martijnbastiaan: any comments?

**Comment by martijnbastiaan** [comment]
Do it :)
