### ISSUE TITLE
Uninformative error when creating codingjobs from not fully indexed set

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#483]
I tried to create a number of smaller codingjobs from an articleset and AmCAT showed this error
![codingj1](https://cloud.githubusercontent.com/assets/6417728/13421699/3ecbebb2-df90-11e5-9232-49ba56b77760.png)

(continued until)
![codingj2](https://cloud.githubusercontent.com/assets/6417728/13421708/4c1713a0-df90-11e5-9be5-480aadf183cb.png)

Back in the codingjobs overview, I noticed that a few jobs were created despite the error
![codingj3](https://cloud.githubusercontent.com/assets/6417728/13421723/63779dd0-df90-11e5-93f1-ecea79d6e982.png)

But there was also a new articleset containing the rest of the articles from the original set, which were not included in any of the codingjobs
![codingj4](https://cloud.githubusercontent.com/assets/6417728/13421740/80e2ab3a-df90-11e5-96de-e742f5e49c54.png)
Trying to create a new job from this set was not possible, and led to the same error as above.

I found out that refreshing the index for the original articleset solved this problem, but
a.) amcat.nl (version 3.3) could create the codingjobs without error even without re-indexing the original set, so it would be nice if 3.4 could do so too, or
b.) if creating codingjobs from not fully indexed sets is not possible, the error AmCAT shows could be more informative.

**Comment by vanatteveldt** [comment]
do you have an example article set that does not work (i.e. that you did not reindex yet)?

**Comment by vanatteveldt** [comment]
(closing due to inaction)
