### ISSUE TITLE
UnicodeEncodeError: on a mac

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#485]
when trying to log in some students have an error after they log in and click on their own name. they might have an older OS system. could that be the problem?
------ Issue details -----
500 error on accessing:
http://eur.amcat.nl/navigator/projects/80/articlesets/

**Comment by vanatteveldt** [comment]
do they have an accent in their name?

Can you post a screenshot of the unicode error?

**Comment by vanatteveldt** [comment]
fixed
