### ISSUE TITLE
kafnafparserpy does not support python3

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#488]
I introduced a dependency on nlpipe -> kafnafparserpy, which does not seem to work with python3. It would be good to try to modify the kafnafparser to be compatible with python2 and python3, and send it as a pull request.

**Comment by martijnbastiaan** [comment]
KafNafParserPy has been ported to Python 3 in our own repository: https://github.com/amcat/KafNafParserPy. A pull request has been submitted here; https://github.com/cltl/KafNafParserPy/pull/4.
