### ISSUE TITLE
'No headline found!' in amCAT

### ISSUE THREAD

**Issue by alytdamstra** [amcat/amcat#492]
When uploading LexisNexis articles (in text files), AmCAT does not seem to recognize the headlines of those articles of which the headline in the original format is called 'Kop:' (instead of 'HEADLINE:')
Find attached a screen capture of the message AmCAT gives and the associated text files.
Can someone help me out here? 

Thanks in advance!

Alyt Damstra
PhD Candidate Political Communication UvA

[De_Telegraaf 02:03a.TXT](https://github.com/amcat/amcat/files/199563/De_Telegraaf.02.03a.TXT)
![schermafbeelding 2016-03-31 om 14 53 56](https://cloud.githubusercontent.com/assets/11331595/14206442/6ff33af6-f813-11e5-8646-f7222483c807.png)

**Comment by martijnbastiaan** [comment]
Fixed!

- [X] Tested on amcat.nl
- [X] Released to master
