### ISSUE TITLE
SMTPSenderRefused: (530, '5.5.1 Authentication Required. Learn more at\n5.5.1  https://support.google.com/mail/answer/14257 e190sm12581625wma.15 - gsmtp', u'wat200@vu.nl')

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#493]
Something is wrong with the login page. See:

------ Issue details -----
500 error on accessing:
http://hill.amcat.nl/accounts/register/

**Comment by vanatteveldt** [comment]
Sorry, I missed this one, but the short answer is that registering doesn't work without an email setup.
