### ISSUE TITLE
better dropdowns for project selection in saving set and 'using set in another project'

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#496]
In query -> "save as new set" and articleset -> "use in another project" the user can select a project. This list can be too large for a simple dropdown, and I think it the list in "save as new set" is not properly filtered at the moment:

_save as set:_

![image](https://cloud.githubusercontent.com/assets/1736240/14381734/da9a95a0-fd88-11e5-8739-0c2a4de0f77f.png)

_use in another project:_

![image](https://cloud.githubusercontent.com/assets/1736240/14381754/07302472-fd89-11e5-91b6-c1e7d708f9e7.png)

The 'save as set' list should only show "favourite" projects that the use has write access in, and both lists should be the 'searchable dropdowns' that we also use in e.g. selecting a user in project -> users

**Comment by CJStuart** [comment]
Fixed in ffc6abb
