### ISSUE TITLE
Processing... projects

### ISSUE THREAD

**Issue by NieropT** [amcat/amcat#498]
When I'm trying to open a part of the articleset about the Dutch news that I have used in my own project, it just keeps on processing forever. It is affecting other users (classmates) as well.

**Comment by martijnbastiaan** [comment]
Could you post the URL of the page you're experiencing this?

**Comment by NieropT** [comment]
https://amcat.nl/navigator/projects/1078/articlesets/

**Comment by martijnbastiaan** [comment]
Thank you, one moment.

**Comment by martijnbastiaan** [comment]
Are you still experiencing the same behaviour now?

**Comment by NieropT** [comment]
It’s working again! Thank you! 
Was it something I did? Or something I should do differently? I’m a novice in using AmCAT

**Comment by martijnbastiaan** [comment]
It's unfortunately a long-standing bug in AmCAT. More specifically, our searching backends (which is also used to query the number of articles in articlesets) do not support forceful cancellation of queries. This causing bugged queries to run basically forever, slowly clogging up the backends (at least, that's the hypothesis). So it's definitely a problem on our side, not on yours! :)

Thanks for reporting. We are still trying to find solutions for this problem..
