### ISSUE TITLE
Exporting articles to HTML

### ISSUE THREAD

**Issue by markboukes** [amcat/amcat#501]
Another question: I very frequently use the "export to HTML"-function. In the new lay-out, i cannot find this option any more. 

How can i query for certain dates, get a number of articles, and export these to a clear format from which the articles can be read by coders - preferably HTML?

**Comment by martijnbastiaan** [comment]
This has been added again. It's not ideal, but you can use the articlelist action and then use the export button. It will offer a HTML export option. If you want to export text, make sure you select 'text' as the column you're exporting.

![screenshot from 2016-04-20 21-31-53](https://cloud.githubusercontent.com/assets/5658854/14687825/5642aabe-0737-11e6-931e-07d669fbf003.png)

**Comment by markboukes** [comment]
Not ideal? It works perfectly it seems :)

Thanks!
