### ISSUE TITLE
Query date interval selection does not work properly, gives incorrect results for 'on'.

### ISSUE THREAD

**Issue by CJStuart** [amcat/amcat#502]
@markboukes: 
> If you selected "on", e.g., 02-06-2015, then you *all * articles instead of the selection based on date. 
If you selected "between", e.g., from 02-06-2015 till 03-06-2015, you only get the results of 02-06-2015.

also see: #499

**Comment by CJStuart** [comment]
The question is whether the end/before date should be inclusive or exclusive. 

@vanatteveldt what do you think?

**Comment by markboukes** [comment]
My main problem is that the "on" function doesn't work :)

**Comment by vanatteveldt** [comment]
I would make them inclusive, I think that makes most sense (and maybe have a 'tooltip' to explain it correctly)

**Comment by martijnbastiaan** [comment]
Changing it from inclusive to exclusive requires a lot of small changes all over the place (including amcates). So maybe consider explaining it or choosing better names in the GUI.

**Comment by vanatteveldt** [comment]
You're probably right :)

Is hte problem with "on" that it does X to X (exclusive), instead of X to X+1?

**Comment by CJStuart** [comment]
I believe 'on' is just completely broken for 'articlelist' queries and does nothing. In other queries, eg. summary and graphs, it does seem to work correctly.

**Comment by vanatteveldt** [comment]
The articlelist passes the filters on to the articles API, right? Does that API ignore all date ranges, or should it be passed differently?

**Comment by CJStuart** [comment]
The search API ignored the on_date filter, it wasn't registered along with the start_date and end_date filters for some reason. fixed that in e1ec271

**Comment by vanatteveldt** [comment]
I've also update amcat.nl, so it should work now

PS @markboukes are you subscribed to amcat-user? We released 3.4 as a preview/release candidate a while ago, so you could have tested your work flow on the new version before it was pushed to amcat.nl. See https://groups.google.com/forum/#!forum/amcat-user

**Comment by markboukes** [comment]
@vanatteveldt, great the date function works now. I was not aware of the Google Group, so i didn't have the opportunity to test it for you guys. Apologies. 

I will send you an e-mail regarding issue #501
