### ISSUE TITLE
Add link to codingjob to article metadata

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#503]
Adding a link to the codingjob (instead of just the codingjob set) to the article metadata would make recoding articles (in the Annotator) easier. Maybe this could be added in 3.5?

Longer explanation: I often have to search for specific articles that I have to recode. I search for these articles in the Query section, open up each article, note down the codingjob(s) in which they occur, and then go to the Annotator to open the codingjob(s) to recode the articles. This could be a little faster if the link to the codingjob (in the navigator, so this:

![codingjob](https://cloud.githubusercontent.com/assets/6417728/14640068/097ad30c-0640-11e6-9bc6-d4b4dcf2a8db.png)
)

could be added as an extra type of metadata here:
![article](https://cloud.githubusercontent.com/assets/6417728/14640086/24303c8c-0640-11e6-8143-960be8f5af2e.png)

Currently, only the codingjob set is listed in the metadata, but I cannot click through to the Annotator (to recode the article) from the codingjob set, only from the codingjob itself. Thanks!

**Comment by vanatteveldt** [comment]
Sorry, I didn't get an email for this issue, makes perfect sense.
