### ISSUE TITLE
Amcat exporteert bij query max 10000 results

### ISSUE THREAD

**Issue by doegema** [amcat/amcat#505]
Hi,

Amcat exporteert bij query max 10000 results, ongeacht via welke modus (csv, sav, xls). 
Bijv: Op een query op NS2016 (set 48759 in project 1037) met de zoektermen NS spoor* levert 22568 docs. Als ik op export druk geeft deze functie netjes aan Limit to 22568 results. Echter in de download vind ik 10000 records. Zouden jullie hier naar willen kijken? Of zie ik nog een knop over het hoofd in de mooie nieuwe interface. Die verder prachtig lijkt te werken!

Groetjes, Dirk

**Comment by markboukes** [comment]
I'm experiencing the same problem.

**Comment by martijnbastiaan** [comment]
Relevant files:

* https://github.com/amcat/amcat/blob/master/api/rest/pagination.py#L53
* https://github.com/amcat/amcat/blob/master/navigator/static/js/amcat.datatables.js#L156

@vanatteveldt Is ophogen OK, of moeten we werken aan pagination in de datatables exporter?

**Comment by vanatteveldt** [comment]
In ieder geval zou de interface correct de beperking moeten weergeven. Zullen we beide op 100k zetten en kijken hoe het gaat?

**Comment by markboukes** [comment]
Ja, als 100,000 kan zou dat perfect zijn. Weinig artikelen sets zullen daar boven komen denk ik, maar de 10,000 tik je toch gemakkelijk aan.

**Comment by doegema** [comment]
Hi,

Fijn dat ie opgehoogd wordt. Als gebruiker scheelt het als je ziet wat ie aan het doen is, zoals nu in R het geval is. Daar zie je met welke set hij bezig is. Dat voorkomt dat mensen (vooral nieuwkomers) meerdere keren op de knop drukken of het venster dicht doen.

Groetjes, D

Van: Wouter van Atteveldt [mailto:notifications@github.com]
Verzonden: Monday, May 09, 2016 5:58 PM
Aan: amcat/amcat
CC: Oegema, D.; Author
Onderwerp: Re: [amcat/amcat] Amcat exporteert bij query max 10000 results (#505)


In ieder geval zou de interface correct de beperking moeten weergeven. Zullen we beide op 100k zetten en kijken hoe het gaat?
