### ISSUE TITLE
Code 500: Internal server error

### ISSUE THREAD

**Issue by veradekkers** [amcat/amcat#506]
Als ik met query's wil zoeken in Amcat geeft hij geen output maar krijg ik, in verschillende browsers (Chrome, Firefox) de foutmelding zoals te zien is in de bijlage. Kan dus niet met Amcat werken door deze melding.

![schermafdruk 2016-04-22 12 00 31](https://cloud.githubusercontent.com/assets/18612849/14738610/d58d5732-0882-11e6-94dd-d58dde9fa78f.png)

**Comment by vanatteveldt** [comment]
Kan je de zoekstring even hier in het comment plakken? Zitten er tabs in, of zijn dat spaties?

**Comment by veradekkers** [comment]
Het geldt voor al mijn zoekstrings dat hij het nu niet meer doet en in de oude versie wel. In de bijlage vind je mijn ontologie. 

[Werkbestand ontologie AMCA.xlsx](https://github.com/amcat/amcat/files/231686/Werkbestand.ontologie.AMCA.xlsx)

**Comment by vanatteveldt** [comment]
Kan je de zoekstring even hier in het comment plakken? Zitten er tabs in, of zijn dat spaties?

**Comment by veradekkers** [comment]
![image](https://cloud.githubusercontent.com/assets/18612849/14741389/31e4de20-0896-11e6-8815-28a507bfac6d.png)

Tabs omdat het inhoud van verschillende cellen is denk ik?

**Comment by veradekkers** [comment]
referendum	referendum					(referendum )	AND (associatieovereenkomst associatieverdrag verdrag overeenkomst) AND (oekra* NOT lissabon)

**Comment by vanatteveldt** [comment]
Het lijkt erop dat iemand de set 25267 uit het project heeft verwijderd (unlink), hij staat nog in de lijst omdat hij wel favourite was (dat is een bug lijkt me). Ik ga even proberen de set weer terug te zetten

**Comment by vanatteveldt** [comment]
Met set 25267 werkt het nu in ieder geval, reopen de issue als er nog meer sets met problemen zijn.
