### ISSUE TITLE
Firefox fails to load heatmap on 3.4

### ISSUE THREAD

**Issue by martijnbastiaan** [amcat/amcat#508]
Firefox is unable to open the query screen without crashing. On master this is "fixed" by disabling heatmap support altogether.

**Comment by CJStuart** [comment]
Are you sure it's not an adblocker that causes this? Adblockers using the EasyPrivacy list block any file matching the `/heatmap.*?` regex.

**Comment by martijnbastiaan** [comment]
That makes so much sense! I don't have an adblocker in Chromium, so that explains it.

**Comment by CJStuart** [comment]
I had the exact opposite problem: it worked in Firefox, but not in Chrome. Took me a while to figure it out.
