### ISSUE TITLE
Some articlesets seem to be no longer fully indexed after AmCAT update

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#510]
This is really strange, but some articlesets that were fully indexed (turned into coding jobs and coded) before seem to have reverted to only a half-indexed stage after the AmCAT update:

![indexing](https://cloud.githubusercontent.com/assets/6417728/14878945/b4c53e40-0d26-11e6-8245-7b2b8f8161b1.png)

I cannot figure out why this has happened to some articlesets but not others. It seems to be only slightly older articlesets, but not all of them. Is it possible that the update has changed things? Or should I just re-index things manually (if it is only this one project (29) that has the problem)?

**Comment by vanatteveldt** [comment]
I don't think this is connected to the upgrade. There was an ealier problem when the index nodes ran out of disk space, maybe this is a lingering problem. It could also be aggressive deduplication?

Can you try to reindex one set manually? If there are a lot of sets I can also make a simple script to reindex a whole project?
