### ISSUE TITLE
Request for lemmatization

### ISSUE THREAD

**Issue by jeroenGF** [amcat/amcat#511]
Set nrs: 24572; 24571; 24570; 24569; 24566

Thanks for looking at it!

**Comment by vanatteveldt** [comment]
Hey Jeroen,

Sorry for taking a while, I was lemmatizing 4M articles from de Telegraaf for my own research and that took a bit longer than I had hoped. 

https://amcat.nl/api/v4/projects/986/articlesets/24571/preprocess/ and https://amcat.nl/api/v4/projects/986/articlesets/24570/preprocess/ are done. 24572 is German language, and we don't have a German lemmatizer installed. The other two sets are social media and I think mixed-language, if you can separate them out by language I can lemmatize these as well. 

For retrieving the tokens from R you need to specify the 'module' name: for Dutch, this is "frog", for english it is "corenlp_lemmatize". 

Please let me know (or reopen this issue) if you run into any problem.

-- Wouter

**Comment by vanatteveldt** [comment]
O by the way: if you don't care about lemmatization per se, but just want the tokens, you can always use module="elastic" (should be the default if you update amcat-r), that just returns the words themselves as tokenized by elastic.
