### ISSUE TITLE
BZK html uploader says 'polling task failed'

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#512]
I have problems uploading a specific document using the BZK HTML. When I try to upload it, AmCAT shows this screen
![polling failed](https://cloud.githubusercontent.com/assets/6417728/14911524/355c6fea-0df6-11e6-97d2-bc952159f2e4.png)

And uploads 0 articles. I can upload other (previously uploaded) documents without problems.

I put the problematic document here:
https://www.dropbox.com/sh/vv4k2li0j1wt4v5/AAAiLZFmyDE6Do2y-dXFagbja?dl=0

**Comment by CJStuart** [comment]
The article with the headline: 'Wij ontberen een ministerie van Energie in ons land'
appears to have a problematic date: `28-04`, If this is changed to `28-04-2016` it should work. 

It shouldn't fail polling, though, on my local machine it gives an appropriate error.

**Comment by carinajacobi** [comment]
Yes, I was able to upload it now. Thank you!

**Comment by martijnbastiaan** [comment]
Error should be displayed in master (instead of poll failure).
