### ISSUE TITLE
http://auc.amcat.nl bad gateway for access using R

### ISSUE THREAD

**Issue by NieropT** [amcat/amcat#516]
Hi,

I got the following failure in RStudio:

> library(amcatr)
> amcat.save.password("http://auc.amcat.nl", username='Thijs', password='XXXX')
> library(amcatr)
> conn = amcat.connect("http://auc.amcat.nl")
Error in value[[3L]](cond) : 
  Could not get token from Thijs@http://auc.amcat.nl please check host, username and password. Error: Error: Bad Gateway

Logging in to https://amcat.nl/ with the Username and password is not a problem. Obviously I altered the password here.

**Comment by vanatteveldt** [comment]
auc.amcat.nl is a virtual server specifically for a course I teach at AUC, so your amcat account doesn't work there.  Why would you want to log on to that server?
