### ISSUE TITLE
Problems with loading articles and using interval option

### ISSUE THREAD

**Issue by ips12** [amcat/amcat#517]
Hallo,

Wanneer ik op een Mac met Firefox AmCat wil gebruiken lukt het mij niet bij query de interval een functie te selecteren. Ik kan hierdoor geen datum invoeren/selecteren. Met Safari en Google Chrome kan ik de interval functie wel gebruiken, alleen worden de zoekresultaten niet geladen. Het scherm blijft dan hangen op "waiting for results".
Op een Windows pc kan ik in Firefox wel de interval functie aanpassen maar wordt mijn zoekopdracht ook niet uitgevoerd. Wanneer ik Internet Explorer gebruik op de Windows pc blijft het scherm hangen op de pagina waar de datasets geselecteerd moeten worden.

Hieronder vindt u een aantal screenshots.
Hopelijk kunt u mij helpen?

Groet,
Ilse

![screen shot 2016-05-05 at 3 18 24 pm](https://cloud.githubusercontent.com/assets/19206693/15044384/af67faa6-12d4-11e6-8f00-372f2ec6428c.png)
![screen shot 2016-05-05 at 2 49 18 pm](https://cloud.githubusercontent.com/assets/19206693/15044096/c72e3cec-12d2-11e6-88b5-f67c7dda8966.png)
![window_firefox_amcat](https://cloud.githubusercontent.com/assets/19206693/15044247/abdb8642-12d3-11e6-8b01-1e2f3f533d0b.png)
![windows_ie_amcat](https://cloud.githubusercontent.com/assets/19206693/15044246/abdb38cc-12d3-11e6-96dd-e35277b5cc27.png)

**Comment by vanatteveldt** [comment]
Dag Ilse,

Je hebt in ieder geval alle mogelijkheden geprobeerd :)

Het hangen op "loading results" was een probleem op de server, dat zou nu opgelost moeten zijn.

De datumseletie op mac+firefox: gaat dat wel goed als je even totaal refresht (control+f5, maar ik weet niet wat dat op een mac is), en/of de cache leegmaakt?

Internet Explorer wordt overigens niet ondersteund, dus dat is geen verrassing. 

Ik sluit het issue, heropen gerust als het nog niet werkt.
