### ISSUE TITLE
Table exporting does not display progress bar

### ISSUE THREAD

**Issue by martijnbastiaan** [amcat/amcat#520]
Now that we've increased the maximum number of exportable items to 100.000 (issue #505), exports can become quite slow. As @doegema said: new users get confused and either leave the page or click the export button multiple times. We should therefore implement some kind of progress bar. Additionally, it would be nice to be able to do [streaming responses](http://www.django-rest-framework.org/api-guide/responses/) as well.

**Comment by vanatteveldt** [comment]
(closing due to inaction)
