### ISSUE TITLE
Problem with exporting date/total tables as csv

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#522]
When I create a date/total table, and export this as a csv
![totaltable1](https://cloud.githubusercontent.com/assets/6417728/15180293/f0130dec-1780-11e6-8796-2c8d5a739c65.png)

Excel appears not to 'see' the frequencies in the resulting csv

![totaltable2](https://cloud.githubusercontent.com/assets/6417728/15180318/17f09b18-1781-11e6-95b6-1b4895c9d3c8.png)

resulting in an Excel table with only the dates, the 'total' column is empty, which is not very useful

![totaltable3](https://cloud.githubusercontent.com/assets/6417728/15180360/5d821b8e-1781-11e6-89f7-4cafc88a8642.png)

This problem seems to only occur for the date/total combination; I also tried other combinations such as medium/total, date/search term, and date/medium, and the csv they produce does not have this problem.

**Comment by CJStuart** [comment]
the output does seem to be correct, for example: 

```
date,total
2015-01-01 00:00:00,1
2015-04-01 00:00:00,2
2015-07-01 00:00:00,1
2015-10-01 00:00:00,1
```

Dutch Excel versions might be interpreting the separator as a decimal comma.

**Comment by carinajacobi** [comment]
But is it possible that Excel does so only for date/total tables? Because
the problem only occurs with those, not with medium/total, date/search term
or other cross tables exported from AmCAT.

Perhaps semicolon-separated csv or xlsx could be added as output options?

**Comment by martijnbastiaan** [comment]
ODS and XLSX support would definitely be nice. CSV is not really convenient for Excel users.

**Comment by CJStuart** [comment]
I noticed we've got table serializers/exporters all over the place with lots of duplicate code. Maybe it would be a good idea to gather them all in one place under one interface, eg. refactor things so they all use the Table interface for exports.

**Comment by CJStuart** [comment]
I added semicolon CSV to the export options as a workaround in 3.4.
