### ISSUE TITLE
Password reset instructions link to amcat.vu.nl which has expired https certificate

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#524]
```
Hi Wouter,
You're receiving this e-mail because you requested a password reset for your user account on AmCAT. Please go to the following page and choose a new password:
https://amcat.vu.nl/accounts/reset/.../
Your username, in case you've forgotten: wva
```

Related to #523

**Comment by vanatteveldt** [comment]
(strange enough, I can't find a reference to amcat.vu.nl, the view references {{domain}}, but I have no idea how that is set)

**Comment by joepschaper** [comment]
It doesn't seem to work at amcat.nl either. After filling in my email address I get the message: "An email with instructions has been sent", but I haven't received anything. I tried all my different email addresses and waited 5-10 minutes. Hopefully it's just slow(?)

**Comment by vanatteveldt** [comment]
It works for me, so I think you just have an old email address. I've sent you a mail to your gmail account.

**Comment by joepschaper** [comment]
I'm back, Thanks Wouter!

**Comment by vanatteveldt** [comment]
I still have no clue where to find the amcat.vu.nl reference... @martijnbastiaan @CJStuart   any idea?

**Comment by CJStuart** [comment]
it seems to be set in django.contrib.auth.forms.PasswordResetForm#save

**Comment by CJStuart** [comment]
Found it, it can be set under Sites in the admin settings.

**Comment by vanatteveldt** [comment]
That's just mean, I was looking in the source code (where I guess it doesn't belong). I assume you changed it to amcat.nl? (closing the issue)
