### ISSUE TITLE
17404 18096 codebooks werken niet meer

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#525]
Als je een codebook wilt gebruiken, dan verschijnt een foutmelding (zie png), ook als je helemaal niets invoert, of i.p.v. <Extremisten> (een concept uit het codebook) Extremisten, [Extremisten], of helemaal niets invoert. 
![fout500 bij codebook](https://cloud.githubusercontent.com/assets/6690321/15318812/2691590e-1c28-11e6-957d-7721697aa46c.PNG)

Werkt de codebook-functionaliteit helemaal niet meer? Studenten die vorig jaar net niet zijn afgestudeerd op ander spoor zetten?

**Comment by vanatteveldt** [comment]
@CJStuart kan jij hier even naar kijken?

**Comment by CJStuart** [comment]
fixed in  995b137d

**Comment by Kleinnijenhuis** [comment]
Beste Christian, helaas is het probleem met het toepassen van queries uit een een codebook niet verholpen. Zowel in de "gewone" amcat als in de preview-versie krijg ik een vergelijkbare foutmelding #515 die Tobycoder doorgegeven heeft.

Gegevens om onderstaande fout te kunnen reproduceren: project 704, articleset 18096, selecteer bijvoorbeeld als medium alleen NRC Handelsblad, codebook 700 Ontologieterreur 26042015, query <Extremisten>

Unknown error. Server replied with status code 500: INTERNAL SERVER ERROR. Full error: 
{"exception_type":"AttributeError","detail":"'SelectionData' object has no attribute 'codebook'"}
