### ISSUE TITLE
set 21413, de met Alpino zinsontleding bewerkte versie van 18096, bevat geen zinsontledingen (meer?)

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#526]
set 21413 was de vorig jaar tbv 3 studenten geparsede versie van 18096, maar blijkens 
https://amcat.nl/api/v4/projects/1/articlesets/21413/preprocess/
is 21413 thans niet geparsed met Alpino; 1 van de 3 studenten moet nog afstuderen.
Moet 18096 dan opnieuw worden geparsed, en kan 21413 worden verwijderd?

**Comment by vanatteveldt** [comment]
Er waren helaas problemen met de parses, en het leek uiteindelijk het makkelijkst om alle eerdere parses te verwijderen en waar nodig opnieuw te parsen.

Ik neem aan dat je bewust vraagt om alpino en niet om frog?

**Comment by Kleinnijenhuis** [comment]
Ha Wouter,
ja, het gaat om set 18096 (ruim 6200 dagbladartikelen en tt888-items). Het klopt toch dat de grammaticale analyse waar we nu mee bezig zijn tbv Oekraineproject Alpino veronderstelt? Dat kan dan ook worden gebruikt door Hafsa Chairi, die vorig jaar afhaakte, maar nu alsnog haar scriptie wil schrijven over rechtvaardiging van terrorisme.
H groet, Jan
________________________________
Van: Wouter van Atteveldt [notifications@github.com]
Verzonden: dinsdag 17 mei 2016 12:30
Aan: amcat/amcat
CC: Kleinnijenhuis, J.; Author
Onderwerp: Re: [amcat/amcat] set 21413, de met Alpino zinsontleding bewerkte versie van 18096, bevat geen zinsontledingen (meer?) (#526)


Er waren helaas problemen met de parses, en het leek uiteindelijk het makkelijkst om alle eerdere parses te verwijderen en waar nodig opnieuw te parsen.

Ik neem aan dat je bewust vraagt om alpino en niet om frog?
