### ISSUE TITLE
export csv van articlelist met text-left-keyword-right

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#527]
Bij left-keyword-right wordt kennelijk uit een artikel waarin verschillende concepten verschillende keren voorkomen een left-keyword-right triplet geselecteerd. Heeft dit een logica, en zo ja, welke? Is er een manier om in AMCAT alle left-keyword-right triplets uit een artikel op te sporen?

Hieronder een voorbeeld van een export van 1 artikel, met verschillende hits voor verschillende trefwoorden, maar slechts 1 left-keyword-right triplet.
![image](https://cloud.githubusercontent.com/assets/6690321/15320032/a2492a9e-1c2e-11e6-9b3e-5d92b207d730.png)

**Comment by vanatteveldt** [comment]
Nee, in AmCAT zit niet zo'n mechanism omdat dat de logica van een artikel-lijst (1 rij per artikel) zou doorkruisen. Ik vermoed dat hij de eerste hit van de eerste zoekterm selecteert, maar zeker weet ik het niet.

Je kan natuurlijk de tokens ophalen en het in R doen, maar met ingewikkelde queries is dat weer lastiger?

**Comment by Kleinnijenhuis** [comment]
oplossingsrichtingen helder; het zal vast de eerste hit van de eerste zoekterm zijn, maar bij het afdrukken op het scherm wordt dan weer een andere volgorde aangehouden.
________________________________
Van: Wouter van Atteveldt [notifications@github.com]
Verzonden: dinsdag 17 mei 2016 13:03
Aan: amcat/amcat
CC: Kleinnijenhuis, J.; Author
Onderwerp: Re: [amcat/amcat] export csv van articlelist met text-left-keyword-right (#527)


Nee, in AmCAT zit niet zo'n mechanism omdat dat de logica van een artikel-lijst (1 rij per artikel) zou doorkruisen. Ik vermoed dat hij de eerste hit van de eerste zoekterm selecteert, maar zeker weet ik het niet.

Je kan natuurlijk de tokens ophalen en het in R doen, maar met ingewikkelde queries is dat weer lastiger?
