### ISSUE TITLE
barplot search queries nested within media : labels media mixed up

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#529]
Query screen, graph/table output, select media on x-axis, term on y-axis
The graph bellow shows that Trouw did neither report on the victim frame nor on the intruder frame,
whereas Pauw & Witteman report a lot on both. Removing Pauw & Witteman from the selection will show the same graph, but now with the bars of Pauw & Witteman atached to Knevel & Van den Brink.
I did not test yet whether the same error occurs with tables.
![media-term bar plot](https://cloud.githubusercontent.com/assets/6690321/15342612/0cd51b6c-1c97-11e6-9f52-ee205adb5ebc.PNG)

**Comment by Kleinnijenhuis** [comment]
The corresponding Table appears to be correct:
volgens Trouw zijn wij 22097 keer affluent tegen 16564 keer deprived, een mooie positieve balansscore van +0.14. In Pauw & Witteman komen inderdaad veel minder items vvoor: 566 keer zijn wij affluent, 544 keer deprived, een socialistische kommer en kwel balansscore van slechts +0.02.
Concluse: alleen in de bar plot worden labels van media verwisseld (of omgekeerd getallenreeksen om bij labels gegevens af te drukken)

**Comment by CJStuart** [comment]
Fixed in amcat/amcat-query-js@e81d990
