### ISSUE TITLE
Random success when clicking on line plot

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#530]
Wanneer ik een lijngrafiek maak en wil doorkllikken om de artikelen te zien, doet AmCAT dat soms wel, soms niet...om onverklaarbare redenen. in de console staat dit:
articlemodal.js:37 Uncaught TypeError: Cannot read property 'start_date' of null
highcharts.js?cache=default_token:25 Uncaught TypeError: Cannot read property 'start_date' of nullelastic_filters.date @ articlemodal.js:37(anonymous function) @ articlemodal.js:70jQuery.extend.each @ jquery.js:382articles_popup @ articlemodal.js:68show @ articlemodal.js:146chart.plotOptions.series.events.click @ renderers.js:459jQuery.event.dispatch @ jquery.js:4435elemData.handle @ jquery.js:4121jQuery.event.trigger @ jquery.js:4350(anonymous function) @ jquery.js:4901jQuery.extend.each @ jquery.js:374jQuery.fn.jQuery.each @ jquery.js:139jQuery.fn.extend.trigger @ jquery.js:4900L.HighchartsAdapter.L.HighchartsAdapter.a.fireEvent @ highcharts.js?cache=default_token:25Va.onContainerClick @ highcharts.js?cache=default_token:178b.onclick @ highcharts.js?cache=default_token:179
highcharts.js?cache=default_token:25 Fetching OPTIONS for table:  undefined
amcat.datatables.js:872 Calling dataTable with options:  Object {searching: true, bDeferRender: true, bFilter: false, iDisplayLength: 10, bProcessing: true…}

Zie ook:
![image](https://cloud.githubusercontent.com/assets/6438205/15352598/3fe91a46-1ce5-11e6-8bbe-c65cda6f9849.png)

**Comment by CJStuart** [comment]
I'm having trouble reproducing this error, for me it seems to work every time. Could you provide more information on when it occurs?

**Comment by nruigrok** [comment]
Well the problem is it occurs sometimes, not all peaks in a bar plot for
example but sometimes it does occur. What kind of information do you need?
For example in amcat project 333 if you take articleset 29303 and make a
line plot with all news in that set per year. The first peak, 1956 doesn't
work, while 1992 does work..at least on my computer (firefox)

Hope this helps,
Nel



Dr. N. Ruigrok
Singel 445-V
1012 WP Amsterdam
+31-627588586
//nieuwsmonitor.org
nelruigrok@nieuwsmonitor.org

**Comment by vanatteveldt** [comment]
I can confirm the problem, this is a save of Nel's query, clicking submit should show the problem immediately:

https://amcat.nl/navigator/projects/333/query/?query=94&sets=29303#aggregation

**Comment by CJStuart** [comment]
I guess it's got something to do with unix timestamps: 1968 and before won't not work at all, 1969 and 1970 give incorrect results, and it works correctly from 1971 onwards.

**Comment by CJStuart** [comment]
fixed in amcat/amcat-query-js@8a952ba
