### ISSUE TITLE
Amcat down

### ISSUE THREAD

**Issue by joepschaper** [amcat/amcat#531]
I can't seem to get on amcat.nl. Is amcat down?

Best,

Joep

**Comment by joepschaper** [comment]
I tried different browsers and restarting the computer, no success

**Comment by joepschaper** [comment]
It's back now, thanks!

**Comment by joepschaper** [comment]
Down again :-(

**Comment by martijnbastiaan** [comment]
And.... up?

**Comment by joepschaper** [comment]
Yes, but it gets stuck when I'm clicking on the query button / trying to open an article set

**Comment by martijnbastiaan** [comment]
Ok, 1 moment.

**Comment by martijnbastiaan** [comment]
Should be fast again :). Thanks for reporting!

**Comment by joepschaper** [comment]
Yes! Thanks Martijn!

**Comment by timvandijk92** [comment]
Hi!

Is AmCAT down atm or is it just me? 

I can reach the website but query gets stuck at 'Waiting for task to start..'. Tried restarting, different sets, etc. but no luck. 

Kind regards,

Tim

**Comment by CJStuart** [comment]
Should be back up.

**Comment by timvandijk92** [comment]
It is, thanks!
