### ISSUE TITLE
Amcat stuck/slow when opening article set / query

### ISSUE THREAD

**Issue by joepschaper** [amcat/amcat#533]
Amcat was working well this morning, until now. Same problem as yesterday.

Cheers - Joep

**Comment by carinajacobi** [comment]
Same problem here, amcat.nl doesn't load, I cannot save codings in the
Annotator, nothing works.

**Comment by carinajacobi** [comment]
Ho hij doet het weer

**Comment by joepschaper** [comment]
Bij mij niet

**Comment by carinajacobi** [comment]
Ja het wisselt een beetje.. Wouter zegt in de chat:
het probleem is dat ik het gewoon niet weet
het is vast een combinatie van veel gebruik en een paar dingen waar hij
echt van flipt
ik heb dinsdag een meeting met de IT mensen hier, wellicht kunnen die nog
iets nuttigs zeggen

**Comment by vanatteveldt** [comment]
Nu weer wel. Ik weet nit precies wat er mis is.

Joep, kan jij even mailen wat voor queries jij aan het runnen bent? Misschien dat daar een deel van de oplossing zit?
