### ISSUE TITLE
Zoekfunctie Amcat functioneert niet

### ISSUE THREAD

**Issue by veradekkers** [amcat/amcat#534]
Ik probeer al een paar dagen (sinds dinsdag) in Amcat te zoeken en zoektermen te combineren. Dit werkt echter niet tot zeer zelden. Wat ik probeer is te zien in de bijlage, maar ook losse zoekwoorden doen het niet. Het is één keer gelukt om er iets uit te halen, verder niets en hij doet heel erg lang over laden. Sinds vandaag gaat de laadbalk ook heen en weer, van bijna geladen tot helemaal niet en er komt geen resultaat hij blijft heel erg lang bezig. Er komt meestal geen foutmelding want hij laad niet door. Een enkele keer geeft hij een undefined error. 

Wat is hier aan de hand en wat kan ik hieraan doen want ik kan zo niet verder?

Vera
![image](https://cloud.githubusercontent.com/assets/18612849/15389120/95b69f4a-1db5-11e6-8a6a-1fd0088ec2a9.png)

**Comment by Kleinnijenhuis** [comment]
Gisteren wilde ik standaardanalyses in AMCAT uitvoeren. Daarbij liep ik op tegen dezelfde problemen op als die door Vera worden beschreven. Eerst een melding dat het nog even duurt voordat je zoekstring verwerkt zal worden. Vervolgens "no results yet", dan vaak een rood scherm met de oninformatieve foutmelding 500 dat er iets undefined is. Je gaat dan toch weer twijfelen aan je queries, maar daar lag het echt niet aan. Voor je het weet is de dag dan om ...

**Comment by vanatteveldt** [comment]
@veradekkers kan je even de tekst van je query hier copy/pasten, want ik kan het niet kopieren uit je screenshot

**Comment by veradekkers** [comment]
democratieOek#				(democrati*)
positief#				(aangena* aantrekkelijk* aanzien* aardig* actief* adequa* allerbest* applaus* barmhartig* befaamd* begrijpelijk* begripvol* behulpzaam* bekwa* belastingvoordeel* beschaafd* bescheidenheid* best* beter* betrokken* betrouwba* betrouwbaarheid* bevlogen* bijzonder* blij* blijde* boeiend* briljant* charmant* collegia* comfortabel* competent* conscientieu* consensus* constructie* cool* correct* coulance* creatie* daadkrachtig* dankba* dapper* deskundig* deugdelijk* dierba* diplomatiek* doelmatig* doeltreffend* dolblij* eensgezind* eensgezindheid* eenvoudig* eerlijk* effectie* efficiency* efficiencywinst* efficient* eminent* enthousiasme* enthousiast* ervaren* esthetisch* evenwichtig* excellent* excelleren* fair* fantastisch* fatsoenlijk* favoriet* feestelijk* felbegeerd* fenomenaal* fijn* filantropisch* florissant* foutlo* fraai* fris* geacht* gedreven* geduldig* geliefd* gelijkheidsdenken* gelijkwaardig* geloofwaardig* gelukkig* gemakkelijk* gemoedelijk* gemotiveerd* genia* gerechtvaardigd* gerenommeerd* gerust* geschikt* getalenteerd* geweldig* gezaghebbend* gezellig* gezond* glansrijk* goed* goedwillend* goeie* goodwill* gul* gunstig* haalba* handig* hardwerkend* hartelijk* hemels* herkenba* hoffelijk* hoogbegaafd* hooggekwalificeerd* hooggewaardeerd* hoogwaardig* hoop* hoopvol* huma* idea* ijverig* indrukwekkend* ingenieu* innovatie* inspireren* intelligent* interessant* juist* kansrijk* keurig* knap* kunde* kwalitatief* kwaliteit* kwaliteitsverbetering* leergierig* leergierigheid* leerontwikkeling* lef* lekker* leuk* lief* lieve* liefste* liefde* liefdevol* lof* lofzang* lol* loya* lucratief* majestueu* makkelijk* meerwaarde* meevaller* moedig* moeiteloos* mooi* moreel morele* nauwkeurig* netjes* nobel* nuttig* objectie* onpartijdig* ontplooiing* ontspannen* ontwikkeld* onverschrokken* opgelucht* opgewekt* optima* optimisme* optimistisch* overtuigend* overzichtelijk* perfect* plezier* plezierig* populair* populariteit* positief* positieve* prachtig* praktisch* prestigieu* prettig* prima* proactie* proba* probleemlo* professionaliteit* professione* profijt* profilering* prominent* proominent* rechtvaardigheid* rekenprestatie* relevant* representatie* respect* respectabel* respectvol* rijk* ruimhartig* rust* schitterend* schoon* schone* sfeervol* slagvaardig* slim* smakelijk* socia* soepel* solidair* solide* sportief* standvastig* stijlvol* stimulans* strijdbaar* succesvol* sympathiek* talentontwikkeling* talentvol* tevreden* tevredenheid* toegankelijk* toegewijd* toereikend* tof* tolerant* toonbeeld* topfunctie* topinstituut* topleraar* topmens* topmusicus* topniveau* toponderzoek* topopleiding* topper* toppositie* topsector* toptalent* topuniversiteit* topvrouw* trots* trouw* uitblinker* uitstekend* vaardig* veelbelovend* veelzijdig* veilig* verantwoord* verantwoordelijk* verbeter* verbetering* verheugd* verstandig* vertrouw* vindingrijk* vlot* voldoende* vooraanstaand* voordeel* voordelig* voortreffelijk* voortvarend* vooruitgang* vooruitstrevend* vorstelijk* vrede* vreedzaam* vriendelijk* vrolijk* ware* waarachtig*waardering* waardig* waarheid* weldenkend* welgesteld* welkom* weloverwogen* welwillend* welwillendheid* welzijn* wereldfaam* wereldklasse* werkbaar* wijs* wijze* winstgevend* zalig* zelfstandig* zinvol* zorgvuldigheid* zorgza*)
"<democratieOek> <positief>"~15

Je zou misschien denken dat het zou kunnen liggen aan lengte van zoekstring positief, maar deze heeft het voorheen wel gewoon gedaan. Ook de onderste zoekstring heeft mij eerder wel resultaten opgeleverd maar nu doet hij het dus totaal niet meer. Vanmiddag deed hij het zelfs niet als ik alleen op democratieOek# zocht. Heb veel verschillende zoekstrings en combinaties uitgeprobeerd maar hij vind geen resultaten meer (voorheen met dezelfde query's wel).

**Comment by vanatteveldt** [comment]
het probleem is dat door (te) complexe queries de zoek-engine elastic vastloopt en dan reageert hij inderdaad nergens meer op. Het lijkt hierbij altijd te gaan om combinaties van zoektermen binnen X woorden, dwz "(veel zoektermen) (veel zoektermen)"~10. 

Ik zal een limiet moeten zetten op deze functie, want kennelijk kan AmCAT het gewoon niet aan. Het is overigens sowieso aan te raden dit soort dingen in R te draaien met semnet.

**Comment by veradekkers** [comment]
Dank voor je reactie. Zou ik er, als je er een limiet op hebt gezet, wel mee verder kunnen werken? Dat zou voor mij persoonlijk een stuk makkelijker zijn aangezien ik met Amcat tot nu toe beter uit de voeten kan dan met R. Als het niet lukt ga ik ermee aan de slag, maar ik hoor het graag!

**Comment by vanatteveldt** [comment]
De limiet zit erop, ga je gang! Als je hem weer "om" krijgt, mail dan direct even de set en de query, dan kan ik kijken of het probleem toch ergens anders zit... 

Ik stuur zo nog even een simpel "sentiment anlayse met semnet" documentje, dan zou het ook met R moeten lukken :)
