### ISSUE TITLE
Artikelen toevoegen (csv file) aan bestaande set

### ISSUE THREAD

**Issue by mse234** [amcat/amcat#541]
Hallo,

ik wil graag een set artikelen toevoegen aan mijn huidige set artikelen. Waar je eerst altijd een csv file kon upload, en waar de AMCAT handleiding dit ook nog steeds aangeeft, is deze optie nu nergens meer te vinden (zie screenshot). Ik heb dit zowel in Safari als Firefox geprobeerd te doen, maar in beide browsers liep ik tegen dit probleem aan. Is dit op korte termijn op te lossen?

Met vriendelijke groet,
Mike
![schermafbeelding 2016-06-01 om 17 06 04](https://cloud.githubusercontent.com/assets/18658648/15735675/cbdc657e-289a-11e6-85c8-5bd237d8e56f.png)

**Comment by vanatteveldt** [comment]
It should be back now!

**Comment by mse234** [comment]
Hallo Wouter,

functie zit er inderdaad in. Ik kom nu echter direct na het invoeren van de gegevens op onderstaand scherm.. Is dit ook op te lossen?
![schermafbeelding 2016-06-03 om 11 42 54](https://cloud.githubusercontent.com/assets/18658648/15775102/597ed9e4-2980-11e6-8634-136e13e7a831.png)
