### ISSUE TITLE
Limit on words in proximity search 

### ISSUE THREAD

**Issue by joepschaper** [amcat/amcat#543]
![error](https://cloud.githubusercontent.com/assets/6523565/15923953/07369280-2e30-11e6-9780-46572a33bdb1.jpg)
Hi Wouter and Martijn,

My query doesn't work. It is one that I have used before, so I don't believe the there's anything wrong with the query itself. I'm getting a red pop-up with the text: 'unidentified'.

I tried saving the query before using and a different browser.

I hope you can help!

Joep

**Comment by joepschaper** [comment]
Update: the text of the error has changed: "Unknown error. Server replied with status code 0:"

**Comment by joepschaper** [comment]
Update II: the error is back to : "undefined"

**Comment by joepschaper** [comment]
Update III: I've made some progress. Apparently the query analyzer is not entirely broken. Some search strings do work, but the ones I want to run (and have run in the past) don't work. 

This one works: 
"(islam* moslim) (immigr* vluchteling*)"~15

This one doesn't:
"(terror* terreur* radica* jihad* extremis*) (immigr* migr* vluchteling* bootvluchteling* asielzoeker* illegalen)"~15

I tried re-typing to make sure there are no macro's or something coming with copy/pasting.

**Comment by joepschaper** [comment]
There doesn't seem to be anything wrong with the query. There's now somehow a limit on the amount of words between ""~15

Can this limit be removed?

**Comment by martijnbastiaan** [comment]
The limit is there to protect our servers from dying every time someone 
issues a query which exceeds the capability of the hardware. Until we 
can either

1. Allocate a lot of resources :-), or..
2. Cancel queries which take too long to process

..this limit won't go away I'm afraid. (2) is in the works ATM, but it 
depends on code which is not maintained by us. @vanatteveldt: any known 
workarounds for the word distance problem?

That being said: it should definitely give a more descriptive error 
message, so I'm leaving this open as a bug report.

**Comment by joepschaper** [comment]
Hi Martijn,

Is there a possibility for a temporary exemption for this limit? I have to re-run some search strings on which I made some adjustments. It will take only 15 min. but it's really important for my analyses..

Joep

**Comment by joepschaper** [comment]
Sorry I was understating the problem. I found a mistake in some of the search strings that form the basis of a paper I'm writing. I'm a bit in distress because I want to know if my results still hold. It is only 9 search strings I have to run, so it won't take long, but it would help me enormously.

**Comment by martijnbastiaan** [comment]
I'll help you this afternoon. Will you be online on Google Talk?

**Comment by martijnbastiaan** [comment]
Sorry, I meant this night. I'll try to be online at 21:00.

**Comment by joepschaper** [comment]
I can't make it tonight, but this afternoon would be perfect, or tomorrow?

**Comment by joepschaper** [comment]
Or any moment today before 18:00..

**Comment by martijnbastiaan** [comment]
Let's do tomorrow night?

**Comment by joepschaper** [comment]
Cool, the earlier tomorrow night the better for me. Thanks Martijn!

**Comment by joepschaper** [comment]
Vanavond 21u kan ik toch wel, liever zelfs! Kan jij ook nog?

Joep

**Comment by joepschaper** [comment]
Hoi Martijn,

Ik zie dat de woordlimiet nog steeds van toepassing is. Is er zicht op wanneer die opgeheven wordt? Is het mogelijk voor mij om binnenkort nog een paar lange(re) zoektermen te draaien? Ik heb niet veel tijd nodig en de zoektermen zijn net als de vorige keer weer niet overdreven lang (onder de 20w).

Groeten,

Joep

**Comment by vanatteveldt** [comment]
I'm assuming this is fixed?

**Comment by joepschaper** [comment]
The limit is still in place, I just don't need to run long search strings
at the moment.

**Comment by joepschaper** [comment]
I would like to run some search strings that are (slightly) above the limit. Is it possible to lift the threshold for me again? 

Joep
