### ISSUE TITLE
broken link in bower.json

### ISSUE THREAD

**Issue by aemal** [amcat/amcat#544]
Hello!

There is a broken link in bower.json in both the stable and production versions in the following link:

"datatables": "http://hmbastiaan.nl/martijn/downloads/DataTables-1.10.7.zip",

It throws a 404 error and the bower is interrupted. Can you please fix it?

Thanks,
Aemal

**Comment by martijnbastiaan** [comment]
Fixed! Thanks for reporting!

**Comment by aemal** [comment]
Thanks for your swift action!
There is one more issue in the line:

    "requirejs": "",

It throws the following error:

bower ECMDERR       Failed to execute "git ls-remote --tags --heads https://github.com/jrburke/requirejs-bower.git", exit code of #128 fatal: unable to access 'https://github.com/jrburke/requirejs-bower.git/': Failed to connect to github.com port 443: Connection timed out

Additional error details:
fatal: unable to access 'https://github.com/jrburke/requirejs-bower.git/': Failed to connect to github.com port 443: Connection timed out

**Comment by martijnbastiaan** [comment]
I'm quite sure that's a temporary error or an issue with your network. I've tried it on three separate networks now and they all seem to work. Could you try it again?
