### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by aemal** [amcat/amcat#547]
Hello!

Unfortunately I am still facing problems in installing amcat. I have installed everything fine but after running the server by "python -m amcat.manage runserver" and visiting the address "http://127.0.0.1:8000/" I see the following python error:

```
ConnectionError at /accounts/login/
error 3 from memcached_get(:1:django.contrib.sessions.cache): (0x7f6d2801a3e0) CONNECTION FAILURE,  host: 127.0.0.1:11211 -> libmemcached/get.cc:314
Request Method:	GET
Request URL:	http://127.0.0.1:8000/accounts/login/?next=/
Django Version:	1.8.14
Exception Type:	ConnectionError
Exception Value:	
error 3 from memcached_get(:1:django.contrib.sessions.cache): (0x7f6d2801a3e0) CONNECTION FAILURE,  host: 127.0.0.1:11211 -> libmemcached/get.cc:314
Exception Location:	/home/aemal/env/lib/python3.5/site-packages/django/core/cache/backends/memcached.py in get, line 84
Python Executable:	/home/aemal/env/bin/python
Python Version:	3.5.2
Python Path:	
['/home/aemal/env/lib/python3.5/site-packages/git/ext/gitdb',
 '/home/aemal/amcat2/amcat/manage',
 '/home/aemal/amcat2',
 '/home/aemal/amcat',
 '/usr/lib/python35.zip',
 '/usr/lib/python3.5',
 '/usr/lib/python3.5/plat-x86_64-linux-gnu',
 '/usr/lib/python3.5/lib-dynload',
 '/home/aemal/env/lib/python3.5/site-packages',
 '/home/aemal/amcat2',
 '/home/aemal/env/lib/python3.5/site-packages/gitdb/ext/smmap',
 '/home/aemal/amcat2']
Server time:	Sat, 23 Jul 2016 22:30:27 +0200
```

Your help in this regards will be highly appreciated and thanks for bringing the change in readme file.

Sincerely,
Aemal

**Comment by vanatteveldt** [comment]
Just to be sure, you're installing the master version, not the 3.4 release right? This release is in active development so might well fail to work. For production use, I highly recommend using release 3.4 until we release 3.5 (hopefully after the summer). 

The error seems to indicate that you need to install memcache, i.e. `sudo apt-get install memcached`. Does that help?

**Comment by aemal** [comment]
Thanks! That solved the issue. I am now installing 3.4 as per your instruction in another issue, but face the following error on executing "python -m amcat.manage syncdb":

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/aemal/amcat34/amcat/manage/__main__.py", line 21, in <module>
    from amcat.tools import initialize
  File "amcat/tools/initialize.py", line 31, in <module>
    from django.db.models.signals import post_syncdb
ImportError: cannot import name post_syncdb
```

Please forgive my ignorance if it is a simple fix, I am a newbie in python.

Sincerely,
Aemal

**Comment by aemal** [comment]
and which python (2.7 or 3) is used for this branch:

https://github.com/amcat/amcat/blob/release-3.4/README.md

**Comment by vanatteveldt** [comment]
2.7, we switched to python3 for the 3.5 build. 

I've added the targeted versions to the readme: https://github.com/amcat/amcat/commit/be4dfc51c6e184ee20b71038698435b23054e80b

About your other issue:
```
  File "/home/aemal/amcat34/amcat/manage/__main__.py", line 21, in <module>
    from amcat.tools import initialize
  File "amcat/tools/initialize.py", line 31, in <module>
    from django.db.models.signals import post_syncdb
```

The first comes from /gome/aemal/amcat34, the second from amcat/tools, are you sure that you're running stuff from the right place?

I would advise to do something like

```
. /path/to/env/bin/activate
cd /home/aemal/amcat34
PYTHONPATH=. python -m amcat.manage syncdb
```

**Comment by aemal** [comment]
Thanks a heap for your swift support and for updating the readme file with targeted versions. Yes I managed to fix the syncdb. 

Regards,

**Comment by vanatteveldt** [comment]
Excellent. Let me know (chat/email/issue) if you run into any problems!
