### ISSUE TITLE
Deduplicating problem

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#551]
I am trying to deduplicate an articleset with articles from LexisNexis. The articles I am trying to remove from the set seem to be perfect duplicates, except for the time posted:

![duplicatesdate](https://cloud.githubusercontent.com/assets/6417728/17293342/0a81897e-57f0-11e6-87ed-025bed86d526.png)

However, AmCAT doesn't remove these articles in the deduplicating process, even when I select 'skip date' 

![deduplicate](https://cloud.githubusercontent.com/assets/6417728/17293503/f3f21dbc-57f0-11e6-8a76-11ebc383dd1f.png)

![deduplicate2](https://cloud.githubusercontent.com/assets/6417728/17293515/019b154a-57f1-11e6-9b84-ab6fc8b8ea75.png)

Does 'skip date' only look at the date in days, not in time? Is it possible to change this and include time in 'skip date' also, or to add 'skip time' or 'skip date and time' as extra options in the deduplicator?

**Comment by vanatteveldt** [comment]
It should skip time as well. Can you give links / article ids of two seeming duplicates?
