### ISSUE TITLE
How to change date format in the lists?

### ISSUE THREAD

**Issue by aemal** [amcat/amcat#552]
Hello!

Can you kindly quickly guide me on how to change the date format in project list?

Sincerely,
Aemal

**Comment by vanatteveldt** [comment]
Hey Aemal,

At the moment there is no user-configurable option to change the date formats, and all dates should follow the international ISO format (1999-12-31T23:59). Do you mean the list at amcat.nl/projects/ ?

-- Wouter

**Comment by aemal** [comment]
Dear Wouter,

I have managed to solve it some how, but still the article upload has lots
of issues. I remember from an old conversation that you are considering a
change in article in next version. Is it so?

Thanks,
Aemal

**Comment by vanatteveldt** [comment]
Yes, indeed, we are working on 3.5, where fields are no longer restricted to the old 'newspaper' fields such as headline and byline; see issue #440. The upload in particular will receive a big overhaul, see #439.

Great to hear that it's working for now, closing this issue
