### ISSUE TITLE
Update query screen for flexible fields

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#553]
3.5 moved to 'flexible fields', i.e. a small set of fixed metadata fields and mostly user-defined fields per article. 

The query screen needs to be updated to reflect this, by determining which fields to use (using `amcates.get_used_properties` and offer these for filtering and aggregating.

Currently, all queries seem to yield 'no results'

**Comment by martijnbastiaan** [comment]
- [ ] Summary
- [ ] Graph / Table
- [ ] Articlelist
- [ ] Association
- [ ] Clustermap
- [ ] Actions

**Comment by martijnbastiaan** [comment]
![screenshot from 2016-10-25 22-46-45](https://cloud.githubusercontent.com/assets/5658854/19703956/24b4d6ee-9b06-11e6-853c-51c5a81627f8.png)

Will be pushed after some more testing!
