### ISSUE TITLE
get used properties for a set

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#554]
To populate dropdowns in e.g. query and upload we need to be able to fetch the used properties per set. There are now two implementations in amcates (https://github.com/amcat/amcat/blob/master/amcat/tools/amcates.py#L444 and down), but the first one seems horribly slow in a production environment even though I thought it would be faster.

get_used_properties2 is faster, but still takes about a second per set, a couple seconds for large setes.

So we might have to cache this per set, and invalidate the cache on adding articles to/from a set. I guess this should be fairly easy with memcache. I also think this should be done on articleset as a "wrapper" around the raw queries from amcates, iow I don't think amcates should contain the caching logic. 

@martijnbastiaan @CJStuart  agree?

(edit: the old get_used_properties even causes a java heap space problem, so I'll ditch that and just rename the alternative implementation)

**Comment by martijnbastiaan** [comment]
I also think it makes sense to put he caching logic on Articleset, not in amcates. On adding articles the cache can simply be updated, on deleting articles it should be recalculated altogether. I think we can do this without bothering the user :). I'll put up a proposal soon.

**Comment by martijnbastiaan** [comment]
I've written an implementation over here https://github.com/amcat/amcat/commit/43ce2e00d3489b913e42cb60578434254d163e91. @vanatteveldt could you please check the performance of this on large datasets? It's written for postgres, which can do one pass over the articles instead of n for elastic.

**Comment by martijnbastiaan** [comment]
Oh: I've switched our cache to Redis instead of memcached. It's a dropin replacement for us and is better in every way: http://stackoverflow.com/questions/10558465/memcached-vs-redis. Most importantly, it supports various datatypes including sets which I use in the code.

**Comment by vanatteveldt** [comment]
Some experimentation showed that postgres is simply too slow on larger sets, taking >30 seconds while elastic takes around 1-2 seconds (when 'burned in', 15 seconds from cold start)

so, it seems best to keep the new caching, but use the old get_user_properties call

**Comment by martijnbastiaan** [comment]
Everything is on elastic now. To warm up the cache run:

```bash
env/bin/python -m amcat.manage cache_article_properties --parallel 4
```

You can omit the parallel part and it will choose `multiprocessing.cpu_count()` threads.

**Comment by martijnbastiaan** [comment]
FYI: it took 40 minutes to warm all caches on dev. Even though the code invokes many threads the indexing did not seem I/O nor CPU bound. I'm not sure what's happening, but I assume parallelism does not really work if there are not that many elastic instances. (?)

**Comment by vanatteveldt** [comment]
FYI terug :). The elastic on dev does not actually have multiple nodes, and is probably underpowered in any case...
