### ISSUE TITLE
plugins in query screen (R and/or python)

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#556]
The output / script options in the query screen are delegated to script objects, making it easy to allow plugins to be added so users (with server access?) can add analyses. 
- config points to a folder in which .py and/or .r files are located
- .r plugins are interpreted through a generic python class that extracts arguments etc.
- all plugins are added to an extra dropdown in the query screen
- optionally, plugins can be activated in project settings, that would also help the upload screen

~~If plugins are activated through project settings, the folder contents can be read on opening the settings screen. Otherwise, some sort of sync-to-cache might be needed.~~

Plugins are activated per project through project settings (both query plugins and upload plugins). When a user goes to plugin management the list of plugins can be retrieved from disk, so we don't really need the database anymore. Built-in query/upload plugins (summary, table / csv, plain text, lexis) can be hard-coded in the HTML or views as needed. 

@martijnbastiaan: `templates/project/query/scripts.html` staan de scripts gespecificeerd
Waarbij de naam simpelweg `BlaatScript.__name__.lower()` is

**Comment by vanatteveldt** [comment]
(from email dd 2016-10-28)

Ik heb een suffe R plugin gemaakt die een soort hello world dansje doet. Kasper had al e.e.a. gedaan om forms te parsen, dus nu maak je een r plugin zoals https://github.com/amcat/amcat/blob/a01f60ba200b8d410dfcfd03395fdb23c2ef439e/amcat/scripts/query/r_plugins/demo_plugin1.r

De python RAction (https://github.com/amcat/amcat/blob/a01f60ba200b8d410dfcfd03395fdb23c2ef439e/amcat/scripts/query/test.py) parset vervolgens met een R call dat formulier in de @property form_class, en in de run() roept hij R aan met het ingevulde formulier. Dat lijkt wel goed te werken voor de test plugin. 

Punten van aandacht / bespreking:

- om amcat data te krijgen moet er ofwel een auth token meegeleverd worden voor die user, of de RAction moet als root de API aanspreken. Ik heb voorkeur voor de eerste, volgens mij is dat ook heel makkelijk?

- ik return nu een suffe string, maar we willen vast (ook?) tabellen etc kunnen meesturen. Wat is daar een goede interface voor? gewoon de huidige tabel json namaken?

- willen we nog dingen cachen, bv de form fields? Voordeel van "nee" is (behalve minder complexiteit)  dat je eventueel per project andere fields kan per project...

- hoe gaan we dit dynamisch maken? mijn voorstel was om plugins per project te doen, en bij de 'manage plugins' pagina een directory te monitoren?

**Comment by martijnbastiaan** [comment]
I've cleaned up the existing test code. It should be production ready now (*knock on wood*).

> om amcat data te krijgen moet er ofwel een auth token meegeleverd worden voor die user, of de RAction moet als root de API aanspreken. Ik heb voorkeur voor de eerste, volgens mij is dat ook heel makkelijk?

R plugins will now receive an argument 'api_token' which they can use to access the API. It is immediately removed after the scripts finishes executing (or in the worst case 48 hours).

> ik return nu een suffe string, maar we willen vast (ook?) tabellen etc kunnen meesturen. Wat is daar een goede interface voor? gewoon de huidige tabel json namaken?

Similar to normal plugins, I think this is the R-scripts's responsibility. 

> willen we nog dingen cachen, bv de form fields? Voordeel van "nee" is (behalve minder complexiteit) dat je eventueel per project andere fields kan per project...

We'll cache as soon as the performance gets bad :^).

> hoe gaan we dit dynamisch maken? mijn voorstel was om plugins per project te doen, 

I've added a column to the project table to enable/disable (disable is default) R plugins entirely. (I do realize this is not what you were proposing.) We should only enable it on "our" projects so we can test R plugins and see if this is the implementation we want. If we're happy with it we can remove the column / move to a more sophisticated dynamic system in AmCAT 3.6.

> en bij de 'manage plugins' pagina een directory te monitoren?

Right now, `~/amcat_r_plugins` and the system directory are scanned at startup.

**Comment by martijnbastiaan** [comment]
I'm closing this issue for 3.5. We should test if the existing code (w.r.t. input / output) is what we want and then implement your additional suggestions for 3.6.
