### ISSUE TITLE
Query rules: specific word combination within proximity search

### ISSUE THREAD

**Issue by joepschaper** [amcat/amcat#557]
I would like to run a search string with a specific two word combination within a proximity search:

"("sans emploi*") (immigr* OR migr* OR refugie*)"~15

I know this is not possible under the given query rules, but this would be really helpful. Is there any chance this will be possible in the future?

Thanks!

Joep

**Comment by vanatteveldt** [comment]
I don't think this is possible with lucene / elasticsearch. The closest you can get is:

```
"sans emploi" AND "sans emploi (immigr OR migr* OR refugie*)"~15
```

(which is pretty close I think)

**Comment by joepschaper** [comment]
That's a good work around, I was thinking too much inside the box..
