### ISSUE TITLE
Switch from Travis to Semaphore

### ISSUE THREAD

**Issue by martijnbastiaan** [amcat/amcat#558]
In my experience Semaphore is:
- Way faster (both in terms of building and navigating the UI)
- Easier to debug (breakpoints / SSH)
- Easier to use

It's free for OSS and it shouldn't take too long to switch, as both Travis and Semaphore are running 14.04.

**Comment by martijnbastiaan** [comment]
Link: https://semaphoreci.com/

**Comment by vanatteveldt** [comment]
(closing due to inaction)
