### ISSUE TITLE
'Use in another project' of project 19470 crashes 

### ISSUE THREAD

**Issue by timvandijk92** [amcat/amcat#559]
Whenever I try to use the 'use in another project' function of article set 19470 the browser crashes. Sometimes it reaches the page where you select the target project, but crashes when I try to select one.  

URL: https://amcat.nl/navigator/projects/683/articlesets/19470/import/

**Comment by CJStuart** [comment]
It should be working now.

**Comment by timvandijk92** [comment]
Many thanks!
