### ISSUE TITLE
Can's upload Danish LexisNexis articles for the month May

### ISSUE THREAD

**Issue by joepschaper** [amcat/amcat#561]
Hi Martijn and Wouter,

I can't seem to be able to upload Danish LexisNexis articles (newspaper 'Politiken') for the month of May. Any other month is no problem, but May stays empty. Maybe because May is 'Maj' in Danish?
[Politiken_&_Politiken_Weekly2016-11-21_15-11.TXT](https://github.com/amcat/amcat/files/603798/Politiken_._Politiken_Weekly2016-11-21_15-11.TXT)

I hope you can fix this!

Best,

Joep

**Comment by martijnbastiaan** [comment]
Are you using amcat.nl or dev.amcat.nl?

**Comment by joepschaper** [comment]
Amcat.nl

**Comment by martijnbastiaan** [comment]
As a temporary workaround: maybe you can replace the word 'Maj' with 'May' with your favourite text editor? If you can't find a suitable editor I suggest Notepad++.

**Comment by joepschaper** [comment]
It should be possible, but it's a lot of data and i don't know what other words i mess up.
