### ISSUE TITLE
Flexible fields in ArticleSet API

### ISSUE THREAD

**Issue by martijnbastiaan** [amcat/amcat#565]
I have fixed the article api to include flexible properties in https://github.com/amcat/amcat/commit/5896d0d08401cf5b9ed2cc5f45cab61375b64de8. The API is the same as before, although the properties field is treated differently. All given fields which are not static fields (text, date, etc.) will end up in properties. Two questions:

* If you GET an article, should the flexible properties be in a 'properties' dict or should it be merged with the rest of the fields?

* If we choose to:
  * not return properties but a flat dict, should we disallow uploading with a properties dict?
  * return a properties dict, should we allow uploading using a flat dict?

PS: I removed the children code. You are now ought to provide a parent_hash which you can calculate locally. We should look into providing this as a standalone library for R/Python/etc.

**Comment by vanatteveldt** [comment]
Decision: flat-in, flat-out: the API should accept POSTS with flexible fields side-by-side with the static meta fields, and GET should get a flat dict

**Comment by vanatteveldt** [comment]
(closing due to inaction)
