### ISSUE TITLE
Deploying AmCAT is cumbersome 

### ISSUE THREAD

**Issue by martijnbastiaan** [amcat/amcat#568]
(Stub)

**Comment by martijnbastiaan** [comment]
See branch https://github.com/amcat/amcat/tree/feature-easy-deployment.

- [X] No inline elastic scripts
- [X] External config files
- [X] Setup scripts
  - [X] nginx
  - [X] elastic
  - [X] postgres
  - [X] letsencrypt
  - [ ] Proper CLI
- [ ] {Docker,Debian} packages

**Comment by PaulHuygen** [comment]
Concerning Docker, I am trying to make a Docker-container and a 
Dockerfile to build it, but it is not ready yet. Moreover, there is 
https://github.com/cogfor/amcat-docker.

Cheers.

Paul

Op 04-01-17 om 14:34 schreef Martijn Bastiaan:

**Comment by martijnbastiaan** [comment]
Really nice! Thanks!

**Comment by vanatteveldt** [comment]
(closing due to inaction)
