### ISSUE TITLE
Dynamic fields in summary

### ISSUE THREAD

**Issue by martijnbastiaan** [amcat/amcat#570]
It would be nice if we could select fields to display in the summary. For example, some users might be interested in the origin of a certain article:

![schermafdruk van 2017-01-11 15-06-22](https://cloud.githubusercontent.com/assets/5658854/21851503/9aa5e046-d80f-11e6-9a58-d985fb6f2463.png)

**Comment by vanatteveldt** [comment]
fixed, right?
