### ISSUE TITLE
ESQuerySet.highlight() should return more useful markers

### ISSUE THREAD

**Issue by martijnbastiaan** [amcat/amcat#573]
Right now the query:

```python
qs = ESQuerySet(ArticleSet.objects.all())
qs.highlight("vvd").highlight("cda")
```

would return a string such as:

```html
De <mark0>vvd</mark0> vind dat het <mark1>cda</mark1> lief kijkt
```

It would be great if it could use data attributes instead. An example mark tag could then look like:

```html
<mark data-id="1" data-query-label="vvd" data-query="vvd AND rutte">
```

Although not all information is there yet [this function](https://github.com/amcat/amcat/blob/master/amcat/tools/amcates_queryset.py#L73) is perfectly suited to do this.

**Comment by vanatteveldt** [comment]
(closing due to inaction)
