### ISSUE TITLE
Upload error: over 50 new medium id's created

### ISSUE THREAD

**Issue by joepschaper** [amcat/amcat#578]
Hi Martijn,

I downloaded Politiken (Danish newspaper) articles from lexisnexis and uploaded them to AmCAT. After uploading I found out that in some cases the first paragraph of the article was at the place where the medium should be in the text-files. Now AmCAT created over 50 new medium ID's, I'm sorry. It's medium 989907703 through 989907740, and some lose medium ID's (basically all medium id's of article set 34114, excluding 317 and 318. Could you remove the medium ID's? Of maybe delete article set 34114 all together, so that I'll polish the text files before I re-upload the whole thing.

Best and apologies,

Joep

**Comment by martijnbastiaan** [comment]
There's no need to delete them if it doesn't bother you, AmCAT can handle it :-). If it does bother you, I would happily remove them for you. Let me know!

Also: could you send me the files through email so I can have a look at them?
