### ISSUE TITLE
Flexible fields: allowing non-indexed field types

### ISSUE THREAD

**Issue by kasperwelbers** [amcat/amcat#579]
The flexible field upload currently has as default that each field in the input data (from here on: input-field) is given a field in AmCAT (amcat-field). In most cases this is brilliant (and not to forget; really cool). However, with certain data it can lead to a huge number of fields. I personally had the joy of working through 100+ bogus fields from LexisNexis, when it dawned that we might need to think about how to deal with this elegantly.

If I'm right, then currently ignoring fields is only possible by dropping the input-fields altogether. However, I often would want to keep the data. Previously I often put such data in the metastring. A similar solution would be nice to have here as well. Since we already have flexible fields, it seems that the most convenient solution would be to have a non-indexed field type that would: a) not be searchable and b) not pop up as an option in the query screen (e.g. aggregating axes). This should ease-up navigation and in some cases safe some indexing for elastic.
 
Given a non-indexed field type (or alternative solution), it might then be better to not index every input-field by default. For instance, fields with a vast majority of empty values are probably better left non-indexed (in particular if these are nonsense fields, as you can get from e.g. LexisNexis). 

Any thoughts?

**Comment by vanatteveldt** [comment]
(closing due to inaction)
