### ISSUE TITLE
Changing field type after uploading

### ISSUE THREAD

**Issue by kasperwelbers** [amcat/amcat#580]
I would like to make a case for enabling users to change a field's type after uploading. The reason is that I fear people could end up uploading stuff multiple times if they have the 'wrong' field type for what they want to do. 

This is assuming that field types would currently determine things such as aggregation, which I cannot verify at the moment. The most important case is tag versus text. I assume it should be impossible to select a text field for aggregation (in Graph/Table), but possible to use a tag field. I bet a bottle of wine that people would often select the text field type when they would have wanted tags. Another possible case is integer (ratio) versus tag (ordinal/nominal). 

Being able to toggle field types would also be convenient (necessary?) if there is a non-indexed field type (#579).

**Comment by vanatteveldt** [comment]
I don't really think this is possible in elastic, and would involve re-indexing the data in any case. So closing for now, people need to think before they upload, or just reupload later.
