### ISSUE TITLE
Upload button to import/migrate articles [also offering gradual migration path]

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#581]
Add a button to import data from another amcat server. 

"import articles" is an 'upload script' that allows you to import a single articleset from a different server, checking whether the article is already known (based on uuid and/or hash?) , and handling articles from 3.4 as well as .5

"import project" would be a special button that would copy a whole project, including coding jobs, saved queries etc. This could be either a one-off button to copy from existing amcat.nl to a new 3.5 server (see below), or a general button that retrieves information from any AmCAT server from its API. If we add a special API endpoint "project backup" (which would presumably run as a background job) this would also facilitate people downloading all information from their projects.

IF the "import project" button works we can use it to do a more gradual migration of amcat to 3.5, copying manually all the "big" projects (2, 13, etc), and maybe automatically copying all projects with recent logins, and then leaving it up to users to copy their projects. This would probably allow us to retire a large chunk of the data. 

@CJStuart can you start with/on the import articles button?
(cc @martijnbastiaan @kasperwelbers )

**Comment by CJStuart** [comment]
I added a script and a formview for it. It can be found at 'Add Article Set' -> 'Import from other AmCAT instance' . I also added a view at /request_token, which serves to let users provide access to an  AmCAT client via the navigator. The view is a simple button that requests an API token from the server, and redirects the user back to the form, where the token is filled in automatically.

I backported the request_token view to 3.4.
