### ISSUE TITLE
read write metainfo from sets 2 and 2221 from (for example) 704

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#587]
An old problem is how to see and export the content of articles/items included in sets 2 and 2221. Both sets are included in set 704 (Justifications of (counter)terrorism. Users 'jan' and 'hafsa' both have admin rights in 704, and both have 'read' rights in set 2, Dutch newspapers (I did not checq 2221, tv news).

Nevertheless articles do not pop up, for example after clicking on the dots in a cluster diagram (venn diagram).

(From #588) A reason why export does not succeed is presumably that 'Hafsa' and 'Jan' are 'readers' rather than 'reader-writers' in 2 (and presumably 2221) (although both are 'admin' in 704) ?

**Comment by vanatteveldt** [comment]
I don't think I understand the question. You can export article metadata by choosing the "article list" output option in the query screen. Does that not work? 
(or you can use amcat.articles from R, that should yield the same results)

If that's not the question, can you describe exactly what goes wrong, or include a screenshot of where you expected something to pop up?

For permissions: if you have read access to a project you have read access to all sets within that project, so the access in project 2 should not matter.

**Comment by Kleinnijenhuis** [comment]
Ha Wouter,
Hafsa, en ook ik, zijn in 2 en 2221 inderdaad slechts lezers. Is dat dan een mogelijke reden waarom  Hafsa in 704 verhinderd wordt om een export naar een csv-besand met text als kolom uit te voeren? Dat zou me verbazen omdat ik vanuit 2 heel goed zulke csv-bestanden kan uitschrijven. Ik zal haar ook nog vragen een screenshot toe te sturen.
Hartelijke groet, Jan

Van: Wouter van Atteveldt [notifications@github.com]
Verzonden: dinsdag 25 april 2017 13:10
Aan: amcat/amcat
CC: Kleinnijenhuis, J.; Author
Onderwerp: Re: [amcat/amcat] read write metainfo from sets 2 and 2221 from (for example) 704 (#587)


I don't think I understand the question. You can export article metadata by choosing the "article list" output option in the query screen. Does that not work?
(or you can use amcat.articles from R, that should yield the same results)

If that's not the question, can you describe exactly what goes wrong, or include a screenshot of where you expected something to pop up?

For permissions: if you have read access to a project you have read access to all sets within that project, so the access in project 2 should not matter.

**Comment by vanatteveldt** [comment]
Is dit nog actueel?
