### ISSUE TITLE
quary articlelist with kwic appears to work, but export csv or xlsx fails

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#590]
project 1006, set 35545 queary "Oekraine", Articlelist KeyWord In Context appears to work, but export the results fails, both as csv and as excel (issue aangemaakt omdat ik door Ilse Ploegmaker gesignaleerd probleem kon reproduceren, export met extra's zoals text, page en length lukt wel.

![site niet bereikbaar](https://cloud.githubusercontent.com/assets/6690321/25405013/1f2a220c-2a02-11e7-8ed2-34901e1876bf.PNG)
![1006 unable](https://cloud.githubusercontent.com/assets/6690321/25405022/2614e3ae-2a02-11e7-9ea1-f947b008ca90.png)

**Comment by CJStuart** [comment]
The problem seems to occur when trying to export the following article with the KWIC field enabled: https://amcat.nl/navigator/projects/1006/articles/155437830/. The query `Oekraïne NOT id:155437830` does work.

The article has a missing headline, I think the exporter doesn't handle that properly. I'll look into it.

**Comment by Kleinnijenhuis** [comment]
Ha Christian,
dank voor het vinden van de fout en je bereidheid een oplossing te zoeken. Dit soort onbenullige foutjes betekent voor sommige studenten dat ze zomaar anderhalve week verspelen.
Hartelijke groet, Jan

prof. dr. Jan Kleinnijenhuis
Vrije Universiteit Amsterdam
      Department of Communication Science
De Boelelaan 1081
1081 HV Amsterdam
tel. ++ 31 20 598 6854 (secr.) 6827 (direct)
________________________________
Van: Christian [notifications@github.com]
Verzonden: vrijdag 16 juni 2017 16:13
Aan: amcat/amcat
CC: Kleinnijenhuis, J.; Author
Onderwerp: Re: [amcat/amcat] quary articlelist with kwic appears to work, but export csv or xlsx fails (#590)


Closed #590<https://github.com/amcat/amcat/issues/590> via 7a4214d<https://github.com/amcat/amcat/commit/7a4214d644e7e96b64b2655b75bc3784b67ae7b9>.
