### ISSUE TITLE
Error uploading articles Danish newspaper

### ISSUE THREAD

**Issue by joepschaper** [amcat/amcat#591]
Hi AmCAT developers,

I'm trying to upload lexisnexis articles from the Danish newspaper Politiken to my AmCAT docker, but it seems to not understand a bunch of fields (see screenshot 1). It gives me the option of matching the text to the right fields in AmCAT but that is not sufficient for 2 reasons: 1) not all fields are optional, for instance 'medium', and 2) most of the corrupted fields are one word from a headline that is separated from the rest of the headline by a colon (as journalist often do, for instance when a header is a quote). There is no option to say to amcat that it is not a separate field, but part of the headline. 

I also tried to upload the same set of articles to normal amcat (without the docker). I don't get the errors I get when I download it on the docker page, but it reads the headlines as 'no headline found!'.

I tried to set all the corrupted fields on '(don't use)', but that doesn't help, I get redirected to the same page. 

![screenshot1](https://cloud.githubusercontent.com/assets/6523565/25431666/d0acf962-2a81-11e7-89b3-1d04fb4cf170.jpg)
![screenshot2](https://cloud.githubusercontent.com/assets/6523565/25431667/d0ad6a46-2a81-11e7-812b-99033cd61619.jpg)

Best,

Joep

**Comment by joepschaper** [comment]
Here's one more screenshot with the right settings for the top fields.
![screenshot3](https://cloud.githubusercontent.com/assets/6523565/25432398/8fa63c28-2a84-11e7-9bae-7c623edc3095.jpg)

**Comment by martijnbastiaan** [comment]
@CJStuart I believe you wrote the uploader? Please reassign if not.

**Comment by kasperwelbers** [comment]
I might have a partial solution for one part of the problem.

It's pretty much impossible to parse lexisnexis perfectly, because it does a terrible job at specifying what the meta fields are. I'm currently also uploading a wide range of international media (locally), for which I had to make some changes to the parser. This fixes some of the bugs in the required fields.  I was planning on pushing this after I was done with all the batches to make sure the changes were well tested, but given that the topic came up I pushed it just now anyway. 

Even with these updates there is a LOT of junk. I've had plenty cases where there were about 100 junk fields in a batch of 20,000 docs. Ideally, we'd have a selection of valid fields and the rest would be ignored. This is tricky, however, because lexisnexis sometimes uses different languages for meta field names. 

I also encountered a related performance problem with the lexisnexis uploader, but i'll post that as a separate issue.

**Comment by kasperwelbers** [comment]
Abort. Travis wasn't happy with the changes to the lexisnexis uploader, but I currently don't have time to check this so I undid the commit

**Comment by CJStuart** [comment]
One of those Travis errors was my fault, I reverted the commit that caused it.

**Comment by joepschaper** [comment]
Thanks Kasper and Christian, for weighing in. I was able to upload the
articles to amcat.nl (site without docker), but it seems like it just
didn't upload the articles that caused conflicting fields errors when
uploading it locally (using the docker). Without the 'new' upload I
wouldn't even know about this, if this is correct. It gives over 1000 junk
articles of 30,000 articles total. I'll attach the batch I'm trying to
upload. ​
 POL 4.zip
<https://drive.google.com/file/d/0B5pKLUqFuZ7BY3VnTlVFa3VJQnc/view?usp=drive_web>
​

**Comment by joepschaper** [comment]
Where does that leave us? Is there anything I can do to help? If it is possible to identify the 1000 "junk" articles and manually assign the fields I'm happy to put in the work, but right now it looks I can't even upload the batch without the junk articles to the docker site and with normal Amcat (which I think ignores the junk articles - which are actually relevant) I can't run my search strings, because they're too long. What do you recommend?

**Comment by joepschaper** [comment]
Here's a small update with my latest experience uploading Danish articles to the AmCAT docker site:

Now I can login again I gave the Politiken upload another shot, but it doesn't seem to matter which destination field I select for all the fields (my best bet was 'text' for 'text' and 'date' for 'date' etc., and the rest '(don't use)') that AmCAT cannot specify itself, it just doesn't upload. A few fields (40 out of over 1000) give a clear error, because the word has the letter Ø in it. Even if I select '(don't use)' it gives this error. 

So the problem can be caused by two things:

1) The articles with the Ø that AmCAT can't seem to ignore
And/or
2) Specifying the destinations manually doesn't work (probably this also has to do with special characters like ö.

Is there a way for AmCAT to ignore special characters, or convert them to the closed normal letter? Or is the problem more complex?

**Comment by joepschaper** [comment]
Another update: the problem seems to be easier than I thought.

AmCAT has trouble with headlines that start with a word followed by a colon, such as: "Kronik: Farvel til den barmhjertige samaritaner". This makes AmCAT to ask you to assign the field. So if it's possible to ask AmCAT to ignore the colons between the date and the byline the problem might be solved. The extra error ("Invalid property name") occurs when the first word of the headline contains a special symbol AND is followed by a colon, like: "DÆMONISERING: Værdikamp koster de svageste dyrt". Apart from this AmCAT seems to handle the special symbols quite well!

Joep

**Comment by CJStuart** [comment]
I had some success by running a python3 script that replaces all titles that use the format `<TOPIC>: <HEADLINE>` with `TITLE: <TOPIC>: <HEADLINE>`. This way the parser correctly recognises them as titles, rather than metadata fields with the field name `<TOPIC>`. I can't guarantee that it works in all cases, but for this set of articles it seems to work. 

[This](https://gist.github.com/CJStuart/a852632bb038492c6bdf141b5c2cbaa3) is the script I used. 

I ran the script on all article files in the POL 4.zip file: https://drive.google.com/open?id=0B3gCmcpJdTYJdDJNSi1UTHl1OFU

**Comment by joepschaper** [comment]
Thank you, Christian. I tried to upload the file you prepared and the good news is that it seems to have worked! I checked a few articles that gave an error before your intervention and they are uploaded. The only problem is: only the headlines are uploaded, not the texts. Do you know what is going on there?

Best,

Joep

**Comment by joepschaper** [comment]
Wait, I seem to have made a mistake allocating the fields. It seems to work now. Please don't close the issue yet. I would like to give the set a thorough check first, the coming days.

**Comment by joepschaper** [comment]
It worked! Thank you so much for your help, Christian. I'm good to go with my project and the docker website.

Joep

**Comment by joepschaper** [comment]
Hi Christian,

I just downloaded a new batch of articles of the Danish newspaper and tried
to run your script for the parser, but unsuccessfully. Maybe I don't run it
correctly, maybe it's because I'm using python 2.7. I made an empty folder
and put a test file in it, renamed '1.txt', together with addtitletags.py.
After that, I ran the following script in my terminal: python3
/home/joep/Desktop/lndata/Joep/pol_test/addtitletags.py
/home/joep/Desktop/lndata/Joep/pol_test/1.txt

It didn't give an error, the terminal gave the following output:

processing 1 files...
1 of 1
1 of 1
1 of 1
1 of 1
1 of 1
1 of 1
1 of 1
1 of 1
1 of 1
1 of 1
1 of 1
1 of 1
1 of 1
1 of 1
1 of 1
1 of 1

The file remained unchanged and I didn't see a new improved file. Do you
have an idea what I'm doing wrong?

Thanks!

Joep
.

**Comment by CJStuart** [comment]
Hi Joep,

By default it places the processed text in the directory `out/`, relative to your current working directory. 

I updated the script so that it only processes the file once, rather than 16 times, and so that it also prints the exact target directory. 

- Christian

**Comment by joepschaper** [comment]
Hi Christian,

Sorry, I'm experiencing the same problem again, but this time the add title tags procedure doesn't seem to work. It does process the files and puts new files in my output trajectory, but the txt files don't seem to have changed and when I try uploading them I get the same error as before, asking me to specify fields and having trouble with special signs like ö. Could you have a look into what is going wrong? I attach a zip-file of the lexisnexis batch I try to upload. I also include the python code I'm currently using which worked before. 

I'm actually uploading the same articles to the docker which I used for my project on the 'normal' amcat. I rather just transfer my project from amcat to the docer all together (because I want no discrepancies between the two, I already did analysis using the amcat site). I made an issue about the failing transfer, I believe Wouter made this issue 585, do you know if this is anywhere on the priority list?

Best wishes,

Joep

[DP_3.zip](https://github.com/amcat/amcat/files/1142040/DP_3.zip)

**Comment by vanatteveldt** [comment]
(closing due to inaction)
