### ISSUE TITLE
amcat.gettokens connection error

### ISSUE THREAD

**Issue by thoushallbepwned** [amcat/amcat#593]
Hi everbody, I am using amcat to do an automated discourse analysis as done in Wouter's tutorial.

As such my code is as follows:

library(amcatr)
library(slam)
library(corpustools)

conn = amcat.connect("https://amcat.nl")

sotu.archetype = amcat.gettokens(conn, project= 1392, articleset=35932, module = "corenlp_lemmatize", page_size = 100)

When running the last line in Rstudio it has to process fora  long time 5-10 minutes and then returns the following: 

GET https://amcat.nl/api/v4/projects/1392/articlesets/35932/tokens/?module=corenlp_lemmatize&page_size=100&format=rda&page=1
Error in amcat.getURL(conn, path, page_filters, post = post, post_options,  : 
  Unexpected Response Code 500
This seems to be an AmCAT server error. Please see the server logs or create an issue at http://github.com/amcat/amcat/issues
ConnectionError: ConnectionError(('Connection aborted.', error(104, 'Connection reset by peer'))) caused by: ProtocolError(('Connection aborted.', error(104, 'Connection reset by peer')))

The previous code has worked succesfully in all my other discourses, accessible by changing the article set to: 35930, 35894 or 35892. As some background information what sets apart this particular data set is that it consists of only 2 pdfs, one of which is approximately 1500 pages. 
Any help on how to resolve this issue? 

Thanks!

**Comment by vanatteveldt** [comment]
(response is horribly late, but amcat.gettokens has been removed. You can now use amcat.nlpipe if you want, but it requires you to install nlpipe+corenlp server yourself, which can be done using docker. Feel free to contact me if you need more info, closing the issue for now)
