### ISSUE TITLE
query -> table  fails for metadata fields

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#595]
When running a query -> graph/aggregate -> table aggregating on a custom field it apparently looks for a render function based on the field name:

valuerenderers.js?cache=2017-05-06T19:38:33.897015:40 (line 40) Uncaught Could not find renderer 'medium_str'

If the custom field is numeric, it also fails for the bar/line plot (it runs but gives an empty plot)

![image](https://cloud.githubusercontent.com/assets/1736240/25774704/485b0100-32c7-11e7-8787-0c280797ac9d.png)

**Comment by martijnbastiaan** [comment]
I'm quite sure this has been fixed a while ago by @CJStuart 

https://github.com/amcat/amcat-query-js/blob/master/query/valuerenderers.js

Could you please refresh your bower installation?

**Comment by CJStuart** [comment]
I left this issue open because of:

> If the custom field is numeric, it also fails for the bar/line plot (it runs but gives an empty plot)

This seems to be fixed as well. I'm closing this issue.
