### ISSUE TITLE
Upload CSV bestand

### ISSUE THREAD

**Issue by bvw1** [amcat/amcat#598]
Hi, 

Ik wil graag een CSV bestand met kamervragen uploaden, maar krijg steeds de volgende error. 
![schermafbeelding 2017-05-09 om 16 39 52](https://cloud.githubusercontent.com/assets/28568299/25856418/33abd23c-34d6-11e7-9f0d-22d98d805e0c.png)

de error komt op deze pagina: https://amcat.nl/navigator/projects/1406/tasks/244092/?next=%2Fnavigator%2Fprojects%2F1406%2Farticlesets%2Fupload%2F13%2F 

Voor de error heb ik de volgende gegevens ingevuld: 
![schermafbeelding 2017-05-09 om 16 36 56](https://cloud.githubusercontent.com/assets/28568299/25856471/5ee28f0e-34d6-11e7-8500-d70d3115b429.png)
![schermafbeelding 2017-05-09 om 16 37 25](https://cloud.githubusercontent.com/assets/28568299/25856470/5ee1e2d4-34d6-11e7-8463-c5cfdcb692ca.png)

Het gaat om dit bestand: https://www.dropbox.com/s/qorpglubgobfiwh/PQ0216.csv?dl=0

Ik heb het bestand in verschillende browsers geprobeerd, in verschillende vormen (.xsls) en in verschillende groottes.

**Comment by martijnbastiaan** [comment]
De uploader zou een betere error moeten geven, maar: ik denk niet dat de datum kolom geinterpreteerd kan worden. Voor zover ik kan zien bestaat dit uit de tekst "Vergaderjaar XXXX-YYYY". Zou het een oplossing zijn om deze tekst te vervangen door XXXX-01-01?

**Comment by martijnbastiaan** [comment]
Probeer het eens met [dit bestand](https://www.hmbastiaan.nl/martijn/downloads/PQ0216.csv) (waar ik het bovenstaande heb uitgevoerd).

**Comment by bvw1** [comment]
@martijnbastiaan Dank voor je reactie. Ik krijg nog steeds dezelfde 'Polling failed'

**Comment by bvw1** [comment]
Ik heb het inmiddels ook vanaf een andere computer geprobeerd, maar ook hierbij krijg ik dezelfde melding.

**Comment by vanatteveldt** [comment]
Sorry, I missed this issue earlier. Do you still need this? If so, can you reopen the issue?

**Comment by bvw1** [comment]
No, don't need it. Thanks

2017-08-02 12:54 GMT+02:00 Wouter van Atteveldt <notifications@github.com>:
