### ISSUE TITLE
Can't log in to Amcat docker website

### ISSUE THREAD

**Issue by joepschaper** [amcat/amcat#599]
Dear developers,

I tried to log in to the docker website this morning. My docker is up; I can reach the login page when I go to localhost:8000, but it doesn't recognize my username/password when I try to log in. If I reset my account/recover my password I don't get an email and if I try to make a new account I don't get an email. Is there a malfunction?

The normal site does work with my username/password.

Best,

Joep

**Comment by CJStuart** [comment]
If you're running a local docker server it should be accessible with the default login: 

username: amcat, password: amcat

**Comment by joepschaper** [comment]
Oops, I forgot, thanks!
