### ISSUE TITLE
Coosto upload script only for Dutch

### ISSUE THREAD

**Issue by kasperwelbers** [amcat/amcat#604]
The Coosto upload script only supports Dutch column names. I suppose this makes sense since Coosto is primarily used for Dutch data, but a colleague got the data with English columns despite the data being Dutch. 

Here is a list with the Dutch versus English columnnames, in the order used by Coosto.

1. "zoekopdracht" = "query"   
2. "datum" = "date"   
3. "url" = "url"   
4. "sentiment" = "sentiment"   
5. "type" = "type"
6. "discussielengte" = "discussion length"   
7. "bereik" = "reach"
8. "auteur" = "author"
9. "volgers" = "followers"   
10. "invloed" = "influence"
11. "GPS breedtegraad" = "GPS latitude"
12. "GPS lengtegraad" = "GPS longitude"   
13. "bericht tekst" = "message text"
14. "type bron" = "source"   
15. "titel" = "title"

**Comment by CJStuart** [comment]
Added in 8978987
