### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by Ellisaizenberg** [amcat/amcat#606]
Dear reader,

I was trying to connect to AmCAT through R and this failed. Then I tried to connect through Chrome and I got a warning message stating that the certificate of AmCAT is expired and that it's not safe to continue.

I am now wondering whether it is safe to continue working in AmCAT for the moment and whether this will be solved?

Best regards,

Ellis

**Comment by vanatteveldt** [comment]
Whoops, it seems the https certificate is expired or invalid. @martijnbastiaan I don't have my laptop here, can you have a look?

**Comment by vanatteveldt** [comment]
Fixed by installing and running certbot as per https://certbot.eff.org/#ubuntutrusty-nginx
