### ISSUE TITLE
BZK uploader does not work for specific file (attached)

### ISSUE THREAD

**Issue by martijnbastiaan** [amcat/amcat#607]
(This is a bug report following from an e-mail conversation. I've asked the reporter to subscribe to this issue here.) The following file fails to create any new articles when uploading it using BZK HTML.

[Knipselkrant 16 juni 2017.zip](https://github.com/amcat/amcat/files/1081604/Knipselkrant.16.juni.2017.zip)

@CJStuart Could you look at it? If the issue is still there after the 25th of this month I'll happily fix it.

**Comment by CJStuart** [comment]
It seems to be the section "Opiniebladenoverzicht week 24" that's causing the problem. It's in a different
format than the usual articles. I'm not sure what's supposed to happen to it. Should it be parsed as four separate articles, or as one article with the four articles as text?

**Comment by nruigrok** [comment]
Thanks guys for looking into this issue. Preferably make it separate
articles.
Cheers
Nel

Op 16 jun. 2017 12:39 schreef "Christian" <notifications@github.com>:

**Comment by Jessfi** [comment]
Thanks! I couldn't figure out what the problem was. But I deleted the 'Opiniebladenoverzicht'section and it works. Thanks very much!
