### ISSUE TITLE
Code 500 internal server error

### ISSUE THREAD

**Issue by Oujdia** [amcat/amcat#609]
Hi everyone,

This morning I got an error (Code 500: internal server error). I tried different articlesets and quaries, but nothing seems to help (https://amcat.nl/navigator/projects/2/query/?sets=2#summary AND https://amcat.nl/navigator/projects/2/query/?sets=2#summary AND https://amcat.nl/navigator/projects/10/query/?sets=17864#summary). I refreshed my browser, logged out and even restarted my macbook. Don't know what to do anymore. Can someone help me?:)

One of my queries: 
![image](https://user-images.githubusercontent.com/29662817/27492788-c5ba5baa-5847-11e7-82d6-16ea0f2c96c6.png)

**Comment by vanatteveldt** [comment]
Fixed by restarting rabbitmq. Please reopen if problem still occurs.
