### ISSUE TITLE
Exporteren naar SPSS lukt niet + Internal service ERROR bij zoeken

### ISSUE THREAD

**Issue by Oujdia** [amcat/amcat#610]
Ik probeer 2 articlelists te exporteren naar een SPSS bestand, maar ik krijg hier constant een code 500 error bij. Gaat om articlelists van deze articlesets: https://amcat.nl/navigator/projects/10/query/?sets=17864#articlelist en https://amcat.nl/navigator/projects/10/query/?sets=17870#articlelist

Ik krijg de volgende ERROR: 
{
  "status": 500, 
  "message": "500 : An Error has occurred", 
  "description": "The server encountered an internal error or misconfiguration and\n                     was unable to complete your request.", 
  "details": "PSPPError: PSPP Exited with error: \n\nerror: An I/O error occurred writing system file `/tmp/table-x4wXGZ.sav'.\n", 
  "error": true
}

Hieronder screenshots:
![schermafbeelding 2017-06-23 om 20 59 36](https://user-images.githubusercontent.com/29662817/27496663-3b75f78c-5857-11e7-9a04-f61d29a29de7.png)
![schermafbeelding 2017-06-23 om 20 59 43](https://user-images.githubusercontent.com/29662817/27496664-3df36b0c-5857-11e7-8767-92746b687efe.png)

**Comment by martijnbastiaan** [comment]
Sorry, our server got clogged up. It should now succeed!

**Comment by martijnbastiaan** [comment]
@vanatteveldt Different files keep clogging up /tmp. These are:

* /tmp/lessphp*
* /tmp/delpher_records_*
* /tmp/Rtmp* (directories)
* /tmp/tmp* (with our without html extension)
* /tmp/table-*.sav

The last one is caused by the SPSS exporter, which I will fix. Do you know recognize the others?

**Comment by Oujdia** [comment]
Hi Martijn, I'm still getting the internal server error when I try to search in the articlesets.

**Comment by CJStuart** [comment]
I restarted rabbitmq again, it should be working now.
