### ISSUE TITLE
Tokens

### ISSUE THREAD

**Issue by Ellisaizenberg** [amcat/amcat#611]
Dear reader,

I am trying to extract the tokens from a dataset in AmCAT through R. When I try to do this, however with the following command:

t = amcat.gettokens(conn, project = 1401, articleset = 36507, page_size = 10, module="frog")

It seems as if the program gets stuck at: GET https://amcat.nl/api/v4/projects/1401/articlesets/36507/tokens/?module=frog&page_size=10&format=rda&page=1

Do you have any advice on how to proceed from here?

Many thanks and regards,

Ellis

**Comment by vanatteveldt** [comment]
Tokenizing now goes through nlpipe, see email  / http://github.com/vanatteveldt/nlpipe
