### ISSUE TITLE
upload articles in amcat using csv or xlsx format

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#612]
When uploading a csv-file, a choice of three options to specify the medium is offered: medium name, medium field, and existing medium. I opted for the latter because all items came from "NOS 20:00" (for one reason or another the mediumid 999 of "NOS 20:00" was not visible in this context (see upload1.png). However, amcat gives an error message that it did not see the choice of medium input format that was opted for (see upload2.png). No csv is added to the list of article sets. In case an xlsx is made from the csv-file,, with a column with column header "medium" with 999 in each row, and medium field is specified as "medium"  amcat returns with a polling error. An xlsx with 0 articles is added to the list of article sets, that can't be deleted anymore ....  Unfortunately I cannot paste my data files here.
![upload2](https://user-images.githubusercontent.com/6690321/27888489-8eafaf9a-61e6-11e7-95ca-d47a996ca537.PNG)
![upload1](https://user-images.githubusercontent.com/6690321/27888488-8eaa74a8-61e6-11e7-8e8a-6a0f349b25a6.PNG)

**Comment by Kleinnijenhuis** [comment]
Apparently the second part of this issue is similar to the "polling failed" error messages reported by Eschout in 584 and bvw1 in 598. If "date" may cause the problem, as is suggested by Stuart in reaction to 598 and by Welbers and Stuart in 592, then why is there no prescription of how precisely the date should be formatted?
![upload3](https://user-images.githubusercontent.com/6690321/27889077-63fef662-61ea-11e7-9bd6-4359f5cf287b.PNG)

**Comment by vanatteveldt** [comment]
It seems that the "existing medium" is broken, or at least in some circumstances, but I uploaded the file using R so there is no urgent need to fix the 3.4 uploader
