### ISSUE TITLE
changing codebooks

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#613]
BZK wil zelf de codebooks kunnen veranderen. Toen ik het voordeed kwamen we een aantal zaken tegen die of niet duidelijk zijn of irritant. 

1. Een uitleg ontbreekt helaas ook nog trouwens...

2. Je kunt codes hiden maar wanneer je dat doet komt er een streep doorheen te staan en bij het opnieuw inladen zie je die nog steeds. Dat wordt als irritant gezien. 
Een foutief gemaakte code kan ook niet makkelijk worden verwijderd. 

3. Het verplaatsen van codes is onduidelijk, kregen wij niet voor elkaar.

Als Admin zou het handig zijn als je een codebook kunt wijzigen zoveel je wilt.

**Comment by vanatteveldt** [comment]
ad 1) De "help" knop  bij de codebook editor verwijst toch naar de wiki http://wiki.amcat.nl/3.4:Create_codebooks, waar het  staat uitgelegd? Of bedoel je iets anders?

ad 2) Codes deleten zou nog wel eens gevolgen kunnen hebben voor de annotator. @martijnbastiaan wat denk jij?

ad 3) Verplaatsen kan al met het plus of pijltjes symbolen (|nieuwe parent resp. volgorde): 

```
* Using the crossed arrows you can move the code in a different position within a hierarchical codebook. That is, you can give it a different parent code. Click on the icon first, then click on the code that should be the code's parent.
* Using the arrows you can move the code one position up or down in the codebook. If you want to re-order the entire codebook, use the buttons on top of the screen to the right of 'Download codebook'. Here, you can sort the codebook by alphabet or by code ID (that is, older codes are placed on top of the list).
```

**Comment by vanatteveldt** [comment]
(closing due to inaction)
