### ISSUE TITLE
Uploading articles takes >10 minutes

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#621]
Uploading a file (LN upload script, preview.amcat.nl, default fields selected) takes very long on preview. It seems to get stuck on the checking_deduplicates

<img width="1243" alt="checking duplicates takes long" src="https://user-images.githubusercontent.com/6417728/28745556-ee823f04-747a-11e7-92f3-9923b6060754.png">

I tried this using several of the test files in this folder: https://www.dropbox.com/sh/yojtf2f4o5p7jnl/AACJRMzJHhQEqCP0p_x_iRfla/georgia?dl=0

Even a file containing only 7 articles took over 10 minutes to upload.

**Comment by vanatteveldt** [comment]
Can you check whether this is still the case?
