### ISSUE TITLE
No confirmation when editing project details

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#622]
I added an upload script to the standard settings in project 29 BZK ('Advanced' tab -> 'Project details') and clicked Save

<img width="706" alt="no confirmation" src="https://user-images.githubusercontent.com/6417728/28745585-7050c3a2-747b-11e7-9409-49a46d6b7525.png">

I expected a green box saying 'Project settings successfully changed' or something similar to show up on the top right of the screen to confirm that I changed the project details, but there was no confirmation message. 

The change was made successfully though (the upload screen shows my changed selection of upload scripts) so it is only the confirmation missing that seems to be missing.

**Comment by vanatteveldt** [comment]
(3.5.1  meaning: good idea, but not a bug and not critical before release)
