### ISSUE TITLE
Fields preview doesn't give enough information (in my opinion)

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#623]
I want to upload this file 
https://raw.githubusercontent.com/amcat/amcat/master/amcat/scripts/article_upload/tests/test_files/lexisnexis/test.txt

using the LN uploader. In the screen where I have to select the fields to extract, amcat shows me the following information about what will be in those fields:

<img width="800" alt="preview not enough information" src="https://user-images.githubusercontent.com/6417728/28745757-fac6329e-747e-11e7-8488-20c9dd10b324.png">

I assume that the goal of the preview to the left of the screen is that I can check if each field contains the right information. But amcat shows me only what is in those fields, not what is in the document text right before or after. So for example if you look at the fields date, loaddate and datechargement, they all look like dates, but by the information shown here alone I cannot tell how they are different, or which ones I would like to extract or not. 

Ideally, this page would give a keyword-in-context type of preview (keyword here being the information in each field) for each field instead of only showing examples of the field values themselves. (Please comment if my description isn't clear.) Would that be possible at all?

**Comment by vanatteveldt** [comment]
I think this would be quite difficult to implement, especially in a generic way. In my opinion, the preview is more for getting some idea about the contents than to really debug the upload script. 

I'm closing the issue for now, we can reopen if we think of a good way to do this...
