### ISSUE TITLE
Amcat extracts a lot of fields by default. 

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#624]
I want to upload this file 

https://raw.githubusercontent.com/amcat/amcat/master/amcat/scripts/article_upload/tests/test_files/lexisnexis/test.txt

using the LN upload script. In this page

<img width="805" alt="many fields" src="https://user-images.githubusercontent.com/6417728/28745850-7080f5c6-7481-11e7-9b21-b42552c16985.png">

where I can select the fields to extract, AmCAT suggests >20 fields to extract in addition to the core fields. Some of these fields are unique to particular media (e.g. the date that the article was updated becomes a different field for the French-language newspapers than for the English-language newspapers). 2 questions:

1) Changing to 'don't use' takes 2 clicks per field, so people are probably going to extract all fields AmCAT suggests. Would it save on memory/uploading time if 'don't use' were the default for each of these fields? Or is the intention to gather as much information from each article as possible?

2) Would it be possible to allow users to combine some of the fields that AmCAT suggests and extract them into the same field? So for example, if I want a field that shows the date the article was updated, but AmCAT suggests a separate datechargement field for the French newspapers and dateupdated for British newspapers, that I can extract both of those into one 'date updated' field? I think that AmCAT currently overwrites the first values with those of the second field if you try to do this.

**Comment by vanatteveldt** [comment]
re 1) I think the default behaviour should be to only keep known fields and translate known fields in different languages into English. Now we don't have a full list of fields in all languages so it might be missing for French. Which file did you use to upload?

re 2) That might be possible, simply contatenate two fields if they have the same destination. @CJStuart  what do you think?

**Comment by CJStuart** [comment]
> 2) That might be possible, simply contatenate two fields if they have the same destination. @CJStuart what do you think?

Should be doable, but doing this for the date destination would most likely break the dateparser, unless the combination coincidentally happens to be a readable date. For text fields it makes sense, though. For int, number and date destinations we should only accept one source.

**Comment by vanatteveldt** [comment]
Yeah. I noticed btw that all fields are now (again?) default new field, I think unknown fields for LN should be [don't use] unless the user specifically adds them.

I agree that concatenation is naive. We could use the first valid entry for int, number, date and use concatenate for text?

**Comment by vanatteveldt** [comment]
I'm moving the "let's concatenate multiple fields" to another issue, this issue is just: set unknown lexis fields to don't use
