### ISSUE TITLE
Uploading failure, null value in column date violates non-null constraint

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#625]
I tried uploading this test set 

https://raw.githubusercontent.com/amcat/amcat/master/amcat/scripts/article_upload/tests/test_files/lexisnexis/test.txt

using the Lexis Nexis upload script. For testing reasons, I tried adding the loaddate (at the bottom) to the date field 
<img width="403" alt="2 dates" src="https://user-images.githubusercontent.com/6417728/28745991-1479e438-7484-11e7-9006-57e0cb72face.png">

AmCAT didn't show a warning, but when I uploaded the articles, this failure happened

<img width="1354" alt="null value in date" src="https://user-images.githubusercontent.com/6417728/28746001-334a602c-7484-11e7-9931-df402dc98559.png">

So what I guess happened is that the second date field overwrote the first one, but contained null values, which isn't allowed in a core field? (maybe AmCAT shouldn't allow me to assign date to a different field?)

**Comment by vanatteveldt** [comment]
I'm combining this with #624
