### ISSUE TITLE
Database not properly indexed after migration (was:Article full text doesn't load)

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#626]
I want to access the full text of an article, either from the articleset view
<img width="1110" alt="article does not load" src="https://user-images.githubusercontent.com/6417728/28746050-13fd0020-7485-11e7-8bc9-8d68acaaf145.png">

or from my query results summary (by clicking on the headline from the screen below)
<img width="629" alt="i want to see the full article" src="https://user-images.githubusercontent.com/6417728/28746052-1f15d1f8-7485-11e7-8c08-4634e4ff80d9.png">

but the page just keeps loading, nothing happens 
<img width="1132" alt="page does not load" src="https://user-images.githubusercontent.com/6417728/28746062-3d778e0c-7485-11e7-9136-1abcdc64b43c.png">

**Comment by vanatteveldt** [comment]
I did not reindex all projects yet, so that might be the problem. I'm reindexing project 888 right now, let's see what happens

(you can also refresh individual sets)

**Comment by vanatteveldt** [comment]
No, that wasn't the problem. It hangs on the database trying to run:

```{sql}
SELECT "articles"."article_id", "articles"."project_id", "articles"."date", "articles"."title", "articles"."url", "articles"."text", "articles"."hash", "articles"."parent_hash", "articles"."properties" FROM "articles" WHERE "articles"."parent_hash" = '\xc27e9753bbd1c6ca5634b2ce04d42fd2f68edff0521ce8350e8f03db'::byte
```

It seems that the migration did not properly reindex the articles table, it needs an index at least on parent_hash and a unique index on hash, now it only has an index on the pk.

also, it should not have inserted article ID 4, but a much higher number, so that's also not good
