### ISSUE TITLE
Articles uploaded successfully, but articleset not found on this server

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#627]
I succeeded in uploading some articles

<img width="1104" alt="success" src="https://user-images.githubusercontent.com/6417728/28746085-b1f14c3c-7485-11e7-891d-6f5b3b93caf0.png">

and clicked the 'View Set' button. But instead of viewing the set, I got this

<img width="470" alt="not found" src="https://user-images.githubusercontent.com/6417728/28746099-d458528e-7485-11e7-8475-0661ad4acd70.png">

Did AmCAT let me upload articles into an articleset on a different server? 

Related problem: the list of articlesets to choose from in the dropdown menu under 'Articleset' here 
<img width="1031" alt="uploading" src="https://user-images.githubusercontent.com/6417728/28746128-32a6b4fc-7486-11e7-9fb4-2324ff5af469.png">

is very long and seems to contain all articlesets from every project. Including a lot of different sets named 'test' or 'testset'. So I guess I picked a set named 'testset' that wasn't my test set, and uploaded my articles there (apologies to the owner of that set..). Two things:

1. I don't think AmCAT should allow me to add articles to someone else's set (with no way to see what I did or to undo it)...
2. Is there a way to make the articleset dropdown menu more manageable -- e.g. show only the articlesets in the current project?

**Comment by vanatteveldt** [comment]
I can't reproduce this, is it still happening?

I'm putting the related problem in a different issue
