### ISSUE TITLE
Query failed; server closed the connection unexpectedly

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#629]
I tried to query some articlesets (I selected the articlesets and clicked 'use in query', then left everything in its default settings and clicked 'Query' in the screen below) but instead of showing the search results, AmCAT returned the following error:

<img width="1369" alt="server closed the connection" src="https://user-images.githubusercontent.com/6417728/28753962-382ba430-753c-11e7-900e-5ad430a9387b.png">

**Comment by carinajacobi** [comment]
It's not just the query, uploading also fails with the same error.

@vanatteveldt: Staat de server uit of zo:P?

**Comment by vanatteveldt** [comment]
I made some db changes and restarted the uwsgi worker, but didn't restart celery. For some reason it got out of sync with the db, no idea why. Should be resolved now.
