### ISSUE TITLE
validation fails in annotator for quality field

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#636]
As reported by @jessfi: 
```
Bij intypen verkeerde waarde -4 (ipv 0,0,5,1, -0,5 0f -1) slaat hij het artikel gewoon op. Zou fijn zijn als ie aangeeft dat je iets verkeerds of vergeten bent. Misschien ook bij mediaobject, daar moet altijd wat staan. Staakeholder niet, die is soms echt leeg omdat het hoort.
```

@CJStuart  can you check whether this is the case? Do the other validators work correctly?

(cc @nruigrok)

**Comment by CJStuart** [comment]
According to [annotator/views/codingjob.py#L49-L55](https://github.com/amcat/amcat/blob/c07e729e27a71102c3d7938b8e4b3314b6bbd120/annotator/views/codingjob.py#L49-L55):

    Big fat warning: we don't do server side validation for the codingvalues. We
    do check if the codingjob and logged in user correspond, but it's the users
    responsibilty to send correct data (we don't care!).

Currently the only thing that is preventing users from entering bogus is the html input type.

**Comment by vanatteveldt** [comment]
(closing due to inaction)
