### ISSUE TITLE
How does adding new fields (specifically, length) work when uploading data?

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#638]
I want to upload a file and add more fields, for the author and length of the article. How can I do that? Does the file need to have these fields specified, like 'author: X' , within each document? And the same for length, or does amcat count words? I don't find the explanation 'Type constant value' or 'Optional, adds a property with the same value for each article' very helpful (and I'll gladly help to improve this once I understand it myself).

In any case, just to see what would happen, I tried this

<img width="1013" alt="i do not understand adding fields" src="https://user-images.githubusercontent.com/6417728/28975124-2bcf1cf2-7939-11e7-923e-21c269173745.png">

this doesn't work: no error message, but nothing happens either (for > 10 minutes now).
I guess this is because length_int needs to be an integer, because when I tried adding only that field

<img width="655" alt="ik wil length weten" src="https://user-images.githubusercontent.com/6417728/28975369-076919a2-793a-11e7-9778-906d3bbbbe44.png">

I got this error

<img width="1365" alt="geen string" src="https://user-images.githubusercontent.com/6417728/28975348-fa134944-7939-11e7-8ef7-0f117b950acc.png">

But when I tried adding length as the string 'length' option, amcat added this wonderfully informative new field 
<img width="1017" alt="length" src="https://user-images.githubusercontent.com/6417728/28975424-3b463d04-793a-11e7-997e-10a7b8a89a29.png">

This is also not what I want, I want amcat to count the words of each article. Can I make it do that, and if so, how?

**Comment by vanatteveldt** [comment]
These fields are if you want to add a value that is the same for all articles, e.g. all articles from a file should have the same section or medium. 

The error is because you set length_int (which should be numeric) to the value "length_int", which is not a number. 

I'm leaving this open because we should probably explain / document this better?

**Comment by carinajacobi** [comment]
Yeah, that's what I thought. But strange that the first case (where I tried to extract 3 new fields, of which one caused the error) didn't result in an error message, just amcat stuck on processing/waiting. The error message only appeared when I had only the length_int as a new field.

**Comment by vanatteveldt** [comment]
(closing due to inaction)
