### ISSUE TITLE
Fields specified during uploading are different from the fields in the articleset overview

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#639]
I want to have the following fields in my articleset
<img width="651" alt="fields i want" src="https://user-images.githubusercontent.com/6417728/28975663-26c19616-793b-11e7-9439-f650f0a30d5d.png">

I expected to see these fields in the articleset overview after uploading, so the medium as the leftmost column after id, then the title and then the date and text. But after uploading, the articleset overview shows different fields, including 'URL', which I didn't choose to include, and is empty (so not informative at all)
<img width="1026" alt="fields in overview" src="https://user-images.githubusercontent.com/6417728/28975697-4740632c-793b-11e7-9cdb-b374512fad98.png">

Would it be possible to connect the two somehow, so that the fields you pick when uploading the file are also the ones that are shown in the articleset overview? That would make it easier to confirm whether amcat extracted the right information for each field (which is especially important when adding new fields).

**Comment by vanatteveldt** [comment]
(This ties in a bit with #635 )

I think we should either show all fields in that set (which is something we cache, right?), or the project fields. Maybe instead of project fields just always display all fields relevant for that set?

**Comment by carinajacobi** [comment]
Yeah, I also think all fields relevant for that set would be best. So that if you add more fields in addition to the project fields, you can check whether those fields contain the right information.

**Comment by CJStuart** [comment]
This could become quite  a mess when there are a lot of columns, so I added a setting to projects that allows users to pick some columns that should be shown in articlesets and the annotator. By default all columns are visible.
