### ISSUE TITLE
upload failure, duplicate key

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#640]
I am trying to upload this document: 
https://www.dropbox.com/sh/yojtf2f4o5p7jnl/AACgnKoMpqPIbtYL0nyhJFoLa/iraq?dl=0&preview=Czech+Republic+U.S-+Iraq1.TXT

using these uploader settings:
<img width="973" alt="upload settings" src="https://user-images.githubusercontent.com/6417728/29241245-2d41f968-7f76-11e7-86ad-20edae325dce.png">

using all default values (the standard fields and the extra fields suggested by amcat). This resulted in the following error:
<img width="1023" alt="duplicate key" src="https://user-images.githubusercontent.com/6417728/29241255-5154b70a-7f76-11e7-8f2a-c262b3aa6abd.png">

I went back to see if something was wrong with the fields suggested by amcat, and it seemed that a lot of things were in the wrong place (like 'loaddate' going into the 'text' field:
<img width="768" alt="fields recognized incorrectly" src="https://user-images.githubusercontent.com/6417728/29241262-70c36726-7f76-11e7-861a-142ebf8d7663.png">

So I corrected them:
<img width="723" alt="fields corrected" src="https://user-images.githubusercontent.com/6417728/29241268-79e11b28-7f76-11e7-9403-dde8abf2dcd1.png">

But this didn't help:
<img width="892" alt="again failure duplicate key" src="https://user-images.githubusercontent.com/6417728/29241272-86cdcbec-7f76-11e7-9c0b-b00a70da4f67.png">

I don't know what could be causing this error..

**Comment by carinajacobi** [comment]
It's not just that document that returns the error when I try to upload it, I've tried a few other documents in the test documents dropbox folder and they all seem to cause it. But uploading a Knipselkrant in the BZK project using the BZK HTML uploader does work.

**Comment by vanatteveldt** [comment]
(closing due to inaction)
