### ISSUE TITLE
'Sample' lets you pick a different articleset, but then returns error

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#641]
Minor issue: in the screen where you take a sample from an articleset
<img width="1046" alt="sample" src="https://user-images.githubusercontent.com/6417728/29241346-d6c0b8a2-7f77-11e7-8075-abef2e0bc0c1.png">

you can choose a different articleset than the one you originally wanted to take the sample from (the dropdown menu shows every articleset in every project). This suggests that you can take a sample from any articleset you want, or from a combination of multiple articlesets. However, the menu doesn't let me select more than one articleset. And selecting a different one than the one I originally came from
<img width="685" alt="sample different articleset" src="https://user-images.githubusercontent.com/6417728/29241338-b8b1301c-7f77-11e7-8687-2f475f7eb1c2.png">

Results in an error
<img width="533" alt="sample server error" src="https://user-images.githubusercontent.com/6417728/29241341-bdfc6aa0-7f77-11e7-80b2-9b74646f4815.png">

Wouldn't it be better to remove this dropdown menu altogether, if the only articleset you can take a sample from is the original? Or allow users to select more than one articleset to combine in the sample.

**Comment by CJStuart** [comment]
Fixed in a8d207efedeb6d907c649a853d3747b71c832969
