### ISSUE TITLE
Upload does not work (amcat docker)

### ISSUE THREAD

**Issue by joepschaper** [amcat/amcat#645]
Hi Christian,

I can't seem to upload articles to the docker site anymore. I uploaded a few batches, which worked, but now the site does not accept my zip-files, even though I do nothing differently. When I click 'upload' it takes a while before I get the attached error. I hope you can help.

Best,

Joep
[upload error.txt](https://github.com/amcat/amcat/files/1257294/upload.error.txt)

**Comment by vanatteveldt** [comment]
(closing due to inaction)
