### ISSUE TITLE
Error deduplication (amcat docker)

### ISSUE THREAD

**Issue by joepschaper** [amcat/amcat#646]
Dear Christian,

I have trouble deduplication article sets on the amcat docker site. Enclosed you'll find the error.

Best,

Joep
[error deduplication.txt](https://github.com/amcat/amcat/files/1257317/error.deduplication.txt)

**Comment by CJStuart** [comment]
Hi Joep,

We've updated the amcat docker image to the latest version, which fixes the problems described here and in #645. In order update, please follow the following steps:

First of all, the update script might cause data loss, so it's wise to make a backup. Open the terminal inside the directory where `docker-compose.yml` is located, and run:

```sh
mkdir -p backups
docker-compose up -d
docker-compose exec postgres pg_dump -U postgres amcat > "backups/backup.sql"
```
This dumps the entire contents of the database into `backups/backup.sql`.

To update amcat-docker, I wrote a short script (https://git.io/v518W) that should take care of everything. The easiest way to run it is like this:
```sh
wget -qO - https://git.io/v518W | sh
``` 

Please let me know if you run into any trouble. 

-- Christian

**Comment by joepschaper** [comment]
Hi Christian,

This looks very promising! However, I run into an error updating the docker. For a while the code is running smoothly, but at some point it doesn't seem to be able to find 'amcat'. I tried to run the script again, but it fails. I enclosed the feedback I get from the terminal. Could you have a look?

Best wishes,

Joep

**Comment by CJStuart** [comment]
Hi Joep,
I believe you forgot to enclose the feedback. 

-- Christian

**Comment by joepschaper** [comment]
I see, github didn't support ubuntu's text editor files.

[error update amcat docker1.txt](https://github.com/amcat/amcat/files/1295303/error.update.amcat.docker1.txt)

**Comment by CJStuart** [comment]
This should fix it:
```sh
docker-compose up -d postgres                                                                                                                   
docker exec -i --user postgres $(docker-compose ps -q postgres) sh -c "(until pg_isready; do sleep 1; done)"
docker exec -i --user postgres $(docker-compose ps -q postgres) sh -c "dropdb --if-exists amcat && createdb amcat && psql amcat"  < backups/backup.sql
docker-compose stop && docker-compose rm -f postgres
```

Now `docker-compose up` should run like normal.

**Comment by joepschaper** [comment]
It looks like the steps have worked, but when I run 'docker-compose up' (from the amcat-docker-master directory) I get an error that loops. I'll send you the log and the last part is repeated over and over.

[error docker compose up.txt](https://github.com/amcat/amcat/files/1295517/error.docker.compose.up.txt)

**Comment by CJStuart** [comment]
It looks like Elasticsearch is failing to start because the kernel parameter `vm.max_map_count` is too low.

We can test if this is the case by running:
```sh
sudo sysctl -w vm.max_map_count=262144
```
and running `docker-compose up` again. 

If this works, the changes can be made permanent by editing `/etc/sysctl.conf`:

```sh
sudo gedit /etc/sysctl.conf
```
and adding the following line at the end of the file:
```
vm.max_map_count = 262144
```

**Comment by joepschaper** [comment]
The first part works! And I can upload articles to the docker and the
duplication works. Only permanently editing /etc/sysctl.conf doesn't work.
The first command opens an empty file (with the right name though), and
when I copy past the second line, save, and try to start the docker I run
into the same problem as before. I tried to search for the sysctl file
manually, but can't seem to find it. If it's too much of a hassle to fix
this, I can adapt use the temporary parameter change into in my docker
start routine..

**Comment by joepschaper** [comment]
I uploaded two article sets, but the third gives an error: 

Task started: | Sept. 12, 2017, 2:14 p.m. by amcat
-- | --
Status: | FAILURE
Message: | IndexError: list index out of range

I don't know if this should be a new issue or if this is still part of the docker update?


[Error uploading articles docker.txt](https://github.com/amcat/amcat/files/1295882/Error.uploading.articles.docker.txt)

**Comment by joepschaper** [comment]
I see, the files are too big, if I chuck them in half it works.

**Comment by joepschaper** [comment]
Sorry, I was too quick with that message: I can't upload the other half (even though it is a new article set). Is there a limit on the amount of articles I can upload? And is there a way to get rid of the limit?

**Comment by CJStuart** [comment]
Could you check if there exists an emtpy document in the LexisNexis file, i.e. a line `DOCUMENT <M> OF <N> DOCUMENTS` that is immediately followed by another without any text? If that is the case, then a workaround might be removing it from the file.

**Comment by joepschaper** [comment]
That's it! Thank you for your help.

**Comment by joepschaper** [comment]
Hi Christian,

I'm experiencing the same problem getting the docker up as before, but now adjusting the kernel parameter doesn't seem to do the trick anymore. Could you have a look and see what's going on? I enclosed the log.

Thanks!

Joep

[error docker2.txt](https://github.com/amcat/amcat/files/1306635/error.docker2.txt)

**Comment by joepschaper** [comment]
Sorry, false alarm! I thought I recognized the error, but in the end it worked.

**Comment by vanatteveldt** [comment]
(closing due to inaction)
