### ISSUE TITLE
Error uploading, false character(?)

### ISSUE THREAD

**Issue by joepschaper** [amcat/amcat#647]
Hi Christian,

I try to upload a pretty big article set, but I get an error:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xef in position 16: invalid continuation byte

I think there's a character in the document that is not recognized, but is there any chance to see in which document, what character, or the words before or after, so I can look it up in the document and change/delete it manually? Now I don't know how to find the mistake.

Best wishes,

Joep

**Comment by joepschaper** [comment]
If it helps: The error occurs during the initial upload, before the field assignment.

**Comment by vanatteveldt** [comment]
(closing due to inaction)
