### ISSUE TITLE
Docker: query length limit for article list option

### ISSUE THREAD

**Issue by joepschaper** [amcat/amcat#649]
Hi Christian,

I'm trying to get a list of article id's from a set using a certain search string, but I don't get any results. It seems to work with short search strings, but not with longer ones, although the longer ones do work when using the summary or table option. There's probably still a limit on search strings coded into the articlelist function of the docker. Could you take a look at this?

Best wishes,

Joep

**Comment by vanatteveldt** [comment]
(closing due to inaction)
