### ISSUE TITLE
UI to get token from AmCAT

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#650]
Currently I use username/password to connect to the AmCAT API from python or R clients. This means that people often store their password in the script or somewhere on their hdd. I think it would be better to get a token from AmCAT and store that token. 

For increased security, it would be good to have different tokens:
- read only. This should be the default, as most people will only use the API to extract data from AmCAT
- read+append. This would allow for uploading articles and creating new article sets, but not for any 'destructive' access.
- read+append+manage. This would allow creating new users and projects as well. This is useful for automatic setting up of dedicated servers e.g. for teaching
- full access. Not sure if we even need it?

(Alternatively, we can go full oauth2, but that sounds complicated?)

**Comment by CJStuart** [comment]
Closing this, since a basic implementation is available.
