### ISSUE TITLE
Server-wide settings for registering and anon access

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#651]
Every AmCAT server now allows users to self-register, but that might not be desirable for some servers. So, it would be good to have a server-wide option (presumably in the settings file) that controls whether users can self-register, with a comment that a working email system is required for it to work.

Additionally, a server-wide option to allow anonymous access would also be nice.

**Comment by CJStuart** [comment]
This already is an option in the amcat.ini file. I added some documentation to the to clarify these settings.
