### ISSUE TITLE
Getting articles via the API: flatten fields and enable filtering

### ISSUE THREAD

**Issue by kasperwelbers** [amcat/amcat#655]
We can get articles via the API with:
http://localhost:8000/api/v4/projects/1/articlesets/1/articles/

Currently, there is a separate "properties" field, in which certain fields (e.g., medium, headline) are nested. I think it would be more convenient to flatten this, which is also how it is currently arranged in elastic. At the moment, the data is being flattened in the table renderers (api/rest/tablerenderer.py), but arguably, this shouldn't be necessary in the first place. 

Possibly a related issue is that it no longer seems possible to select specific fields/columns (in previous api versions, the columns= parameter could be used). This is really useful for limiting needless traffic.

**Comment by CJStuart** [comment]
That latter issue was not broken intentionally. Labelling it as bug.
