### ISSUE TITLE
/api/v4/search replaced by /api/v4/query

### ISSUE THREAD

**Issue by kasperwelbers** [amcat/amcat#656]
I was working on the AmCAT R bindings (amcatr), where originally we used /api/v4/search and /api/v4/aggregate for querying and aggregating. However, in the query screen on the website it seems that /api/v4/query is used for searching and aggregating.

Is there a reason that /search and /aggregate are still available? Would it make more sense to use /query in the API bindings?

**Comment by CJStuart** [comment]
It's probably best to use /aggregate. The /query views  schedule tasks via celery, so that would require some polling on the R side, which probably isn't ideal. The /aggregate view just returns the results directly from elastic.
