### ISSUE TITLE
finish&continue works despite required fields not being filled

### ISSUE THREAD

**Issue by sebbelpiet** [amcat/amcat#659]
I want to avoid coders not filling out the whole coding schema before continuing to the next article. This it to avoid that maybe certain variables will be missed while coding. Therefore I want to use the "Required" option in the coding schema. However, although all fields in the articleschema are set to be required it is possible to click finish&continue without having filled out any of the fields.
The problem appears for all codingjobs I tried, all article sets I tried, all coding schemas I tried. For example with this coding job:
https://amcat.nl/annotator/project/1479/codingjob/15107/

**Comment by vanatteveldt** [comment]
@CJStuart , can you have a look at this?

**Comment by CJStuart** [comment]
See #660
