### ISSUE TITLE
Uploading csv file to AmCAT

### ISSUE THREAD

**Issue by travelminded** [amcat/amcat#661]
I would like to run a news text annotation job on AmCAT.

1) Therefore I try to upload the articles. They are in csv file format (columns of interest are: headline, lead_pragraph, text)

 - URL of the page: https://amcat.nl/navigator/projects/1562/articlesets/upload/13/
 - I select the csv file, enter an article set name, a medium name, headline for headline field and lead_paragraph for byline field, and have the encoding and dialect field set as "autodetect"
- Here is a dropbox link, that includes three example files (csv, comma separated) of the kind I plan to upload for coding. It is news text, each file includes text in a different language

https://www.dropbox.com/sh/q0773t2fqqz2f62/AACLVr5RDjmaSekN476TktU6a?dl=0
 
2) The upload fails. The text of the error message  I get is:

  | Polling failed. Refresh?
 
3) Steps I already took to solve the problem, e.g. 
 - test all combinations of encoding and dialect field options
 - rename the file
- test different files 

I would really appreciate your support!:) Any suggestion on file format transformation is also very welcome. Thank you!

**Comment by vanatteveldt** [comment]
Can you share the csv file so we can have a look? Easiest is e.g. a dropbox link, but if the data aren't public, you can also mail them to wouter@vanatteveldt.com

**Comment by travelminded** [comment]
Thank you very much! I just sent an email.

**Comment by vanatteveldt** [comment]
I looked at the BBC file
- You need to specify publication_date for date 
- This field cannot contain any NA or empty values as each document needs a date
- It's also better to specify the encoding manually to 'utf-8', sometimes the automatic doesn't correctly recognize the encoding. 

Hope this helps! If you still run into trouble, feel tree to post here again or create a new issue!
