### ISSUE TITLE
Failure to upload article sets

### ISSUE THREAD

**Issue by bschlipphak** [amcat/amcat#664]
After setting up my first project at AmCAT, I tried to upload LexisNexis txt files via the LexisNexis Uploading Link. After beginning to upload, the Task Manager always gives me the Status: "Polling failed. Refresh?" I did refresh several times, set up alternative projects, used different article sets (with different labelling) and different browsers. The result always stayed the same (see screenshot below)

I will send the article sets I used directly to the administrator of AmCAT as I would otherwise confront copyright problems.

Thanks for helping me,

best, Bernd

![amcat_error](https://user-images.githubusercontent.com/35990945/35611695-246020aa-0666-11e8-8112-263864895645.jpg)

**Comment by vanatteveldt** [comment]
@CJStuart can you have a look at this? I mailed you the input file.

**Comment by CJStuart** [comment]
The parser had some trouble with the German text used in the document headers. I added these to the script, so it should be working now.
