### ISSUE TITLE
duplicates in queries

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#665]
Many articles in the classic databases appear to be duplicates, e.g. in
https://amcat.nl/navigator/projects/2/query/?sets=2#summary
Is there a simple way to deduplicate query results?

Screen shot of search query Turkije turk*
![image](https://user-images.githubusercontent.com/6690321/35653828-41a06f92-06ea-11e8-829a-edf3bdc45aa9.png)

**Comment by vanatteveldt** [comment]
You can deduplicate the underlying set, right? I'm not sure it is useful to add deduplication in the query interface. What is the problem with doing it via the set?

(closing for now, feel free to respond if you disagree)
