### ISSUE TITLE
Filter on article fields in query screen

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#668]
Currently you cannot filter on article fields in the query screen. Medium is still there, but without any options. Ideally every non-text property in the selected set should be included, with different options depending on the property type (dropdown, date picker, value text field). This should probably in the form of [select field] -> [load options through AJAX] and [add field] to avoid populating potentially many different fields with different values.

**Comment by CJStuart** [comment]
Better UI was added in 804dcf207fcd75e8a93d01b27bed7feb47490d48
