### ISSUE TITLE
Lexis Nexis uploader ignores URL for online media

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#672]
I am trying to upload articles from online newspapers downloaded from Lexis Nexis. These are not full text, but include a link to the full text above the date in the txt file

<img width="724" alt="dichte mist txt" src="https://user-images.githubusercontent.com/6417728/38041355-cdcf5f44-32b1-11e8-8270-f02729be9e9b.png">

This link unfortunately gets lost as the article is uploaded in Amcat using the Lexis Nexis uploader, so what I get in Amcat is this

<img width="1235" alt="dichte mist" src="https://user-images.githubusercontent.com/6417728/38041416-efd22284-32b1-11e8-9f6a-68e8a5236e37.png">

Not having this link means no access to the full text, so that is a problem. Since the link is always in the same place in the txt files downloaded from Lexis Nexis (between the medium name and the date), would it be possible to add a line to the upload script that reads this link and saves it as metadata in the URL field?

**Comment by vanatteveldt** [comment]
Hey Carina... Probably a bit late, but do you (still) have a lexisnexis file with URLs in it so I can test?

**Comment by CJStuart** [comment]
Closed due to inactivity
