### ISSUE TITLE
error 403 FORBIDDEN when trying to save articleset before deduplication

### ISSUE THREAD

**Issue by Kleinnijenhuis** [amcat/amcat#673]
When trying to save 1059 articles from a query to an articleset either in project 2 or in one of "my" projects (so as to deduplicate the search results in the new set), I'm getting Unknown error, server code 403 FORBIDDEN. See png below. Any idea?

![image](https://user-images.githubusercontent.com/6690321/38392343-77d5fc84-3927-11e8-8e25-ce4ba03e39a7.png)

**Comment by vanatteveldt** [comment]
Are you sure that you have write access to the project you're trying to save it to? You probably don't have write access to project 2 (almost no one does to prevent it from getting cluttered)
