### ISSUE TITLE
Query labels not used in coding job aggregation

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#677]
In the query screen, you can set a label for a query like this:

```
wiv#ollongren
```

This should use the query 'ollongren', but call it 'wiv' in tables or graphs. This is especially useful for long and complicated queries which otherwise clutter up graphs. 

In the coding job aggregation, this label is not used:

![wouter](https://user-images.githubusercontent.com/1736240/38796611-36b14f28-415c-11e8-88e4-332b90a42f2f.png)

The line should be called 'wiv', not 'ollongren' in the legend below the graph. Same presumably for tables etc.

**Comment by CJStuart** [comment]
I'm pretty sure I added this last night. Make sure to run a bower update.
