### ISSUE TITLE
Student created 25000 coding jobs by accident, should Amcat not prevent this?

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#679]
One of my students managed to create about 25000 coding jobs at once (project 1637). This huge amount of jobs is a problem, since it takes several minutes to load the coding jobs table, if it doesn't crash. Deleting more than one job at a time also isn't possible. I recommended the student to start a new project and import the articles and coding schemas from the old project, but I'm wondering if something could be done to prevent this kind of messing up.

Would a solution be to put a limit on the number of jobs you can create in one go, max. 100 for example? Or at least a warning? So if you have an article set containing 4000 articles and you want to make this into coding jobs with a job size of 20 articles each, AmCAT should say no or ask 'Creating this many jobs may cause long loading times. Are you sure?' and then add a yes and a cancel button for the user to click.

**Comment by CJStuart** [comment]
It would be nice, but we won't implement it in 3.5.
