### ISSUE TITLE
Line plots of multiple terms

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#680]
In the new AmCAT query I try to make a line plot of two terms, with data from BZK (project 29) per month number of articles of 

Ollongren
Knops

As a table it works fine, but as a line plot it only shows "Ollongren"  although it seems it gives to values per month. With the scattered plot this is seen more clearly. It gives two dots per month but both it says to be Ollongren.
The same is true with other terms. See screenshot
![screenshot from 2018-05-20 22-33-11](https://user-images.githubusercontent.com/6438205/40283408-f83a2d68-5c7d-11e8-901d-bc3a22a33f01.png)

**Comment by CJStuart** [comment]
This was fixed in amcat/amcat-query-js@3d525b1176c93da772599a1ac913ca44a07c9e3c

A bower update might be necessary.
