### ISSUE TITLE
Twee termen in line plot worden een lijn

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#681]
Volgens mij had je dit ooit al opgelost maar op de nieuwe site bzk.nieuwsmonitor.org zie ik het nog steeds?

Wanneer je twee termen onder elkaar zoekt en deze als twee lijnen per week bv wilt weergeven in een line plot dan krijg je slechts een lijn waar amcat steeds springt van de ene waarde naar de andere. 
![screenshot from 2018-07-17 17-24-09](https://user-images.githubusercontent.com/6438205/42827322-62d67920-89e6-11e8-934b-7802bbef3e18.png)

**Comment by CJStuart** [comment]
Ik zie dat de bower installatie nog niet helemaal up to date is. Dit zou op te lossen moeten zijn dmv:

    bower update -F
