### ISSUE TITLE
tweede as in lijngrafiek werkt niet (altijd)

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#682]
MArtijn, ik assign het aan jou maar als je geen tijd hebt, kun je het dan sturen naar Christian? Dank

Wanneer ik de codingjobs selecteer en dan een lijngrafiek wil maken met aantal artikelen op de y-as en versus gemiddelde mening mediaframe op de tweede y-as dan gebeurt er iets geks. Als ik eerst aantal artikelen doe en tweede mening mediaframe dan komt alleen de eerste lijn, maar als ik het andersom doe, dan doet ie het wel.

Overigens staat er 2 x gemiddeld mening mediaframe in de dropdowns en dat is ook niet correct
![screenshot from 2018-07-18 17-31-28](https://user-images.githubusercontent.com/6438205/42892767-f0cae3b6-8ab2-11e8-8463-3fdc95794b5d.png)
![screenshot from 2018-07-18 17-31-04](https://user-images.githubusercontent.com/6438205/42892775-f411eaa6-8ab2-11e8-89cd-ca9618f288b0.png)

**Comment by martijnbastiaan** [comment]
@CJStuart Kun jij hier naar kijken?

**Comment by CJStuart** [comment]
Ja, prima!

**Comment by CJStuart** [comment]
Ik heb wat moeite om dit te reproduceren. Bestaan er misschien meerdere velden 'Mening mediaframe' in het codingschema, waarvan er één niet gebruikt wordt?
In dat geval zou die namelijk inderdaad niet in de grafiek verschijnen, aangezien er geen coderingen voor zijn.

**Comment by nruigrok** [comment]
Volgens mij is dit nu opgelost. Het probleem werd veroorzaakt doordat we twee verschillende codebooks hanteren, nl voor artikelniveau en zinsniveau. Volgens mij werkt het wel als je alleen articles doet of alleen issues. Zal ik nog even testen zo.

**Comment by nruigrok** [comment]
dus idd conflicteren schema's
