### ISSUE TITLE
Volgorde in Bar plot van de bars

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#683]
Bij de bar plots zou het mooi zijn als de volgorde kan worden bepaald door ofwel de eerste y-as ofwel de 2e y-as (maar als dat lastig is dan gewoon alleen de eerste y-as)
![screenshot from 2018-07-18 18-09-42](https://user-images.githubusercontent.com/6438205/42893871-c2f96496-8ab5-11e8-9578-93bc1f96d3da.png)

**Comment by martijnbastiaan** [comment]
Je bedoelt dat je oplopend/aflopend sorteren neem ik aan? Dus in je plaatje bijvoorbeeld:

Bestuur, Wonen/Bouwen, AIVD, Overheidsorganisatie, ....

**Comment by nruigrok** [comment]
JA dat bedoel ik idd



Dr. N. Ruigrok
Brouwersgracht 935
1015 GK Amsterdam
+31-627588586
//nieuwsmonitor.org
nelruigrok@nieuwsmonitor.org

2018-07-19 23:40 GMT+02:00 Martijn Bastiaan <notifications@github.com>:

**Comment by martijnbastiaan** [comment]
Fixed in https://github.com/amcat/amcat/commit/d4901af5e5653aa0b662b82be0139ebba773b4e1. Kun je het testen voor je codings?
