### ISSUE TITLE
Aggregatie onderwerp mbv codebook

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#684]
Je kunt nu onderwerpen alleen aggregeren op het 'hoogste' niveau. Idealiter zouden we dit op ALLE niveaus doen die ook in de codebooks voorkomen. Daar wordt binnen BZK veel gebruik van gemaakt. ZO heb je bouwen/wonen wat weer onderverdeeld is in bouwen en wonen en dat wil men graag zien, maar is nu niet mogelijk.

Ook zou het heel fijn zijn als we foute coderingen weg kunnen halen, al snap ik dat dat wellicht heel lastig is als ze gewoon fout gecodeerd zijn...zie bijlage
![screenshot from 2018-07-18 19-23-09](https://user-images.githubusercontent.com/6438205/42897429-4de0905c-8ac0-11e8-8f5b-d85bd4125c2d.png)

**Comment by martijnbastiaan** [comment]
De weergave gaat wellicht tricky worden (diepere niveaus moeten ook in de tabel netjes geindent worden neem ik aan?), maar voor de rest voorzie ik geen problemen om dit op korte termijn te implementeren.

**Comment by nruigrok** [comment]
Nee hoeft niet in de tabel duideiijk te worden. In excel kun je in de pivot
gewoon niveau 2 of 3 kiezen en krijg je dus meer issues te zien. Dat is
alles en dat is goed genoeg.





Dr. N. Ruigrok
Brouwersgracht 935
1015 GK Amsterdam
+31-627588586
//nieuwsmonitor.org
nelruigrok@nieuwsmonitor.org

On Thu, Jul 19, 2018 at 11:42 PM, Martijn Bastiaan <notifications@github.com

**Comment by martijnbastiaan** [comment]
Zie: https://giant.gfycat.com/CleanEssentialBandicoot.webm

Ik zal binnenkort de commit doorvoeren zodat het getest kan worden.
