### ISSUE TITLE
Bronselectie lijkt niet te werken

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#686]
In de filters voor gecodeerde data klik ik bij Bron BZK aan en alle descendents. Als ik vervolges een tabel maak per bron dan krijg ik ook bronnen die NIET bij BZK horen.

(ik had hier ook nog filter gedaan op twee onderwerpen, dat werkt wel, maar in een tabel geeft ie dat niet goed weer, dan komt er geen foutmelding maar gebeurt er niets, net als bij vorige issue)

zie bijlage 
![screenshot from 2018-07-18 19-50-31](https://user-images.githubusercontent.com/6438205/42898633-fc97a45c-8ac3-11e8-92cd-4a0d72674002.png)

**Comment by nruigrok** [comment]
Het lijkt erop dat ie bij de bronselectie alle ARTIKELEN meeneemt waarin die bron voorkomt en vervolgens ALLE bronnen laat zien die in de artikelen voorkomen. Maar BZK wil graag dat ALLEEN de zinnen worden geselecteerd waarin BZK voorkomt en dat dan in de Tabel wel wordt uitgesplitst naar aantal artikelen en gemiddelde mening (die weer gebaseerd is op aantal zinscoderingen). Waarbij dus alleen BZK en onderliggende stakholders/bronnen worden genoemd in de tabel.

**Comment by vanatteveldt** [comment]
(zinnen = coderingen, toch?)

**Comment by nruigrok** [comment]
Ja sorry coderingen bedoel ik en die zijn op zinsniveau

**Comment by martijnbastiaan** [comment]
Kun je wellicht een concreet voorbeeld geven van wat je zou willen zien?

**Comment by nruigrok** [comment]
Nou een vraag is bv ALLE onderwerpen waarover BZK als stakeholder iets heeft gezegd. Dus we willen dan alle zinnen waarin BZK stakeholder is gecodeerd. Vervolgens willen we die afzetten tegen de onderwerpen waarover men iets heeft gezegd in termen van aantallen artikelen en teneur van het aantal zinnen. Maar dan willen we dus ALLEEN die zinnen gebruiken waarin BZK als bron is gebruikt en alle andere bronnen uit die artikelen willen we dan niet meer.
is dat duidelijker?

**Comment by martijnbastiaan** [comment]
Het is inderdaad zo dat alles boven de "output options" streep wordt gebruikt om artikelen te filteren. Op die artikelen wordt vervolgens het output script uitgevoerd. Ik zal kijken wat ik hier kan doen, maar het is een vrij sterke aanname in de code op het moment.

**Comment by martijnbastiaan** [comment]
Fixed in https://github.com/amcat/amcat/commit/d27fe2ef12f4f6f1da7d79df21dd066e1d3803b3
