### ISSUE TITLE
Scraper newsdesk misses often publisher and link to original articles not possible

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#688]
de scraper van newsdesk mist vaak een publisher. Dat komt waarschijnlijk door de scraper. Zie bijlage, het gaat m.i. altijd om die h4
![screenshot from 2018-07-19 08-46-43](https://user-images.githubusercontent.com/6438205/42925988-5277ebe0-8b30-11e8-8603-867b7a6a35f9.png)

Punt is ook dat je dan niet kunt doorklikken naar de originele artikelen. Misschien hoort dat zo, maar is toch wat verwarrend.

![screenshot from 2018-07-19 08-43-14](https://user-images.githubusercontent.com/6438205/42925994-55ce3b32-8b30-11e8-885c-d729777e6f9b.png)

**Comment by martijnbastiaan** [comment]
Duidelijk! 

* `h4` wordt inderdaad niet meegenomen. 
* Publisher zou meegenomen moeten worden. Heb je een artikel mét publisher die de scraper nite meeneemt?
* Linken naar artikelen: is helaas niet mogelijk voor zover ik weet..

**Comment by nruigrok** [comment]
Nou gaat vooral mis op de h4 volgens mij, geen voorbeeld zo gauw van publisher die wel meegenomen met worden. Die h4 zijn er alleen best veel, vandaar dat het opvalt. Kan dat nog meegenomen of niet?

**Comment by martijnbastiaan** [comment]
Gaat zeker lukken!

**Comment by nruigrok** [comment]
Top! Thanks



Dr. N. Ruigrok
Brouwersgracht 935
1015 GK Amsterdam
+31-627588586
//nieuwsmonitor.org
nelruigrok@nieuwsmonitor.org

On Fri, Jul 20, 2018 at 12:19 AM, Martijn Bastiaan <notifications@github.com

**Comment by martijnbastiaan** [comment]
Fixed!
