### ISSUE TITLE
Uploading BZK not available in bzk.nieuwsmonitor.org

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#689]
De uploadpagina voor bzk ontbreekt in de bzk.nieuwsmonitor.org site. Deze hebben we wel nodig om ook coderingen te kunnen laten doen op deze site. 
![screenshot from 2018-07-22 11-17-39](https://user-images.githubusercontent.com/6438205/43413185-a4ff21fa-942f-11e8-92e1-e628f9ad4a80.png)

**Comment by vanatteveldt** [comment]
Je kan hem zelf toevoegen in de project settings:

![image](https://user-images.githubusercontent.com/1736240/43413293-f94142de-942f-11e8-80f8-1a8cb40f9766.png)
