### ISSUE TITLE
AmCAT opent niet: 502 Bad Gateway

### ISSUE THREAD

**Issue by vivianseljee** [amcat/amcat#690]
Ik heb geprobeerd AmCAT te openen via Google Chrome, maar ik krijg telkens de melding 502 Bad Gateway en de tekst nginx/1.4.6 (Ubuntu). Ik heb hetzelfde geprobeerd in Safari, waar ik normaal in ieder geval nog wel op de AmCAT-site kan komen, maar krijg hier dezelfde melding. Er is dus geen probleem met een coding job o.i.d., maar puur met het überhaupt bereiken van de website. Ik heb overigens eerder vandaag al gewerkt met AmCAT, dus het is niet dat ik altijd deze foutmelding krijg. Kan iemand me hierbij helpen? Alvast bedankt!

**Comment by vivianseljee** [comment]
Het is inmiddels opgelost, ik kan weer in AmCAT!

**Comment by vanatteveldt** [comment]
Er was gisteren inderdaad een korte storing, dank voor de melding!
