### ISSUE TITLE
AUTNES SERVER: SSL connection has been closed unexpectedly

### ISSUE THREAD

**Issue by daevil** [amcat/amcat#691]
!!! Only happening on the autnes server, works fine on amcat.nl !!!

Issue:
When trying to query any article set I get the following error message:

> Operational Error:
> SSL connection has been closed unexpectedly

This worked fine in the past but does not anymore since at least this week (potentially  up to 2 weeks before that (I was on holida yand not using it))

**Comment by CJStuart** [comment]
I restarted the servers, everything seems to work properly now. Please let me know if you run into any other problems.

**Comment by daevil** [comment]
It works again! Thanks a lot!

**Comment by daevil** [comment]
So it is ok for me to post issues that only occur on the AUTNES server in here? Was wondering about that...

**Comment by vanatteveldt** [comment]
not sure where else to post them... and if you only email they get lost too easily. If we start getting a lot of Autnes issues we might want to open a separate bug tracker :)

**Comment by daevil** [comment]
Understood. Someone told me once you guys don't want Autnes issues in here. Thanks!

**Comment by vanatteveldt** [comment]
Heh. Well, I don't think we have any real policies about it... feel free to contact us any way you like :)
