### ISSUE TITLE
simplify / improve coding aggregation interface

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#698]
The current interface for aggregating on coding jobs is complicated and non-intuitive:

![image](https://user-images.githubusercontent.com/1736240/45212632-aa30db80-b295-11e8-9df2-7abed10c2f00.png)

**Comment by martijnbastiaan** [comment]
Any ideas on how to improve it?

**Comment by CJStuart** [comment]
I don't think it's still relevant to do this in amcat 3.5.
(Feel free to reopen if you disagree.)
