### ISSUE TITLE
Coding: Cannot save data

### ISSUE THREAD

**Issue by daevil** [amcat/amcat#706]
Version:
autnes.amcat.nl (AmCAT Navigator 3.5rc1)

Observed:
When trying to save my coding on a unit-scheme (sentence level) coding job I get the following error message: "Cannot save data. 1) Make sure all coded sentences have a sentence number.2) Make sure no codings are left empty if your project does not allow this." and can not save nor continue to the next article.

I tried old coding jobs/schemes that use unit-coding and used to work with an older version of amcat and they don't allow me to save anymore either. Therefor I am guessing this is a problem related to the new version of the navigator we are using on autnes.amcat.nl

STR:
- Assign yourself a codingjob using the "Populism gregorr25" coding scheme and any article set
- Start coding
- Try to save your sentence coding
- Behold the error

**Comment by CJStuart** [comment]
This has been fixed in the latest update
