### ISSUE TITLE
codings query with two axes fails

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#715]
If you do a codingjob query with two codingvalue-based group-by axes, the result is empty. 

e.g. http://bzk.nieuwsmonitor.org/projects/1/queryselect/ query 5, works if you drop the secondary aggregation, but returns empty with both primary and secondary aggregation

![image](https://user-images.githubusercontent.com/1736240/48579123-e595f900-e91b-11e8-91f1-91830b2b7faa.png)

Martijn's diagnosis:

```
https://github.com/amcat/amcat/blob/master/amcat/tools/aggregate_orm/categories.py#L312
dat is het probleem
coding_values is 1 join
(denk ik)
Dus als je twee keer een SchemafieldCategory hebt dan gaat het fout
```

**Comment by CJStuart** [comment]
Fixed: https://github.com/amcat/amcat/commit/77860f5298c4f65447d67ddcb41ced0d754999d6
