### ISSUE TITLE
Delete selections at once

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#716]
Wanneer we in AmCAT coderingen selecteren dan moet je ze een voor een wegklikken als je ze wilt verwijderen. Het zou fijn zijn als er een knop was dat je ze allemaal in een keer kunt verwijderen.

![screenshot from 2018-12-03 10-48-44](https://user-images.githubusercontent.com/6438205/49366290-43cb2600-f6e9-11e8-85e7-9d78a09c5c23.png)

**Comment by CJStuart** [comment]
Dit kan nu mbv de "select all" knop.
