### ISSUE TITLE
No link to inividual articles Facebook when using search terms

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#719]
Wanneer ik zoek in project 3 van bzk op coosto en dan selectie FB dan doet de link naar individuele FB artikelen het soms niet, soms wel. (hier heb ik als zoekterm gebruikt: bzk OR knops OR rutte OR ollongren OR npo OR politie en dan per dag een tabel gemaakt) Zie hieronder. 

Kan het zo zijn dat wanneer de zoekterm in de metadata voorkomt het dan niet wordt getoond als artikel? ik kan niet bedenken waarom het anders soms wel soms niet kan.

![screenshot from 2018-12-09 12-29-06](https://user-images.githubusercontent.com/6438205/49696702-2812c480-fbae-11e8-8562-80bf86bbc118.png)

**Comment by CJStuart** [comment]
Seems to have been a timezone issue. Fixed in
https://github.com/amcat/amcat-query-js/commit/15881365e97e93e9a64f1f49a013900ca9e39f0e.

I'll update the BZK amcat server later today
