### ISSUE TITLE
505 Bad Gateway Server is down 

### ISSUE THREAD

**Issue by sebgaly** [amcat/amcat#726]
I am using the autnes.amcat.nl server. But as of this morning I cannot reach the server anymore. I get

502 Bad Gateway
nginx/1.10.3 (Ubuntu)

I hope this is only a temporary issue. Please let me know as soon as possible what is going on, as we have codings in progress on this server.

All the best,
Sebastian

**Comment by CJStuart** [comment]
It's back up

**Comment by sebgaly** [comment]
The server appears to be down again. Any chance there is a quick fix again? ; )

**Comment by vanatteveldt** [comment]
Should be back up!
