### ISSUE TITLE
Sentence coding does not work (AmCat 3.5.rc1)

### ISSUE THREAD

**Issue by sebgaly** [amcat/amcat#730]
I am working under AmCAT version 3.5.rc1 at autnes.amcat.nl

1) I am trying to code something on the sentence level/via Unitschema
    See for example this codingjob:
    http://autnes.amcat.nl/projects/3/codingjobs/2352/code
 

2) The following problems appear:

- I cannot select a sentence number
The dropdown gives all the correct sentence numbers of the article selected for coding, but no matter which number I select, it always resets to "1.1" when going to the next field or when trying to save. I suppose that this is also causing the next problem:

- I cannot save any coding
If I didn't enter any codings in any of the fields "Finish & Continue" jumps to the next article and changes the Status to "finished". However, if I type anything in any of the fields (regardless of their data type), both "Save" and "Finish & Continue" result in the following message:
> Cannot save data. 1) Make sure all coded sentences have a sentence number.2) Make sure no codings are left empty if your project does not allow this.

![image](https://user-images.githubusercontent.com/33219861/52654473-53899680-2ef2-11e9-9d70-fdaee9227654.png)

No fields are set to being required in the coding schema, 
The network tab of the browser doesn't show any error except for some images that fail to load (?):

![image](https://user-images.githubusercontent.com/33219861/52655420-67ce9300-2ef4-11e9-933d-6393ea7d8df7.png)

In the console tab of the browser however, the following error appers whenever I interact with the sentence number field:

![image](https://user-images.githubusercontent.com/33219861/52656048-d6f8b700-2ef5-11e9-8e11-d21acc9f3142.png)

3) I already tried (same result in either case):
 - refreshing via ctrl+F5
 - the same in a different browser (Chrome and Firefox)
 - a different sentence level coding schema on different articles

**Comment by sebgaly** [comment]
Hi guys,

is there any news regarding this issue yet?
We are planning a sentence level coding of a certain volume in the upcoming month and need to know whether we will be able to use AmCAT or if we will have to find another solution. Do you think there will be a solution in the next few weeks or so?

All the best!

**Comment by CJStuart** [comment]
This has been fixed in the latest update
