### ISSUE TITLE
More than one option where actor can occur

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#732]
Nu is het in het query scherm van de gedeerde artikelen alleen mogelijk om OF mediaobject OF stakeholder te kiezen als je gecodeerde artikelen wilt filteren. Echter het zou fijn zijn als als je zou kunnen zoeken op meerdere opties. Bv Als je wilt kijken wanneer Rutte OF als stakeholder aan het woord komt OF dat er over hem gesproken wordt. Nu kun je maar een tegelijk kiezen. De opties eronder maken de selectie alleen maar nauwer, dus als Stakeholder EN als mediaobject en dit optie is soms fijn, maar een OF OF zou ook fijn zijn!

![screenshot from 2019-02-13 13-07-59](https://user-images.githubusercontent.com/6438205/52710788-7ff3f000-2f90-11e9-9e43-c61cd60685d1.png)

**Comment by CJStuart** [comment]
Ik heb een knop toegevoegd waar je kan selecteren of 'any' of 'all' filters moeten matchen. Door 'any' te kiezen wordt een artikel dus geselecteerd als maar één van de geselecteerde codings matcht. 

Het is nu alleen van toepassing op sentence codings, dat leek mij het meest logische, maar ik weet niet zeker of dat de bedoeling is.

**Comment by nruigrok** [comment]
Ja dat lijkt me prima oplossing voor nu.
