### ISSUE TITLE
Number of codings is not calculating correctly

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#737]
De number of codings in AmCAT verwijst nu naar zowel sentence codings als article codings en dat is niet correct.  De number of codings moeten alleen sentence codings bevatten, dus waar sentence is not NULL.

**Comment by CJStuart** [comment]
Het lijkt me dat dit maar net van de use case afhangt. Misschien moet hier een optie van gemaakt worden?

**Comment by nruigrok** [comment]
Nou nee want in het geval van coderingen zijn de coderingen altijd aan setences gebonden en niet aan artikelen. Als een optie maken makkelijker is prima, maar liever gewoon alleen als zinscoderingen omdat AmCAT voor gebruikers al best ingewikkeld is.
