### ISSUE TITLE
Amcat selection is not working properly 

### ISSUE THREAD

**Issue by nruigrok** [amcat/amcat#738]
In AmCAT gaat het mis wanneer je een tweede selectie maakt. Bv naast onderwerp ook mediaobject BZK. Zie in Amcat Query 60 als voorbeeld. Daar vragen we onderwerp = woningmarkt en BZK als mediaobject.
Deze gaat goed want per medium vindt hij in totaal 5 artikelen.

Wanneer je de query runt "Stakeholder die fout gaat met mediaobject in selectie" dan zie je dat het goed gaat, namelijk in totaal zijn er 11 coderingen waarin het EN gaat over het onderwrep Woningmarkt en waarbinnen BZK als mediaobject is gecodeerd. 

Echter wanneer je de query runt "Stakeholder die fout gaat met number of codings" zie je dat met dezelfde selectie (onderwerp=woningmarkt en mediaobject=BZK) er niet 11 maar veel meer coderingen opeens zijn. 

Ergens gaat het dus fout tussen de selectie en het aantal codings. Zie ook screenshots.

![screenshot from 2019-02-25 17-07-27](https://user-images.githubusercontent.com/6438205/53353481-162afd00-3925-11e9-8b47-bd5e5ade7016.png)
![screenshot from 2019-02-25 17-33-08](https://user-images.githubusercontent.com/6438205/53353484-17f4c080-3925-11e9-9dbb-3dcd8ec0c194.png)
![screenshot from 2019-02-25 17-34-36](https://user-images.githubusercontent.com/6438205/53353485-1a571a80-3925-11e9-8f4d-72cbbf154d14.png)

**Comment by CJStuart** [comment]
Ik geloof dat dit nu naar behoren werkt. Ik heb het oude gedrag laten staan als 'Total number of coded sentences', maar wellicht kan dit wel helemaal weg.
