### ISSUE TITLE
AUTNES Server can't be reached

### ISSUE THREAD

**Issue by andreasf22** [amcat/amcat#745]
Hey,
I am trying to connect to the AUTNES Version of AmCat (autnes.amcat.nl), but it seems to be down at the moment. Using Chrome, it is not even possible to log in (see screenshot below). When using Firefox, logging in is possible, but the same error message accurs when trying to open an article. Furthermore, when using R, it is not possible to access an AmCat-project.

The error message is a follows:
500 : An Error has occurred
ResponseError: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error. 

![Screenshot Error 500](https://user-images.githubusercontent.com/50229588/58234011-d31ed100-7d3d-11e9-83fb-3f369b4d136b.png)

 I tried using different browsers, refreshing and restarting them, and restarting the system as a whole.

Thanks in advance!
Andreas

**Comment by vanatteveldt** [comment]
There was an issue of disk space (log files grew too much), should be fixed now, thanks for reporting!

**Comment by andreasf22** [comment]
After working well yesterday, it is again not possible to connect to autnes.amcat.nl (neither in Firefox, Chorme, Explorer, Edge nor connecting via R). This time there is not even an error code, the website itself is not loading at all.

**Comment by vanatteveldt** [comment]
Does it work again now?
