### ISSUE TITLE
http://autnes.amcat.nl/ 502 Server Down

### ISSUE THREAD

**Issue by mrwunderbar666** [amcat/amcat#746]
Trying to access http://autnes.amcat.nl/ this morning from Vienna, gives this result:
 
![image](https://user-images.githubusercontent.com/20080275/59666492-3a049e00-91b5-11e9-8c99-e619fe9bc030.png)

Blank page reads as follows:

> 502 Bad Gateway
> nginx/1.10.3 (Ubuntu)

- reproducable on different machines and browsers
- https://downforeveryoneorjustme.com/autnes.amcat.nl confirms

Thanks!

**Comment by vanatteveldt** [comment]
Fixed, thanks for reporting!

**Comment by mrwunderbar666** [comment]
Awesome, thanks!
