### ISSUE TITLE
Browser blocks 'unsafe' amcat website

### ISSUE THREAD

**Issue by joepschaper** [amcat/amcat#752]
Hi developers,

I'm trying to code articles manually using the annotator, but I can't reach my list of coding jobs, because Google Chrome blocks the site because the security certificate of amcat.nl seems to be overdue. I get a similar error when I try to visit amcat.nl using Firefox.

Best,

Joep

**Comment by nruigrok** [comment]
Hi Joep,

Volgens mij had ik dat ook vd week een keer en dan moet je gewoon naar
accept unsafe page gaan, via advanced. Dan doet ie het weer.

Gr,
Nel


Dr. N. Ruigrok
Brouwersgracht 935
1015 GK Amsterdam
+31-627588586
//nieuwsmonitor.org
nelruigrok@nieuwsmonitor.org

**Comment by joepschaper** [comment]
Ha Nel!

Bij mij blijft ie dan hangen bij het laden van mijn lijst codingjobs. Maar dat kan natuurlijk een apart probleem zijn.

Joep

**Comment by nruigrok** [comment]
Hhmm dat is gek, want bij mij laadt ie die wel gewoon, zowel in chrome als
in firefox...dus het kan ook niet elastic zijn.
Ik vraag de chef wel even :-)

Gr,
Nel

**Comment by joepschaper** [comment]
Behoede man en amcat-held! :)

**Comment by vanatteveldt** [comment]
Certificate needed to be reloaded, fixed!

```
sudo /etc/init.d/nginx reload
```

**Comment by nruigrok** [comment]
En doorrrr!
Succes,
Nel

**Comment by joepschaper** [comment]
Top, bedankt!!
