### ISSUE TITLE
"Your connection is not private" NET::ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by vivianseljee** [amcat/amcat#754]
I tried to open AmCAT, but keep getting the warning that my connection is not private (NET::ERR_CERT_DATE_INVALID). I've tried several things to fix this issue myself, but it does not seem to work. Does anyone else have this issue? Or knows how to fix this? 

I found this in an article about the issue: "If you DON’T manage the website in question:
You’ll need to contact the website owners. Just send them:
- A screenshot of the NET::ERR_CERT_DATE_INVALID message you’re seeing
- The URL on their site that you’re trying to visit
- A link to this article"
[https://comodosslstore.com/resources/how-to-fix-net-err_cert_date_invalid-error-on-google-chrome/](url)

I'll attach the screenshots of the warning. It's not about a specific URL, it's about the website in general. 

<img width="1440" alt="Schermafbeelding 2019-10-20 om 19 41 26" src="https://user-images.githubusercontent.com/42320132/67163734-ca750a00-f372-11e9-8ad6-1d4cc5fef096.png">
<img width="1440" alt="Schermafbeelding 2019-10-20 om 19 41 32" src="https://user-images.githubusercontent.com/42320132/67163735-ca750a00-f372-11e9-95e2-2fc18f0d84fa.png">

I hope anyone can help me with this issue. Thanks in advance!

**Comment by vanatteveldt** [comment]
Should be fixed now!
