### ISSUE TITLE
autnes.amcat.nl: Annotator doesn't load for specific user

### ISSUE THREAD

**Issue by mrwunderbar666** [amcat/amcat#756]
One of my project mates cannot use the annotator anymore. The problem is rather strange, as I cannot replicate it.

- URL: http://autnes.amcat.nl/projects/34/codingjobs/
- Affected user: meixnervalentin (ID: 119)
- Occurring since Friday (13.12.2019)
- Browser Google Chrome
- Problem Description: Annotator is stuck at the Loading overlay (see screenshot)

<img width="960" alt="AmCat Programm" src="https://user-images.githubusercontent.com/20080275/70866703-29b75b00-1f6d-11ea-95a4-e3849f102cde.png">

I am requesting further details from the user (chrome build, used extensions, etc).

**Comment by vanatteveldt** [comment]
Also ask them to hit control+f5 to refresh and/or try in another browser or private mode.

If that doesn't work, ask them to press f12 to check the console and network log for errors. 

Thanks!

**Comment by mrwunderbar666** [comment]
I asked the user to clear the cookies for amcat and also to provide some diagnostic data (see below). I also told the user to try your suggestion. Meanwhile, he somehow resolved the issue by installing a different browser. So I guess it could be an issue with his local cache.


Chrome: Version 79.0.3945.79 (Offizieller Build) (64-Bit)
 
extensions: 
```
aapocclcgogkmnckokdopfmhonfmgoek : Präsentationen : version 0_10
ahfgeienlihckogmohjhadlkjgocpleb : Web Store : version 0_2 
aohghmighlieiainnegkcijnfilokake : Docs : version 0_10 
apdfllckaahabafndbhieahigkjlhalf : Google Drive : version 14_2 
blpcfgokakmgnkcojhhkbfbldkacnbeo : YouTube : version 4_2_8 
caljgklbbfbcjjanaijlacgncafpegll : Avira Password Manager : version 2_9_0_3316
ccbpbkebodcjkknkfkpmfeciinhidaeh : Avira Safe Shopping : version 2_7_2_2033
felcaaldnbdncclmgdcncolpebgiejap : Tabellen : version 1_2 
fheoggkfdfchfphceeifdbepaooicaho : McAfee® WebAdvisor : version 8_0_0_34745
gfdkimpbcpahaombhbimeihdjnejgicl : Feedback : version 1_0 
ghbmnnjooekpmoecnnnilnnbdlolhkhi : Google Docs Offline : version 1_7
gighmmpiobklfepjocnamgkkbiglidom : AdBlock – der beste Ad-Blocker : version 4_0_2
kmendfapggjehodndflmmgagdbamhnfd : CryptoTokenExtension : version 0_9_74
mfehgcgbbipciphmccgaenjidiccnmng : Cloud Print : version 0_1 
mhjfbmdgcfjbbpaeojofohoefgiehjai : Chrome PDF Viewer : version 1
neajdppkdcdipfabeoofebfddakdcjhd : Google Network Speech : version 1_0
nkeimhogjdpnpccoofpliimaahmaaome : Google Hangouts : version 1_3_14
nmmhkkegccagdldgiimedpiccmgmieda : Chrome Web Store-Zahlungen : version 1_0_0_5
pjkljhegncpnkpknbcohdijeoejaedia : Google Mail : version 8_2
pkedcjkdefgpdelpbcmbmeomcjbeemfm : Chrome Media Router : version 7919_1028_0_0
```

**Comment by mrwunderbar666** [comment]
I got his console output, seems to be a jquery problem:

<img width="960" alt="AmCat Console" src="https://user-images.githubusercontent.com/20080275/70982827-f46b5400-20b7-11ea-9b57-054195068468.png">

I also checked his network log, and it appears that his jquery script is loaded from the cache:

![image](https://user-images.githubusercontent.com/20080275/70982989-4d3aec80-20b8-11ea-88eb-48f34fac0935.png)

The strange part is that refreshing the page with F5 (several times) did not help. 

I presume, wiping his local cache would probably solve it... 

[networklog.zip](https://github.com/amcat/amcat/files/3972454/networklog.zip)

**Comment by vanatteveldt** [comment]
Yeah exactly, probably a cached older version that is causing the problem. Sometimes pressing control+F5 works. Closing the issue for now as I don't think there's anything I can do to fix it.

**Comment by mrwunderbar666** [comment]
User confirmed that wiping the cache helped. 

Thanks!
