### ISSUE TITLE
Autnes Amcat-Server down (Error 500)

### ISSUE THREAD

**Issue by andreasf22** [amcat/amcat#757]
Hi,
when trying to log-in to the AUNTES-Amcat-Page (autnes.amcat.nl), Error 500 (InternalError: missing chunk number 0 for toast value 9943102 in pg_toast_2619) is reported - Screenshot is attached below.
Any idea on how to fix this?
Best Regards, Andreas
![AUTNES_Error500_20191225](https://user-images.githubusercontent.com/50229588/71450351-aa8e0800-2760-11ea-9249-51744ede0d69.png)

**Comment by mrwunderbar666** [comment]
Update: now error is a 502 Bad Gateway

**Comment by vanatteveldt** [comment]
Should be fixed now

(problem was https://stackoverflow.com/questions/47533639/postgres-log-file-contains-missing-chunk-number-0-for-toast-value-815441-in-pg)

**Comment by vanatteveldt** [comment]
For reference

**Comment by vanatteveldt** [comment]
(should be back up)
