### ISSUE TITLE
Captcha not loading in registration form

### ISSUE THREAD

**Issue by tmnssn** [amcat/amcat#763]
Hi, I've been trying to sign up for AmCAT but unfortunately I'm unable to do so as the captcha module of the registration form doesn't load. This issue occurs in Safari, Chrome and Firefox on Mac.

**Comment by vanatteveldt** [comment]
This is actually only for the wiki, right? AmCAT doesn't use a captcha, but
the 'open' amcat server has been shut down after a data breach so it
probably redirects to the wiki page. I'll put up a more informative message
this weekend.
