### ISSUE TITLE
502 Bad Gateway - http://autnes.amcat.nl/

### ISSUE THREAD

**Issue by mrwunderbar666** [amcat/amcat#770]
Hi,

autnes.amcat.nl is down, could you please restart it?

Thanks

**Comment by mrwunderbar666** [comment]
@vanatteveldt :pleading_face: :pray:

**Comment by vanatteveldt** [comment]
Should be back up - we had a system restart and I didn't know autnes.amcat.nl was still in use so didn't restart it. 

Feel free to reach out to me on signal as well, I didn't see the notification for the first message!
