### ISSUE TITLE
rights to see article texts when linking sets to another project

### ISSUE THREAD

**Issue by carinajacobi** [amcat/amcat#85]
When you are not a user of a project, you cannot see the text of the articles in that project. You can link articlesets to another project of which you are a user, but then you still cannot see the texts. However, you can assign them to yourself as a codingjob, and then suddenly you can see the texts. 

Isn't this strange, i.e. wouldn't it make more sense to restrict linking sets to another project to users of the original project?

**Comment by vanatteveldt** [comment]
Dupe of #370, I think we should restrict linking to "read' access users and have permissions propagate through set membership
