### ISSUE TITLE
Get rid of annotator/navigator names

### ISSUE THREAD

**Issue by vanatteveldt** [amcat/amcat#92]
I don't think these names are really meaningful anymore. I would prefer to just drop them,  and call everything 'amcat'. The distinction on app level makes sense, but we can adjust the routing table and the UI header. 

old urls:
annotator: http://amcat.nl/annotator/project/29/codingjob/3734/
navigator: http://amcat.nl/navigator/projects/29/codingjobs/3734/

new urls:
navigator: http://amcat.nl/projects/29/codingjobs/3734/
annotator: http://amcat.nl/projects/29/codingjobs/3734/code
OR
annotator: http://amcat.nl/coding/projects/29/3734/ 

I think the only non-project based view that we currently have is the 'user details' view, that can probably be integrated under /account. @martijnbastiaan what do you think?

**Comment by CJStuart** [comment]
This does make sense to me, the namespaces don't really add anything to the urls, I made a pull request that implements this following the 

http://amcat.nl/projects/29/codingjobs/3734/code

scheme

**Comment by vanatteveldt** [comment]
@martijnbastiaan  do you see any complications?

**Comment by martijnbastiaan** [comment]
This seems OK to me. I think we just need to merge it in order to find all the hardcoded urls :-).

**Comment by martijnbastiaan** [comment]
Merged in master. Marking as fixed.
